### ISSUE TITLE
Cannot open two UIs at the same time

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#1020]
When trying to load a second UI one gets the error message as shown below. It seems that the Temp\APSIMX file is locked by the first UI and this prevents the second to open properly.

An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll
Additional information: The process cannot access the file 'C:\Users\....\AppData\Local\Temp\ApsimX' because it is being used by another process.

**Comment by zur003** [comment]
Just wanted to add some notes here, in case someone wants to revisit this later. The problem largely stems from the matter of trying to clean up "temporary" files created for the dynamically created assemblies generated by the Manager. These are created in an ApsimX sub-folder of the user's temporary directory, but getting rid of them is problematic. Once they have been loaded, they remain open until the current AppDomain is unloaded. This makes it hard for the program to clean up after itself, so as an alternative, we try to do cleanup of any old files when the ApsimX GUI starts. That's fine, unless another ApsimX instance is still using those files and holding them open, resulting in the exception described in this issue.
Now there is a way the program should be able to clean up after itself. When it starts, it can create a new AppDomain, load itself into the new domain and execute itself (look at http://stackoverflow.com/questions/2648411/how-do-i-create-an-appdomain-and-run-my-application-in-it to see how this can be done), then unload the domain at the end. When the domain has been unloaded, the old files should be free to be deleted. This almost works, but it you're running under the debugger, the .PDB files remain open. I couldn't find any easy way to avoid that problem, so for now am sticking with the approach of doing cleanup at the start of a new session, rather than at the end of an old one, but now catching any raised exceptions (and ignoring them).
