### ISSUE TITLE
Edit graph labels is very slugish

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#108]
if you change the name of an axis label the text box types very slowly

**Comment by zur003** [comment]
This appears to be the result of the call to plot1.Refresh() in the GraphView.AxisMinimum function. It's throwing multiple exceptions. I don't know much at all about OxyPlot, but why is this call there? Removing it, oddly enough, causes the regression lines to not be rendered. 
For that matter, ticking regression off, then back on, doesn't immediately refresh display of the regression lines. You see them only when you leave the plot, then return to it (which I should probably open as a separate issue).

**Comment by hol353** [comment]
This call is here because the code for showing regression lines wants to know the auto calculated x and y axis scales so that it can scale the axes the same as each other. It's a horrible hack but I can't find a better way to do it. You would think that oxyplot could provide the x and y axis min and max but they always seem to be zero.

**Comment by zur003** [comment]
I've found a fix, and will submit it shortly.
