### ISSUE TITLE
Entering values in Operations Module and Soil Water grids is very slow

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1091]
I am working on Prototypes/WheatValidation.apsimx which is a large file and the GUI is extreamly slow to respond to changes typed in operations and also in the soil water grids

**Comment by zur003** [comment]
@HamishBrownPFR - Can you provide a more precise description (i.e., steps needed to see the performance problem)? WheatValidation.apsimx is big, and I'd expect it to be slow to load, and slow to display some of the stuff in the datastore, but I don't see why there should be any response problems with the Operations editor or the soil water grid. For those, overall size of the ApsimX file shouldn't make any difference. (Unless maybe you're running out of memory???)

**Comment by HamishBrownPFR** [comment]
@zur003 - If I restart the GUI thinks go quickly when editing values in the soil water grid cells for a start but the more editing I do the slower it gets.  At the moment I am working in the NewZealand folder on the Lincoln2014 experiment.  I have a soil description in each of the treatments and am editing them (entering values and copying and pasting) and after a while things just grind to a hault.  It is quick to open a cell for editing but in hangs for a long time on hitting enter.

The Operations module.  Just try typing something in there, it is slow for a start and gets really slow if the UI has been open and doing stuff like above.

**Comment by HamishBrownPFR** [comment]
Screen shot to show where I am currently working and having speed issues.  Setting up these treatments (highlighted areas) by typing and pasting and gradually it becomes slower and slower
![image](https://cloud.githubusercontent.com/assets/7295858/18073955/450c79e4-6ebd-11e6-971f-4ab5dda23d31.png)

**Comment by HamishBrownPFR** [comment]
@zur003 My computer is using alot of memory (~80%) when I am debugging APSIMX.  Not sure if this is the problem.

**Comment by zur003** [comment]
@HamishBrownPFR No, that's not exactly the problem. I've just had a closer look. The real problem is that the various presenters aren't being cleaned up correctly, and are persisting even after their associated views have disappeared. After a while, you can end up with a bunch of, say, ProfilePresenters which are still trying to handle every "ModelChanged" event that occurs. Each time you enter a character in the irrigation operation editors, an event gets fired to every member of this collection of zombie presenters which then access data structures in an effort to update their views.

I've already fixed this problem in the Gtk# version of the user interface. Now it's a question of whether I fix this in the Windows.Forms version, or use this as leverage to get everyone to transition to Gtk#.

**Comment by HamishBrownPFR** [comment]
@zur003 @hol353 If Gtk is working as well as the windows version then we should switch it in.  There is not point maintaining parallel interfaces if the gtk version will work for windows and linix

**Comment by hol353** [comment]
Yes I agree. Go for it Eric.
