### ISSUE TITLE
Documenting units and descriptions in ApsimX

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1205]
In the last Reference Panel we discussed the desirability of having some consistency in the units used across the various models in ApsimX.  The first stage (and if it gets too hard it might also be the last stage!) of this is to properly document what the current units are and get understandable descriptions.  Dean has started this by developing a tool that pulls out the current information and using that tool I have tidied up MicroClimate relatively easily.  

As a next step, Russel and I have gone through SoilWater.  The spreadsheet attached contains the current units/descriptions and a draft of the proposed units/descriptions.  Some of these have queries on them.  Can you look through this list and comment, improve or modify as sensible?  Please alert others that might contribute to this discussion.

[SoilWater.xlsx](https://github.com/APSIMInitiative/ApsimX/files/483872/SoilWater.xlsx)

@hol353 @fai04d @hut104 @rcichota @HamishBrownPFR @josharp22 @zur003 @her123

**Comment by rcichota** [comment]
That is a great start, one concern I have is whether we should be making explicit the 'stuff' in the units. That is, should we use units of 'mm water' or simply 'mm'. It does make clear what the units refer to, but makes some units to be too long, but most importantly it adds the need for 'spaces' in the units and that can create lots of trouble when writing scripts to interpret the outputs or in the way some programs parse the text into tables... I favor keeping the units as simple as possible and using the description to make clear what the 'stuff' is.
On a more pedantic note, it would be good to follow a general style on the description. I'd suggest not start a description with an article (use 'Amount of water' instead of 'The amount of water'). Also avoid acronyms when possible and especially avoid references to variables or parameters (use 'Reduction in curve number' instead of 'Reduction in CN'). Any other??  how about writing 'day' instead of 'd'.
I have made a few comments/suggestions on the table.

**Comment by rcichota** [comment]
File:
[Uploading SoilWater.xlsx…]()

**Comment by HamishBrownPFR** [comment]
Good stuff.

My initial thoughts below.
I don't like using dd-mmm as a unit.  It is really day of year and dd-mmm is a format in which it can be represented.
0-1 and 1-100 are ranges for dimensionless variables rather than units.  Should variables have a specified range also?
For bare soil albedo a unit of MJ/MJ is proposed where as a unit of 0-1 is proposed for Maximum bare ground soil albedo.  Neither are correct because the MJ cancel so albedo is dimensionless and 0-1 is a range not a unit.  However, both are also informative to tell use what range the value should be in and what the value is made up of.  I suggest we limit units to SI units, provide a field describing range where that is useful (the 1-100 and 0-1 variables) and include any useful descriptive bits and flesh out the description where it may not be clear what the units represent.  For example for Albedo the unit would be dimensionless, the range is 0-1 and the description would be something like "Proportion of incoming radiation reflected from bare soil".  Eg. 2 Potential evaporation would have a unit of mm a range of 0 - infinity and a description "Potential evapotranspiration of water from the soil-plant system"

In proposing units of kg/ha for SoilWat masses and proposing a unification of units this is also proposing units of kg/ha for Plant masses also.  Agree it would be good to unify these and I think the decision of which to use will be arbitary so we should work out which will be easier to change and go with the other.

**Comment by sno036** [comment]
[SoilWater-v2.xlsx](https://github.com/APSIMInitiative/ApsimX/files/510007/SoilWater-v2.xlsx)
Next iteration on the soil water descriptors and units.  Comments (IN THE SPREADSHEET please).  Will look to merge this into the code later this week.

Dean - neither Rogerio nor Russel seem to be permitted to upload files to GitHub - is there a setting that needs changing?

Thanks, Val

**Comment by hol353** [comment]
There are no permissions in GitHub around uploading files to GitHub issues. You're able to do it and you are not part of any special team of developers or admins. Something else must be the problem.

**Comment by mcauliffer** [comment]
Odd. It's working for me today but still not working for Rogerio.

**Comment by mcauliffer** [comment]
Proposed units and descriptions for SoilOrganicMatter
[SoilOrganicMatter.xlsx](https://github.com/APSIMInitiative/ApsimX/files/640669/SoilOrganicMatter.xlsx)

**Comment by mcauliffer** [comment]
[SoilOrganicMatter.xlsx](https://github.com/APSIMInitiative/ApsimX/files/849576/SoilOrganicMatter.xlsx)

**Comment by mcauliffer** [comment]
[SoilOrganicMatter.xlsx](https://github.com/APSIMInitiative/ApsimX/files/849579/SoilOrganicMatter.xlsx)
testing uploads (copy of same file)
