### ISSUE TITLE
Fix case sensitivity for report variables.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#13]
Output variables are case sensitive but people don't get an error to 
say they have don't something wrong - they just get a blank column at 
run time

**Comment by zur003** [comment]
So what is the best solution? I don't know that we want to issue a warning - I think it's possible that the variable might be "correct", but simply not present at that point in time (e.g., because a crop hasn't yet been sown), or am I wrong here? 
The search for variables eventually goes through a call to Type.GetProperty in Locater.GetInternal, and that call could easily be made case-insenstive, but do we want case-insensitivity all the time, or just in this context? Are there other cases where we require case sensitivity (e.g., to resolve ambiguities)?

**Comment by zur003** [comment]
Hhhmmm. I tried submitting a fix, but got an error with Tests\SugarCane\Example\Sugarcane.apsimx. It turns out that SugarCane has both "height" and "Height" as (equivalent) public double properties, and the run then fails because the case-insensitive match is ambiguous. I would argue that SugarCane shouldn't have two property names differing only in case, but is this problem likely to show up in other contexts? I suppose one solution would be to do a case-sensitive search first, and try the case-insensitive search only if it fails..
