### ISSUE TITLE
If a simulation crashes (or is closed) with an error in a Manager script ...

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1654]
If a simulation crashes (or is closed) with an error in a Manager script then it is not at all easy to reopen the file.  There is an error message but it points to the line in the script without naming the script and the only fix that I found was to edit the file in a text editor.

Is there a more graceful way to open a file that already contains an error?

![capture](https://cloud.githubusercontent.com/assets/12176269/25790793/ccb7f4fa-340f-11e7-833f-1ec4fdf477d0.JPG)

**Comment by zur003** [comment]
This problem can also arise easily if model internals are changed. When the GUI tries to load the simulation, it attempts to compile any manager scripts. If these scripts made use of structures that are no longer valid, the simulations won't load, and there's no fix other than to edit the ApsimX file in a text editor. (This is currently a problem with many of the "Validation" tests - they made use of Soil.SoilWater.Thickness, which now should be Soil.Thickness.)

When loading simulations, we should see the errors, but not abort the overall load procedure.

**Comment by rcichota** [comment]
This problem is still there. Once there is an error in the script (whether created by user or change in model internals) it is impossible to open the script and fixed, one has to go to a text editor. Now using JSON, this is harder (or it seem to me) as the text format is not easy to read (e.g. it has no line breaks).
