### ISSUE TITLE
Making PMF easier for the user

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1689]
For the user (i.e. not a developer who understands the structure of the model) getting report variables out of PMF is difficult and confusing.  Take water demand as [Wheat].Leaf.PotentialEP (at least I hope that is the whole-plant water demand) and nitrogen demand as [Wheat].Arbitrator.N.TotalPlantDemand.  Not only is the information that the user most often wants buried but there is no apparent pattern that they can learn.  Would it be possible to make the most 'popular' outputs more readily accessible - e.g. [Wheat].WaterDemand, [Wheat].NitrogenDemand?  Ideally these would be consistent across all the plant model code bases.

There are similar issues with accessing outputs from Soil I think.

**Comment by wolfgang-boku** [comment]
Very good point. Searching for the output of interest is often time consuming and a lot of trial and error. As a first step, an online list with the most common outputs and the appropriate report variables would be really helpful.

**Comment by hol430** [comment]
@sno036 What action is required here? I think when this issue was created there was no intellisense or 'view model structure' feature. Unsure if the autodocs existed at that time either.

**Comment by sno036** [comment]
I think it is mostly that the outputs needed most often are opaque and lengthy and non-obvious to the users. One suggestion would be for the outputs most commonly used by people just wanting to have a crop in the system (i.e. not wanting or needing to get into the detail of how the model works) replicated with a short and obvious name just at the crop level. e.g. as well as "Wheat].Arbitrator.N.TotalPlantDemand" also "[Wheat].DemandN" etc.

**Comment by HamishBrownPFR** [comment]
I think the intellisence helps with this.  Agree that some of the variable names are hard to find and sometimes very long but this comes directly from the models structure an makes it clear exactly what is being reported.  I don't think making a list of simplified names for select variables within the model is the solution because we then have duplicate variables which can cause confusion and cause problems with code maintenance (converters etc).   Simplified names might make variables less opaque from a discovery perspective but it makes them more opaque from the perspective of knowing exactly what is being output.

I think the solution here is to check the examples for each crop an make sure they are outputting the 'Most Often Needed' variables and giving them concise common language alias.  This way users can use the example file to find common outputs and it still remains clear exactly what is being output.

**Comment by sno036** [comment]
That sounds like a useful solution to me. Suggest hold off a little until we have made more progress with the aggregation in Report so that the examples can include that capability as well.

**Comment by rcichota** [comment]
One thing that would be interesting to have, and in line with Val's request, is to have plant 'totals'. Currently there are very few of those, like Total.Wt, though these are defined by the developer, not PMF). It would be nice to have a selection of such 'summaries' for the most commonly needed outputs (N demand, WaterUptake, Photosynthesis, etc.). Currently some are only reported at the organ, or with some luck at arbitrator, level. The user has to sum them up on the report (and know about they coming from different organs - e.g. photosynthesis)...

**Comment by sno036** [comment]
Great suggestion @rcichota. Because all the PMF crops have different parts I can foresee all sorts of errors trying to calculate N and C balances across a range of crops in a rotation for example. If these are defined by the developer rather than PMF itself then may a few mandatory ones?

**Comment by rcichota** [comment]
The issue is then what would be a good minimum list of variables we want this way (and who's going to do)?
I agree with @sno036 these would be great to have when analysing mass balance. Thus variables should capture the main input/outputs for water, N, biomass (photosynthesis, removals,etc)
