### ISSUE TITLE
GTK UI: Can we make the PropertyPresenter make the grid 2nd column left aligned and wide.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1737]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/1943827/27204076-6453dca0-526c-11e7-9e80-4224a8b608cf.png)

Would prefer it to look like old APSIM:
![image](https://user-images.githubusercontent.com/1943827/27204092-762c4372-526c-11e7-84b5-aa70390754ef.png)

i.e. the 'Value' column should be left aligned and much wider. This will make it easier to type in numbers and text. 

No need to worry about doing this for the Windows.Forms version, which suffers the same problem. I'd like to remove the Windows.Forms GUI soon.

**Comment by her123** [comment]
Isn't it normal to right align numbers?

**Comment by hol353** [comment]
Numbers yes but those grids are used a lot for long text strings as well. e.g. for an expression function.

**Comment by zur003** [comment]
I actually went to a bit a of trouble to avoid having that right column taking up the full width, but that was largely because I was right-aligning its contents (as @her123 commented, that looks better when you're working with numbers, and I was thinking about the Report presenter at the time). It should be possible to set a flag to get it to work one way for the ReportPresenter, and the other for the PropertyPresenter.
