### ISSUE TITLE
GTK UI: Weird screen display problem

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1918]
See pic below. Tree control doesn't display correctly on high DPI machines e.g. surface pros.

![image](https://user-images.githubusercontent.com/1943827/29643974-0543e9be-88b6-11e7-9b60-6234e9c3220e.png)

**Comment by hol353** [comment]
@zur003 Any progress on this?

**Comment by zur003** [comment]
@hol353 No.

**Comment by zur003** [comment]
@hol353 I'd like to try to address this, but am not entirely sure where to begin. Which version of Windows are you running on the Surface Pros? And can you provide me with as much information about your current display settings as you can find? Is there any indication whether a custom scaling is being used?

It's also interesting that your screen shot shows the tree using triangles to indicate expanded/collapsed nodes, rather than + and - boxes which I normally see.

You're seeing a problem with both "installed" and "built" versions of the GUI, correct? Just wondering, as they may pick up different versions of the GTK dlls.

**Comment by hol353** [comment]
Hmm interesting. When I install the latest official release of next gen all display artifacts are gone and I get plus signs in the GUI!!!. In fact it looks good.

For developers using Visual Studio, can we just have a set of .dlls and config files that we put somewhere (in Bin folder) instead of installing a separate GTK installation? I'm looking for a clean way for new developers to get themselves set up quickly. The ideal would be a .zip file of files that we unzip somewhere and everything else just works.
