### ISSUE TITLE
Return value of DMConversionEfficiency equal to 1

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#1991]
We have changed to DMConversionEfficiency into other values, but the DMConversionEfficiency always equal to 1 when I debug. 

Seems this line code force DMConversionEfficiency  to 1:

virtual public double DMConversionEfficiency { get { return 1; } set { } }

https://github.com/APSIMInitiative/ApsimX/blob/1b58df65adf9f680a50cce5f259afcf1fe4db096/Models/Plant/Organs/BaseOrgan.cs#L56

**Comment by HamishBrownPFR** [comment]
Is this a problem for all organs or just GenericOrgan.  Looks like Generic organ is not programmed properly.  Have a look at the pattern in Leaf.cs or GenericOrgan.cs.  They both have a override for DMConversionEfficiency and a paramater called DMConversionEfficiencyFunction which assigns its value to DMConversionEfficiency

        public IFunction DMConversionEfficiencyFunction = null;

        private void OnPlantSowing(object sender, SowPlant2Type data)
        {
            if (data.Plant == Plant)
                Clear();
            if (DMConversionEfficiencyFunction != null)
                DMConversionEfficiency = DMConversionEfficiencyFunction.Value();
            else
                DMConversionEfficiency = 1.0;

Generic organ only has a parameter called DMConversionEfficiency which will not be overwriting the value in base organ

**Comment by byzheng** [comment]
From my debug, it is existing in the reproductive organ which is overwrite.
Don't understand why.

**Comment by HamishBrownPFR** [comment]
The problem is that GenericOrgan is not assigning DMConversionEfficiency a value so it keeps the value of 1 that is declared in the base organ.  It has a function called DMConversionEfficiency 
![Uploading image.png…]()
but this will not overwrite the DMConversionEfficiency property that is set in BaseOrgan.  To fix the problem you need to:
1 rename the DMConversionEfficiency function in Generic organ (and all xml files, use the change tool) to DMConversionEfficiencyFunction
2 add into the onsow method of Generic organ lines something like this
            if (DMConversionEfficiencyFunction != null)
                DMConversionEfficiency = DMConversionEfficiencyFunction.Value();
            else
                DMConversionEfficiency = 1.0;

This assigns the DMconversion efficiency value from the models paramaters to the property that the organ class is using in the code.

**Comment by byzheng** [comment]
Leaf: correct
GenericOrgan: correct
ReproductiveOrgan: wrong
Root: wrong

Btw: the DMConversionEfficiency and DMConversionEfficiencyFunction used in the different organs

**Comment by HamishBrownPFR** [comment]
The same fix will apply to root also.  Change DMConversionEfficiency in the XML to DMConversionEfficiencyFunction and put some code in that assigns this value to the DMConversionEfficiency property in the organ classes
