### ISSUE TITLE
Nitrogen uptake

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2125]
There are three variables to export nitrogen uptake in root. 

```
[Wheat].Root.NUptake
[Wheat].Root.NSupplyUptake
[Wheat].Root.NSupply.Uptake
```
`[Wheat].Root.NSupplyUptake` is defined in the `BaseOrgan` and equal to `NSupply.Uptake`. I think this `NSupplyUptake` can be removed to reduce confusing.  `[Wheat].Root.NSupply.Uptake` doesn't be updated in any places. So `[Wheat].Root.NSupplyUptake` and `[Wheat].Root.NSupply.Uptake`  always equal to zero.

`[Wheat].Root.NUptake` is calculated from `ZoneState`, which should be an positive value as the `WaterUptake` (I can submit a pull request to fix it).

As `NUptake` just is an output variable, I would suggest to use Root.NSupply.Uptake for consistence.

Moreover, the curve of `NUptake` is really strange to me. 

![image](https://user-images.githubusercontent.com/1657381/32210860-97fa1b18-be5b-11e7-9886-da5723e7d0fe.png)

**Comment by HamishBrownPFR** [comment]
Hi @byzheng.  It would be good if you were able to tidy this up but it is confusing because it is complicated so go carefully.  I would check in with @hut104 before changing the N uptake variables to be sure they are not needed for any of the multi zone stuff.

Why do you consider the N uptake strange?  Looks like N uptake is increasing as the crop grows and then it appears to run into supply limitation and tails off??

The idea of having an uptake and an uptake supply variable was so graphs of actual N Uptake could be compared with N Uptake Supply and N Uptake Demand for checking things are working properly.  It gets confusing because none of these are fully calculated in the root.  N Uptake Demand is calculated by the organ arbitrator but taking total N demand (summed from all organs) and subtracting out N reallocation supply.  This is then constrained to what the root can supply assuming no competition from other plants.  However, the actual N uptake by the root may be less than this in multicrop simulations if others crops are competing for N uptake.  

Root.NSupply.Uptake seems like the nicest variable to use but there is a problem with it.  The root use to calculate N uptake and this was sent to the organ arbitrator in Root.Nsupply.Uptake.  However, when the soil arbitrator was implemented, NUptake was calcualted via a different route so Root.Nsupply.Uptake became redundant.  However, as this is a generic property that feeds data into the organ arbitrator we can't assign it a value as it will cause the N uptake to be counted twice by the arbitrator, I think it has to be zero.  In theory all organs can have an uptake but because root doesn't use this and no other organs are doing uptake, removing Uptake as a form of N supply might help to tidy things up.  I.e. I suspect we could remove NUptake from the BiomassSupplyTypeClass in the IArbitration interface as I don't think it is ever used now.
![image](https://user-images.githubusercontent.com/7295858/32246041-99257726-bee2-11e7-86d9-0a123d45afbd.png)

The Root.NUptake reporting variable included so N uptake can be reported by root.  

I also suspect NSupplyUptake can be removed from BaseOrgan as it is also redundant now.  At one stage its intent was to report how much N the root would supply if demand exceeded supply and there was not uptake competition for other plants.  Something to this effect could be included in root more tidily..

**Comment by byzheng** [comment]
@HamishBrownPFR Thanks for your explanation. 

I looked the root nitrogen update as the SLN response curve and the photosynthesis model in the DCaPS (developed by Alex) don't make sense to me.  

I expect SLN is about 2 g / m2 as the APSIM 7.9 simulated, not gradually decrease from 6 to 0.5 g / m2 APSIM next generation. See the figures below for example of SLN in APSIM 7.9 and next generation. 

![image](https://user-images.githubusercontent.com/1657381/32246845-101c8a84-becc-11e7-9bd5-f122673b2e56.png)

![apsim wheat 7 8 sln](https://user-images.githubusercontent.com/1657381/32246925-5603b8d8-becc-11e7-8bea-888e296b76bd.JPG)

Have continued to read source codes last night. The deep valley in the figure of my first comment is caused by all nitrogen are uptaked around Stage 4. Seems wheat runs out of nitrogen too quickly. But I still cannot figure out why there are high SLN in early stage. 

You are correct that it is really hard and complicated to clean up codes. 

Currently, the `Uptake` in `BiomassSupplyType` Class don't used in any places with any positive values. But I think it will be useful in some cases for `Leaf` or `AboveGround`, for example, 1) fertilisation through spraying which directly absorbs by Leaf (leaf uptake), 2)  Nitrogen from atmospheric deposition to simulate air pollution. From a generic model point view, `BiomassSupplyType.Update` can be kept.

`NSupplyUptake` is only an reportable variable and can be easily removed.

**Comment by hut104** [comment]
Hi,

Much of this code desperately needs a clean up.  Dean and I try this from time to time.  It is a simple result of our processes of prototyping new approaches etc and so eventually things often require a clean up once the design settles down.


I've found Dean to be a great source of design ideas for refactoring.  We have a large number of lessons from our mistakes and Dean should be able to help you to avoid repeating our previous mistakes.  There are also some basic design patterns that we try to follow.  So I suggest talking to Dean first, he will be moderating your pull request anyway so best to get the info sooner rather than later.


As Hamish has said, some of the design is slightly different to APSIM classic because multispecies and/or multipoint simulations are becoming more commonplace and so the system is being designed to handle this more implicitly.


Great to see your enthusiasm,

Neil.?

________________________________

**Comment by par456** [comment]
These variables have been changed since this issue was written. Closing this. Open a new issue if this is still relevant.
