### ISSUE TITLE
Intlisence in Manager module crashes with date object

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#214]
I am typing Clock.Today in the example below as soon as I type the dot the manager tries to drop down an intelisence list and crashes.  This only seems to happen with Clock.Today

![image](https://cloud.githubusercontent.com/assets/7295858/8790970/75587ba2-2fa8-11e5-8d88-3e856e3f4226.png)

**Comment by HamishBrownPFR** [comment]
Correction, this seems to be happening with other things.  I just got the same error with MCSP.Phenology.

**Comment by zur003** [comment]
Interesting. I'm not getting any intellisense stuff happening at all.

**Comment by HamishBrownPFR** [comment]
It all seems a bit flaky, I often get funny things going on with intellisence

**Comment by zur003** [comment]
Dean, at least part of the fix for this involves a change in ApsimShared rather than ApsimX. I've submitted a change and issued a pull request in ApsimShared, but I think this isn't monitored by Jenkins, and you will have to intervene manually.

**Comment by zur003** [comment]
Hamish, could you pull the change I made in APSIM.Shared and see whether the problem has been resolved? If so, we can probably close this issue. The automated system on Jenkins doesn't work so well when a fix is needed in APSIM.Shared rather than ApsimX, but I don't see any easy way to make the build system work better in that regard.

**Comment by HamishBrownPFR** [comment]
Yes that appears to have fixed it, thanks Erick
