### ISSUE TITLE
Writing to file while running simulations with multiple zones

### ISSUE THREAD

**Issue by josharp22** [APSIMInitiative/ApsimX#2188]
@hol353 
Hi Dean
Would it please be possible to adapt your previous efforts that get APSIMX to write to file while running multiple simulations, to write to file during simulations that have multiple zones?
An example simulation is here: https://github.com/PlantandFoodResearch/MVI-FarmModelling/tree/master/Study_Farms/1RitchieOtane
I'm currently stuck on a project as it seems to be running out of memory and isn't writing to file. Is this a big task?
Cheers
Jo

**Comment by josharp22** [comment]
@hol353 To clarify, I am unable to run simulations with a large number of zones. I think this may be because it is running out of memory as it is not writing to file during the simulation. Here is an example: https://github.com/PlantandFoodResearch/MVI-FarmModelling/tree/master/Study_Farms/1RitchieOtane

**Comment by hol353** [comment]
Hi Jo, that's a lot of zones (> 1000). It is highly unlikely that ApsimX will ever be able to run anywhere near this number. We can't do the same trick as we did with lots of simulations because the zones can be separated and run in different threads at different times like simulations can. Do they really need to be zones rather than simulations?

**Comment by josharp22** [comment]
Thanks Dean. Unfortunately yes they do, as there is a limited resource (an irrigator) which need to respond across all the zones and can't be in more than one place at one time.
