### ISSUE TITLE
Maps not showing in Autogenerated documentation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2261]
Certainly an issue for the new nutrient model. May be an issue for other models.

**Comment by HamishBrownPFR** [comment]
Yep, no map at all in the maize doco and the map in the wheat doco looks like this
![image](https://user-images.githubusercontent.com/7295858/36168238-4469c976-115d-11e8-9f7b-38d22b83c9e6.png)

**Comment by hut104** [comment]
Yeah, I thought that Dean had fixed this.  The stuff in the soil nutrient model I was working on also had a few images that looked like this.

Neil.

**Comment by hut104** [comment]
Is it possible to get this fixed some time in the next week or two.  I'd like to provide doco for review by the reference panel. @zur003

**Comment by zur003** [comment]
I haven't been able to replicate the problem. Is this happening consistently? 

The whole procedure used to generate maps is admittedly a bit of a hack. On Windows, we create a temporary popup window, with co-ordinates that put it off-screen, so the user doesn't see it. The popup window holds an embedded web browser, which navigates to Google Maps to generate the map, then the (invisible) window's contents are exported to a png file. A lot of things can go wrong in this process. For example, I haven't found a good way to know whether the JavaScript stuff associated with the map has fully completed execution, so I rather arbitrarily wait for 500 milliseconds to let things complete. Perhaps that's not sufficient time when there are many data points. Still, I would have expected an "empty" map (or perhaps one with no data points) in that case, rather than the imagelists you seem to be seeing.

@hut104 Can you tell me exactly which simulation you're using, and exactly what you are doing to generate the documentation? Also, are you using a high resolution monitor?

**Comment by hut104** [comment]
The problem is also occurring in the build system.  The doco on our website has the same problem within it.
http://www.apsim.info/ApsimxFiles/Wheat2299.pdf

**Comment by zur003** [comment]
Ahh. I suspect the problem is that trying to draw the map "off-screen" doesn't work correctly on the virtual machine used for the builds. Currently testing this idea.

**Comment by zur003** [comment]
@hut104 - Could you re-open this? It appears that it's not fixed after all. 

Unfortunately, I don't know how to fix it. The problem seems to be that scoop tries to generate the documentations while running "headless". It's a bit like we're trying to do a screen capture when there is no screen.

**Comment by hol353** [comment]
Scoop isn't actually running headless at all. It is a real computer (not virtual) and has a screen and a normal user login.
