### ISSUE TITLE
What is the name of this beast?

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#232]
This is not a bug or feature request. 

I'm just wondering what we should formally call the software product we are creating here. We've had ApsimX, Apsim 2014 and Apsim 2015. The draft MODSIM paper calls it APSIM Next Gen. (although the draft paper used, if I recall correctly, "APSIM Next Generation", "APSIM Next Gen", "APSIM Next Gen.", and "APSIM next gen." at different points in the text). So what does everyone think? Personally, I'd rather not have a "." as part of the name, so I'd prefer "APSIM Next Gen" over "APSIM Next Gen.", but I'd be content with "APSIM NG". I also get lazy and tend to use "Apsim" rather than "APSIM" (and there's probably an argument to be made that it should be "APSim").

It would be good to make the naming is bit more consistent. Is this ultimately a decision to be made by the Reference Panel?

**Comment by hol353** [comment]
Yes good question and I'd be interested in other views. It is a decision for the Reference Panel / Steering Committee. The Steering Committee don't want to lose the APSIM brand name - APSIMx is not acceptable. I'm inclined to go with APSIM Next Generation but it is a long name. What do others think?

**Comment by sno036** [comment]
We tend to refer to classic APSIM generically as "APSIM" but for formally as "APSIM 7.7" or "APSIM r1474".  I suggest that we continue this and still just use "APSIM" generically and "APSIM 2015.07" for specifically.  Eventually classic will expire and then it will matter less.

**Comment by hol353** [comment]
I agree Val but APSIM next gen is now a continuous release so there is no version 2015.07 anymore. I think we use APSIM (all uppercase) and 'Next Generation' as the version.

**Comment by fai04d** [comment]
I tend to use 'classic APSIM' (can we call it 'clapsim'?) or just 'APSIM' and 'APSIM next gen' when referring to them together when speaking to users. I don't use a year/month identifier since the release will change so often.

As APSIM NG gets closer to feature parity I expect they'll become 'classic APSIM' and simply 'APSIM'. This will make it much easier on the website as well. I don't think we really want an apsim.info and apsimNG.info or anything like that, especially looking 10 years down the track when classic APSIM has faded into the background. It's something we'll need to keep in mind though as the it's likely that changing the names of both products will break a lot of links in publications. This shouldn't be an issue for the next two to three years though.

**Comment by hol353** [comment]
Closing this. The Reference Panel suggest we use 'APSIM Next Generation'. Can shorten it to 'APSIM Next Gen.'
