### ISSUE TITLE
When I generate an auto doc I get a script error relating to maps

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#2333]
Screenshot:
![image](https://user-images.githubusercontent.com/1943827/36464249-817cc7e2-171a-11e8-866e-228f1d4b0265.png)

**Comment by zur003** [comment]
@hol353 - See my comment from 12 February on the #_development channel of Slack. This happens because Microsoft has a default behaviour of emulating IE 7 when the browser is embedded.

Anyway, you need to all some registry keys:

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION]
"ApsimNG.exe"=dword:00002af8
"ApsimNG.vshost.exe"=dword:00002af8
