### ISSUE TITLE
if report does not has a specified report frequency or event, it should throw an error message

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#2375]
if a report does not has a specified report frequency or event, it should throw an error message. for the moment it just says null reference object. 
interesting when you add report frequency once and run it successfully. when the delete the report frequency again, apsim seems remember the frequency and did not produce an error.

**Comment by sno036** [comment]
When the reporting frequency is controlled by something else (e.g. a Manager script) then the frequency in the Report should be blank.  I have this in several simulations and do not get a null reference.  Perhaps this issue has been resolved elsewhere?

@hol430

**Comment by hol430** [comment]
Yep I don't get this error either, so I guess it has since been "fixed". 

It's still a bit of a trap for users, so I wonder if we should display a warning...maybe when navigating away from the report view? I guess that would get annoying for people like you who are deliberately leaving it blank. Instead, perhaps we should put [Clock].DoReport in this box by default when the user adds a report via the "New Model" button. Does anyone have a preference here?
