### ISSUE TITLE
the number of APSIM file folder keep increasing 

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#2460]
Maybe this is a difficult question. Is it possible to let each update replace the previous APSIM folder or version? we may have several official release version every day, so the user probably needs to update the version each day as well. As a result, the APSIM folder keeps increasing as well. Probably it is good that after each update, the installer deletes or ask to delete the previous version. 

![image](https://user-images.githubusercontent.com/13222562/37259082-cb470b82-25e6-11e8-8308-fe9864d70601.png)

**Comment by hol430** [comment]
Instead of installing a new version each time an update is released, just use the upgrade functionality built into APSIM:

![test](https://user-images.githubusercontent.com/36427516/37631018-6335bf90-2c33-11e8-83b9-c373a6d836b2.PNG)

This will update your version of APSIM without creating a new installation. You can then uninstall any legacy versions you may already have installed.

If this doesn't work/help, just reopen this issue.
