### ISSUE TITLE
Append icons with something to show the IncludeInDocumentation status of each node

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2485]
Currently need to right click each node to see if the IncludeInDocumentation tag is toggled on or off.  Can we put a small indicator on each icon, like a small tick in the top corner, to show if this is toggled on.

**Comment by zur003** [comment]
We could do that, but I would proceed with caution. I suspect most "normal" users won't be generating their own documentation (they will be much more focused on model outputs rather than model structure). For them, seeing little indicators scattered around may be confusing and distracting. It would probably be better to have a menu option to turn highlighting of documented nodes on and off (with it being off by default). If turned on, then the Include state of nodes could be indicated by icon changes, font changes, or whatever.

**Comment by HamishBrownPFR** [comment]
Thanks Eric.   Yes having any demarcation of IncludeInDocumentation off by default would be a good idea with a menu option to turn it on.  It would only be needed when preparing validation sets in the UI but would be extremely use full then.

**Comment by hol430** [comment]
How should this option be accessible? We could have some sort of user preferences view/dialog - it'd be a bit excessive for this small change, but in the long run it might be useful.

Or I could create a submenu on the current 'include in documentation' menu item:
![test](https://user-images.githubusercontent.com/36427516/37752588-99e43816-2de4-11e8-967e-7a33dc429caf.PNG)

Or I could do something else entirely. What are your preferences?

**Comment by hol353** [comment]
Let's go with the context sub menu. Much simpler. If a sub menu is too difficult then have another menu item immediately under create documentation.
