### ISSUE TITLE
Method to visualize released models

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2486]
The UI is really good for visualizing the structure and settings of models when they are in the replacements node.  However, when the model is released it is necessary to copy it back to a replacements node (which is a bad thing to do) to see the set up easily.  Otherwise we have to look at the xml which is slow going.

Possible solutions:
- Have model nodes display their full xml structure.  There was a bug recently that meant each crop model in the tree was showing all of the crop model structure below it.  This was quite handy but very dangerous as changes could be made to the model here.  If this could be done but with the content below the model read only and displayed by the GUI but not saved in the .apsimx file this would work.
- Have a button on the home page (something like "View released Models") which brings opens a simulation file that has the full structure of each released model.  Sort of like the Crops folder in the standard tool box but with each model expandable to show full model set up.
- Other ideas???

**Comment by zur003** [comment]
I think of it as there being three levels of interaction between the user and the model structure. The first is "I just want to use the model, don't bother me with the details"; the second is "I want to see the model structure, but I don't want to change it"; the third is "I want to make changes to the model". I think the first should remain the default. You could then have an item in the popup menu that toggled visibility of the model structure, with the embedded nodes displayed as "read only", Allowing model changes is "dangerous", so a node editing mode should be a bit harder to get to, or at least provide the user with a large warning sign of some sort. Maybe something obscure, like holding down the control or alt key when selecting a "Show model structure" menu option would open things in editable rather than read-only mode?

**Comment by HamishBrownPFR** [comment]
Thanks for your comments Eric.  The three levels are a good way of thinking of it.  The system we have currently works well for level 1 and level 3.  It is the level 2 stuff that is missing.  Clicking on a model to get an option 'Show model structure" as read only would work well in this respect.
