### ISSUE TITLE
Graph units are not updated correctly

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#2538]
> (2018.4.9.2516 - OSX) graph Y axis label (units) is not updated when Y variable is changed.

**Comment by peter-devoil** [comment]
This was observed with the "Visual Studio release channel" version of mono, not the "stable" channel.

**Comment by hol430** [comment]
@peter-devoil Do you refer to the fact that sometimes the units are null/empty, like in this case?

![test](https://user-images.githubusercontent.com/36427516/39278617-85e98e92-4937-11e8-8aa3-1059e1cc0725.PNG)

**Comment by zur003** [comment]
It seems to work OK for me. Is there a chance that the Y-axis title had been explicitly set? It must be blank to change automatically. For example, the graph in the Wheat example has the title set to "Yield (kg/ha)", presumably because Yield doesn't provide units on its own (it probably should). Anyway, it means that changing the Y variable does not change the axis label.

**Comment by hol430** [comment]
@peter-devoil any chance you remember how to reproduce this one?

**Comment by peter-devoil** [comment]
Charlotte is long gone - so there's no active mac users here for me to try it out again. Suggest you close it.
