### ISSUE TITLE
IntelliSense of nested classes

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#2556]
when adding an x property to a LinearInterpolationFunction I get Intellisense for the first part 

[Lifecycle].CurrentLifestage

but if i add a second . nothing come up

 what i would expect to get is 

[Lifecycle].CurrentLifestage.CurrentCohort.PhenoAge

please contact me if you need a better explanation

**Comment by jwhish** [comment]
I just found an example where Intellisense worked well 

I was adding an xProperty to LinearAfterThreshold function and all worked well finding the functions I had just created 
eg
[LifeCycle].Juvenile.Development.DailyTempCycle

**Comment by jwhish** [comment]
Just found one reason for this working inconsistently. there appears to be a space behind the variable CurrentLifestage so the intelligence wont work unless the space is included.
I am not sure if this is the case for the others. 

[lifeCycle].CurrentLifestage .  works 
[lifeCycle].CurrentLifestage.   does not

**Comment by sno036** [comment]
I'm having trouble with Intellisense as well and is making things very difficult.  See part of a conversation with @hol430 below.  Getting the autoformatting working would be great!

hol430 [11:56 AM]
The problem seems to be that intellisense only works for fields of the class; e.g. if you put `[Link] PastureSpecies Plant;` at the top, then intellisense will work for this Plant field. So, inside your loop, if you write something like this:
`foreach (PastureSpecies plant in Apsim.Children(paddock, typeof(PastureSpecies)))
                    {
                        Plant = plant;`
then intellisense should work on the Plant field/variable
ugh the formatting didn't work there

**Comment by hol430** [comment]
In a manager script, primitive types (e.g. int, string, etc.) do not currently generate intellisense. Would it be useful to have member suggestions for these types?
