### ISSUE TITLE
Allow a "//" to comment out lines in Report and Operations

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2590]
Please - would be very nice to have.

**Comment by zur003** [comment]
This should already be happening in Operations. Is it not working?

**Comment by sno036** [comment]
For me it is converting //2011-04-11 to 0001-01-01 which does effectively disable it but the original date information is lost

**Comment by hol430** [comment]
I have not been able to reproduce this. Can you upload an .apsimx file which shows this behaviour?

**Comment by hol430** [comment]
@sno036 It appears that in order to comment out an operation, your double slash needs to come after the date, but before the action. e.g. 
`1983-12-30  //[Fertiliser].Apply(60, Fertiliser.Types.UreaN, 10);`

Is this something that we want to change? It's not exactly obvious to the user, and I wouldn't have figured it out without looking at the source code.

**Comment by hol353** [comment]
Not obvious. Should just be able to comment whole line out.

**Comment by hol430** [comment]
Should a double slash after the date but before the action still be legal syntax for an operation?

**Comment by hol353** [comment]
Yes. Like in c# a double slash should just comment out the rest of the line so that you can put it anywhere.
