### ISSUE TITLE
Australian users should have better access to SILO weather

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2716]
Now that SILO has released its new API, it would be good if Australian users could download up-to-date weather data by providing their API key and specifying a station number or latitude/longitude within Apsim.

It would be even better if the date range of the simulation was tested against the date range of the available weather, and a fresh copy of weather data downloaded iff necessary.

**Comment by zur003** [comment]
With the World Modeller's project in mind, a weather downloading capability should extend across the globe, rather than just Australia. There should also be potential for including seasonal forecast data in these downloads.

**Comment by peter-devoil** [comment]
The new silo api has been withdrawn. I'll ask if there's an update, but for now, it's planned to revert to the old system next week.

**Comment by peter-devoil** [comment]
Some notes from the SILO maintainers:
--------
The new SILO system:
-          with web pages https://silo.longpaddock.qld.gov.au/
-          and API calls with address: https://siloapi.longpaddock.qld.gov.au

is being terminated this weekend. The new system cost too much to run so we decided to upgrade the original system because it is much cheaper to operate.

 The original system:

-  with web pages https://legacy.longpaddock.qld.gov.au/silo

-  and API calls with addresses: 
o   https://www.longpaddock.qld.gov.au/cgi-bin/silo/PatchedPointDataset.php or https://legacy.longpaddock.qld.gov.au/cgi-bin/silo/PatchedPointDataset.php

and

o   https://www.longpaddock.qld.gov.au/cgi-bin/silo/DataDrillDataset.php or https://legacy.longpaddock.qld.gov.au/cgi-bin/silo/DataDrillDataset.php

has been modified with a new backend and ported to another (much younger!) machine. The new backend is now in production use. We are upgrading the original website so it is similar to the new web site. We aim to release the upgraded website at the end of this week (to coincide with the shutdown of the new system), to minimise impact on users of the new system. I expect there will be some minor changes to the existing API format, but they should be limited to the following:

-          the API addresses shown above should remain the same, although the “legacy” version will be removed
-          the requirement for a username and password will be dropped (clients will no longer require an account)
-          you will need to provide your email address in the API string.
These changes will be documented in the upgraded website.

The original mirroring system developed by Alan Beswick will still be available, enabling you to mirror patched datasets from the (upgraded) original system. The upgraded website will include information on how the mirroring system works. I have included a draft copy of that information below, and attached a copy of the example software that appears in the link below.

**Comment by sarahcleary** [comment]
@peter-devoil - do you want this added to the RP Agenda?

**Comment by peter-devoil** [comment]
@sarahcleary  - It's mostly an operational matter - the service is in no danger, so I don't think it necessary. At some point, I need to decommission the machine that mirrors silo for apsim users, what replaces it will only be apparent once the above has been operational for a while.

**Comment by zur003** [comment]
I think this is all working nicely now, so I'm going to close this Issue.
