### ISSUE TITLE
Small fonts used graphs for Autodocumentation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2857]
The review of the prototype Eucalypt model pointed out that some of the fonts used on graphs in the automatically generated documentation are small.  We suggest a review of font size for all graphs used in auto-doc to determine if a more appropriate size can be used.

**Comment by hol430** [comment]
@hut104 I think if we increase the font size on axis titles, we might have to move to 1 graph per row - there's just not enough space otherwise.

Also should we disable legends in the autodocs? It makes it kind of hard to actually see what's on the graph:

![image](https://user-images.githubusercontent.com/36427516/81250704-f765e180-9064-11ea-94ee-174ee8b70c76.png)

**Comment by hol430** [comment]
I'll take that as a "no, we don't want 1 graph per row, leave it as-is". Feel free to reopen if that's not what you meant.
