### ISSUE TITLE
Barley doco, sections being duplicated

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2910]
See screen shot of doco below.  A number of of the doco sections for plant model components are being duplicated in the cultivar section
![image](https://user-images.githubusercontent.com/7295858/43865279-3e7265ee-9bb6-11e8-8ad9-eba2f55ab1dc.png)

**Comment by HamishBrownPFR** [comment]
@hol430 are you able to help with this.  @hut104  fyi

**Comment by hol353** [comment]
To fix this, right click on 'Replacements' and tell it to not include in documentation. The reason is that the TitlePage at the top goes and finds the barley model and documents it. It then goes to the next node 'Replacements', finds a barley model under it and documents it again.

You might also want to exclude DataStore from the documentation as well.

**Comment by HamishBrownPFR** [comment]
Thanks @hol353, @hut104 can you do these two things.
