### ISSUE TITLE
Find All references similar to Visual Studio

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#3010]
It would be very handy for model development to be able to right click on a node tree and select Find All References to find where the node is referenced from - similar to Visual studio which brings up a list of all the references it finds in a panel.

**Comment by HamishBrownPFR** [comment]
There is a very old issue, #480, still unresolved to put some stuff on the view of each class listing its dependencies which may tie in with this?

**Comment by hol430** [comment]
@jbrider @hol353 (and anyone else who might be interested):

I have developed a working prototype of this feature which currently spits out all output to the status panel. It currently looks through all models in scope of the target model, and

1. Attempts to resolve all links
If the link resolves to the target model, it is considered a reference. Only problem is that link resolution fails if the model is under replacements and it is linking to something under a simulation (e.g. link to summary seems common). 

2. Reads all public string properties and performs an `Apsim.Get()`.
If this resolves to the target model, this is also considered a reference. I trim out `.Value()` so that function references also work.

A model can also be referenced from the source code (via `Apsim.Get() or one of the many alternatives`) but I can't think of a way to identify this at runtime from the GUI. Are there any other ways which models may reference each other which I've missed?

For now, I'm just writing output to the status panel, but how do we want to go about displaying this info to the user? I could write up a new view, but this would hide any information in the target model's view. Sometimes in the IDE it's handy to be able to see the 'view all references' panel and the source code at the same time. 

![image](https://user-images.githubusercontent.com/36427516/55364270-651b1200-5523-11e9-8e8f-4ddfce30c98e.png)

**Comment by jbrider** [comment]
Nice work - where it is is fine - if you wanted to improve it, I would do something similar to VisualStudio's tabbed output windows in the bottom panel - but I doubt that it's worth the extra work at this point. Something to keep in mind maybe if some similar model analysis also required output in the future.

**Comment by hol353** [comment]
Agree with @jbrider. Let's leave it the way it is for now.

**Comment by hol430** [comment]
What I had in mind was something similar to visual studio, where you click on a reference and it takes you straight there. Or would this just be wasted effort?

**Comment by jbrider** [comment]
Sounds great to me.
