### ISSUE TITLE
Error loading MonoMac

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3044]
This is a bug that manifested itself when I clicked on a soil water node, although I suspect that any call to `APSIM.Shared.Utilities.ReflectionUtilities.GetTypeFromUnqualifiedName()` should produce this problem.

While attempting to enumerate the types in the ApsimNG assembly via `assembly.GetTypes()`, I get an exception `Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

I re-added MonoMac.dll as a reference to the solution and the problem went away. Unfortunately, git is not showing any files in my solution as being changed, so I'm not sure that I can push a 'fix'. Furthermore, I'm not sure I can even reproduce this problem anymore, now that I've 'fixed' it.

Is anyone else able to reproduce this problem?

**Comment by zur003** [comment]
Just include MonoMac.dll as part of the distribution. It's really only used on Macs, but I guess since it's included as a reference, the frameworks expects it to be there. Apsim mostly runs OK on Windows without it, but I found it needs to be present when run with Mono, so it's already being included in the Linux installation, even though it's really just extra baggage.

**Comment by hol430** [comment]
This issue emerged when I was building from source - I haven't noticed any issues using the installed version. I guess since no one else has noticed this behaviour it was probably due to something I did on my machine.

**Comment by hol430** [comment]
Re-opening, as another user has found this problem.
