### ISSUE TITLE
Make Apsim API use generics

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3061]
Calls to most of the static Apsim methods which go looking for a model (such as `Apsim.Parent()`) are almost always followed by a cast. If we make these methods generic, we can avoid the need for such a cast.

For example, instead of 
```
public static IModel Parent(IModel model, Type typeFilter) { }
...
Simulations parentSimulations = Apsim.Parent(this, typeof(Simulations)) as Simulations;
```

We could have
```
public static T Parent<T>(IModel model) { }
...
Simulations parentSimulations = Apsim.Parent<Simulations>(this);
```

**Comment by hol430** [comment]
Just found a bug in this API which I will put under this issue. `Apsim.Parent(IModel, Type)` is supposed to throw if it doesn't find a matching ancestor, but in reality it will just return the top-level model (which should always be a Simulations object).

**Comment by hol430** [comment]
@hol353 how do we want this to work exactly? I'm not really a fan of the create a class and pass the model into the constructor idea. It would turn a lot of simple lookups into a two-line job (or one line if you call a method on the constructor which I don't really like either). Maybe we just leave them as static methods for now (but make them generic).

**Comment by hol353** [comment]
If you're writing a model, then we could avoid creating an instance by using links e.g.

`[Link] Locator finder = null;
...
finder.Find<double>('wheat.lai');
`

**Comment by hol430** [comment]
We also need to add the ability to easily find a model based on name and type.

**Comment by hol353** [comment]
Let's do as you suggest above and move the parent / child methods from Apsim.cs into some generics into Model / IModel. e.g.

`public string FullPath { get; }`
`public T Parent<T>() // Maybe called ancestor instead of Parent although Parent/Child works?`
`public List<T> ChildrenRecursively<T>();`
`public T Child<T>;`
`public List<T> Siblings();`

Each of these would return object(s) of the specified type T. 

Unfortunately we already have a `List<Model> Children`. This doesn't match the ChildrenRecursively above. Should we rename Children to something else?

Rather than having all the variants of child, children, childrenrecursively and child by name, type and isvisable, we could go minimal and rely more on LINQ e.g.
`public List<T> Siblings();`
`public List<T> Children();`
`public List<T> ChildrenRecursively();`
`public List<T> Parents();`

Small API's are easier to document and remember.

I also wonder if these should all be `IEnumerable<T>` rather than Lists to stop inadvertent adding / deleting. Although some models do want to add child models at times (e.g. manager).

**Comment by hol430** [comment]
Yes, this sounds good and this will make life so much easier. A few thoughts

- I think Children is a good name for the property we already have. Perhaps the Parent and ChildrenRecursively functions could be called Ancestor (I find Parent a bit misleading) and Descendants (both for consistency with the Ancestor terminology and it's less to type than ChildrenRecursively)
- You're right a small API is easier to document and use (and test). However, many apsim users who write manager scripts are not C# programmers and I would hesitate to recommend that they use linq, as manager scripts can be difficult enough to setup as-is. Linq is also inconvenient to use when debugging (ie typing into a watch window - it's just more to type), so perhaps we should consider some convenience functions. Not sure what the best solution is here,
- Kind of related to the above point, but if we define a function `public List<T> Siblings<T>()` then I think we should also provide `public T Sibling<T>()`. This would apply to all methods of locating models, e.g. Ancestors, Children, Descendants, ... Perhaps in the longer term, we could think about combining these into one method where you pass in a relationship type (sibling, ancestor, ...) but that may be beyond the scope of this issue
- IEnumerable sounds like a good idea. Nothing should ever touch the children property directly (that I can think of). Everything should be using Structure.Add() or Structure.Remove().
- Do we want to keep the `Find()` and/or `FindAll()` methods for finding models in scope of the model? I notice you didn't mention it. I think it makes sense to keep it here, although I'm not so sure about `Get()`. Having `Get()` and `Find()` is just confusing.
