### ISSUE TITLE
GDI+ error when attempting to save ApsimSummary.png

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#313]
Attempting to view the summary on a fresh install.

When trying to save this image the following error occurs on Line 46 of Configuration.cs:

A generic error occurred in GDI+

See http://weblog.west-wind.com/posts/2015/Mar/27/Bitmap-types-Binary-Resources-and-WestwindGlobalization for more information. Running on Windows 10, will do further testing on Win7 to see if this is a W10 issue or we just haven't seen it since the code isn't executing as we already have the image saved.

**Comment by zur003** [comment]
It may not be exactly the same underlying problem, but when working with the Dymex/Climex code, I found that some code with GDI+ calls that worked in Windows 7 failed when run on Windows 8 and above. In the Dymex/Climex case (which involved native code, not .NET), GDI had not been properly initialised due to a coding oversight, but Windows 7 was forgiving of the error.

**Comment by fai04d** [comment]
The code works fine on Windows 7, looks like a Win 8+ issue.

**Comment by fai04d** [comment]
Tried again on Windows 10. Had the error appear once, stopped the debug to change exception settings and the error went away. Removed the created image, reset debug settings and still no error; image saves correctly.

I'm not convinced this is resolved so I'm going to leave it open but at this time I can't replicate it anymore. Need more testing under Windows 10.
