### ISSUE TITLE
Virus scanner problem

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3162]
The Cylance virus protection software that CSIRO has recently moved to appears to have put my ApsimX Updater into quarantine. Has anyone else run into this?

**Comment by hol430** [comment]
Muck (one of the Jenkins build agents) has a recurring problem where the updater is flagged as a system file. It's invisible from the file explorer but it will show up if you open a command prompt in the bin directory and run 

```
dir /a:s
```

It can be fixed by opening an elevated command prompt in the in directory and running 

```
attrib -s -h Updater.exe
```

and then deleting it. I had no idea what was causing the problem, but your post prompted me to check cylance, and which appears to be the culprit. 

I must have killed cylance on my working machine which is why I've never noticed it until now.

**Comment by hol430** [comment]
I have since filled out a "waive request" via cylance and IM&T have told me that the file has been added to the safe list, and that it should no longer be detected by cylance. Unsure if this will affect other people's computers or just mine.

**Comment by zur003** [comment]
I've had to issue a waive request as well. This is likely to be a bit of an issue for anyone in CSIRO, or using Cylance elsewhere.

**Comment by hol430** [comment]
This is from Martin in IM&T

> When you do a release you’ll have to submit a waive request for that version of the updater if it is picked up by Cylance so that other people in CSIRO can run it. 
>
> A possible alternative would be to sign the files in the release and for us to whitelist the certificate used to sign them in Cylance. 
> 
> It might also be helpful to properly fill out the metadata for updater.exe, i.e. a proper version number, module name (instead of MyApplication.app), etc. I doubt that will stop Cylance from detecting it, but it is generally helpful anyway and since it is generally only picked up with a very low score there’s some chance that it would help. 
> 
> There are a few cases when newly generated files are triggering Cylance, but they aren’t common. The most common ones are Fortran and compiled autoit scripts.

I'm hoping one of these suggestions fixes the problem, as I'd rather not have to fill out a waive request each time a new version gets released.

**Comment by hol430** [comment]
This should no longer be a problem since we now sign the updater.
