### ISSUE TITLE
fix/improve weather data plotting

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3196]
There is a fault in the current weather data graphing package. If you clisk on temperature or rainfall tab and attempting to manually insert number of years, this causes APSIM to crash

Improvements: would be good to be able to manually insert start year of comparison (currently have to click arrow many times)

Not sure if it is possible but it would be nice to be able to create overlay line graphs - e.g. to compare whether temperature/rainfall/radiation in a certain year were higher or lower than another year (to help understand why sims might be performing differently). Would also be ideal to be able to isolate a portion of the year e.g. the crop growing season (might be June-October for a winter crop but September-february for a summer crop).

Added complexity. To really make this useful, it would need to be able to compare two separate met files.

**Comment by hol430** [comment]
The crash described here has been fixed, and the user is now able to manually insert the start year (rather than having to click the up arrow many times).

The rest of the functionality here can already be achieved by adding the weather outputs to report and creating your own graph. I've attached a simple demonstration.

[example.zip](https://github.com/APSIMInitiative/ApsimX/files/4242860/example.zip)
