### ISSUE TITLE
Set the sensitivity of heat stress during maize flowering in APSIMX

### ISSUE THREAD

**Issue by ianzhangtianyi** [APSIMInitiative/ApsimX#3329]
In the old version, we can set it by changeing <temp_grain_crit_stress> and <htstress_coeff> in crop file. I am wondering how to set it in the APSIMX version. Thank you very much.

**Comment by hol430** [comment]
@HamishBrownPFR

**Comment by ianzhangtianyi** [comment]
Any reply? Thank you very much

**Comment by hol430** [comment]
Hamish is probably the best person to answer this but I think he's on leave at the moment. @hut104? @hol353?

**Comment by ianzhangtianyi** [comment]
> Hamish is probably the best person to answer this but I think he's on leave at the moment. @hut104? @hol353?

Thank you very much

**Comment by hol430** [comment]
@HamishBrownPFR are you able to help here?

**Comment by HamishBrownPFR** [comment]
Sorry guys, had missed this until now.

As a general answer, the crop parameter files have been in-beaded in the source code to stop post release modifications to the model.  The recommended way to have parameters changed now is to submit an issue (like this one) with evidence of the problem that is being caused by the released parameters.  Then someone needs to implement the changes and check they do not degrade the performance of the model with the existing test set.   The the changes are released (and gained by the user by clicking the update button in the GUI) and ideally the data used as evidence of the problem entered into the test set for ongoing model performance evaluation.

The specific answer to this question will depend on which crop/crops you are interested in and if the change is a general crop coefficient or cultivar specific.

**Comment by HamishBrownPFR** [comment]
Sorry, I missed the title, Maize is the crop of interest.  For the current released maize model we have not implemented any heat stress effects during flowering because we did not have a good data set or publication to base this on.  @ianzhangtianyi if you can provide us with this we may be able to implement something.
