### ISSUE TITLE
Manager scripts with 'wrong' data in Properties (saving too early?)

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3368]
Was unsure how to give this a title but hopefully below makes sense.

- start with a valid Manager script
- change the type of a parameter in the script (e.g. from string to DateTime)
- go to the Properties tab to enter the information in the new correct format
- the Properties tab is blank (so the fix cannot be made) because the script won't compile as it is still 'seeing' the old (in this example) entry in string format
- only solutions seem to be to directly edit the JSON (on which I had limited success) or back out the changes to the script, clear the data in Properties (the script will now compile), change the type and re-implement changes

This used to be easier I think.  Any solution?

**Comment by hol430** [comment]
The properties tab is not blank for me at step 3, but then again, any changes which I make to the property value don't seem to persist. The quick and dirty solution until I patch this is to give your property a different name as well as a different type.

**Comment by hol430** [comment]
I've fixed this in my branch, but there is a caveat. If you change the type of a property such that its "value" is now invalid, a default value for the property will be displayed in the properties tab instead of the old (now invalid) value. An error message is also displayed. How do you feel about this change? Is it important that the old value be displayed even if it is now invalid?

**Comment by sno036** [comment]
I don't think it matters if the old/incorrect values are shown or not, just that the user can see them to edit in a correct value. Thanks for sorting this.
