### ISSUE TITLE
Sowing and Harvesting event handlers are never called if manager script is put in a folder

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3383]
In this example simulation, the EventHandler **OnSowing** is never called in manager scripts **FertliserZ30** and **FertliserZ37** if the managers are put in a folder (I need to have this folder, https://github.com/APSIMInitiative/ApsimX/issues/3378). It is called when I put the manager outside the folder. Other event handlers like **DoManagement** work file.
Any solution?

[01_Sims.zip](https://github.com/APSIMInitiative/ApsimX/files/2670107/01_Sims.zip)

```
    [EventSubscribe("Sowing")]
    private void OnSowing(object sender, EventArgs e)
    {
     	Debugger.Break();
        hasFertilised = false;
        cumRain = 0;
 	}
```

![image](https://user-images.githubusercontent.com/39573622/49841175-45d86780-fe02-11e8-8ef2-67dae9832e7f.png)

**Comment by hol430** [comment]
This is happening because a plant is a scoped model. A quick workaround for you would be to temporarily comment out the `[ScopedModel]` attribute on line 21 of `Plant.cs`, but I'm not sure if this is a change which should be merged. @hol353 what do you think? Should `Plant` be a scoped model? Or do we need to change the scoping rules?
