### ISSUE TITLE
Some HTML tags ignored when generating documentation PDF

### ISSUE THREAD

**Issue by FlorjanCamlek** [APSIMInitiative/ApsimX#3389]
I have noticed some HTML tags are correctly applied in APSIM memos (i.e. the effect is visible in the bottom memo panel). They are however ignored when the PDF is generated.

Example 1: \<strong>Text\</strong> works as expected both in APSIM memo and documentation PDF.
Example 2: \<p style="text-align:justify;">Text\</p> and \<b>More Text\</b> only work in the APSIM memo.

**Comment by hol430** [comment]
The documentation generator looks for [markdown](https://apsimnextgeneration.netlify.com/usage/memo/) rather than HTML. e.g. for bold text, you can use \*\*Bold text\*\*. Paragraphs can be created by separating your text by two newlines.

That link points to a markdown cheat sheet on the Apsim website.

**Comment by zur003** [comment]
The data flow here is intended to be: Markdown => HTML => PDF. It is possible to embed bits of HTML in Markdown documents to produce valid HTML documents in the first step. However, the conversion of HTML to PDF is not very robust. That step translates only a limited number of HTML tags, and makes assumptions about the structure of the HTML that are likely to be broken with HTML not emitted by Markdown.
