### ISSUE TITLE
Graph of volumetric soil moisture is frozen

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3392]
I have two very different soils in my simulations but their graphs are just the same.

![image](https://user-images.githubusercontent.com/39573622/50255614-527e4080-043e-11e9-808e-23442cdcbb40.png)

![image](https://user-images.githubusercontent.com/39573622/50255617-5742f480-043e-11e9-8040-1fa93a2d0a6a.png)

**Comment by hol430** [comment]
I think I saw a similar bug a few weeks ago, which was due to the soil water node having a different number of rows of data to the crop soil water node. Can you attach the .apsimx file to this issue?

**Comment by BenAbabaei** [comment]
[TEHartog-2.zip](https://github.com/APSIMInitiative/ApsimX/files/2719828/TEHartog-2.zip)

The number of rows is the same. I think it has to do with the soils being introduced as factors.

**Comment by hol430** [comment]
Yep, it's because the soil is under a factor and not under a simulation. Do these graphs look correct?

![WaterGraph1](https://user-images.githubusercontent.com/36427516/50616904-3c8c7780-0f36-11e9-8ca8-06688a78b060.png)

![WaterGraph2](https://user-images.githubusercontent.com/36427516/50616919-48783980-0f36-11e9-8c97-9e525686635c.png)
