### ISSUE TITLE
Bind code created model to clock events

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#3424]
I am wondering if you can create a model in the code of another model and bind all the EventSubscribe events to the clock so the model will respond to events?

I have a model that does some summarising of ruminant herd data and I used to have a separate report that wrote the summarised data to the datastore. I was wondering whether I could create a report in this model, provide it with the desired parameters and events and link it to all the APSIM clock events so it works like a Report added to the tree structure by the user.

I don't want to repeat all the Report.cs functionality in my model and haven't found any other examples anywhere.

**Comment by lie112** [comment]
I believe there is quite a divide between the more modelling expert users of APSIM and the ecologists, Ag scientists, extension officer users of CLEM. For this reason we have added quite a bit of data entry validation, graphical display of simulations, and HTML descriptions of the setup to assist the user and make it a more friendly modelling environment.
I have found the report model to be a bit buggy and not produce clear error messages to the user when not setup correctly which requires detailed understanding of the parameter space. (I found there have also been some changes to the format of error messages reported in APSIM to include file and simulations now). For this reason I made a couple custom reports that automatically fill in the parameter and event details that our users don't understand and all they need to enter is a few simple values they can see in their user interface tree. 
What I was after would be a report that you can pass all the setup information to as JSON or TXT. I could create some derived models from report and fill in the details during OnStartSimulation before they get all hooked up at OnCommencing.
At present we have a model to do the data summarising and a second report to write the summarised data to the datastore. I was hoping to combine these for simplicity and thus not need the user to add the report.
I was wondering if my question was used elsewhere to create models in memory that are then bound to the clock events and operate as if they were in the UI tree?

**Comment by hol430** [comment]
You should be able to create a `Report` model in memory, add it into the simulations tree by giving it a parent, and set its `IsHidden` property to true. That way the user won't see it. You could then set its `VariableNames` and `Eventnames` properties as you like, and it should do the rest by itself. Then, inside the model which creates the report, subscribe to the `EndOfSimulation` event and remove the report from the simulations tree so that it doesn't get written to the .apsimx file. As a disclaimer, I haven't tested this, but I don't see any reason why this general approach shouldn't work.

That said, it might be better to just work on the current report model to get it to the point where your users are comfortable using it. You're welcome to work on it yourself, or if you want to create some issues here on github then I'll have a look at it. In the short-term, even just improving the error messages could go a long way.

**Comment by hol430** [comment]
@lie112 did you end up getting this to work? If so can this be closed?
