### ISSUE TITLE
Number of recently opened ApsimX files

### ISSUE THREAD

**Issue by pre078** [APSIMInitiative/ApsimX#3501]
I've noticed that I am only seeing 2 recently opened APSIMX files.  I prefer to see more.  Has something changed or is there a setting I need to change?

**Comment by hol430** [comment]
Is your computer running Windows?

**Comment by pre078** [comment]
I'm running Windows 10 and used to have a large list of recently opened APSIMX files but I now only see 2.

**Comment by hol430** [comment]
This setting is stored in an xml file: `%appdata%\APSIMInitiative\ApsimX\ApsimX.xml`. If you're familiar with xml, you can edit the file - the setting you're interested in is called FilesInHistory. 

Otherwise, deleting this file and then starting and closing Apsim should reset the setting back to its default (20).

**Comment by hol430** [comment]
@pre078 Did this fix the problem for you?

**Comment by pre078** [comment]
Yes, thankyou
