### ISSUE TITLE
Performance test site graphs not working

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3552]
The XY graphs of predicted vs observed for current and accepted tests sets are not showing.  Instead when you click something that should take you to these graphs (A bar on the graphical results page, a heading in the Tabulated results page or a link to a test set on the main page) you get an error page
![image](https://user-images.githubusercontent.com/7295858/53354317-6472e700-398b-11e9-87ec-d25cdad2791a.png)

Error message
![image](https://user-images.githubusercontent.com/7295858/53354186-25dd2c80-398b-11e9-8c4e-c8dcd8e7f4f3.png)

**Comment by hol430** [comment]
Was this working recently?

**Comment by HamishBrownPFR** [comment]
It wasn't working when Dean and Neil were over here.  I am not sure how long ago it broke because I haven't been doing pull requests for a while

**Comment by hol430** [comment]
@HamishBrownPFR @hol353 

The reason this isn't working is because one of our tables in the performance tests database contains about 300 million rows of data, and the performance tests site times out while waiting for a query to run. I experimented with removing the timeout, but was forced to give up after waiting 15 minutes for the query to run.

After looking into this some more, it appears that many of the queries generated by the .net entity framework tend to be convoluted (to me) and very slow. I've rewritten one of these queries and it now runs in much less than a second. I'm now working through the rest of the queries but it will take some time.

As an additional measure I wonder if it's reasonable to delete old data. How often do you look at stats for pull requests which are over a month old? I guess it could be useful/interesting to look at how our stats have changed over time, but consider that this DB only contains 1 year's worth of data - and it's already rather large.

**Comment by jbrider** [comment]
It sounds more like a query issue than a database size problem.
If we need to keep them, can we archive those older than a month... sounds like it might take longer than fixing the queries though?

**Comment by HamishBrownPFR** [comment]
I think @hol430 has a reason for keeping this data.  Check with him before deleting any

**Comment by hol430** [comment]
@HamishBrownPFR is this working for you now? I haven't changed anything on the live website but it seems to be fixed for reasons I do not understand...

**Comment by HamishBrownPFR** [comment]
Yes it is working now

**Comment by HamishBrownPFR** [comment]
Closing issue as it seems to have resolved its-self

**Comment by hol430** [comment]
I'm re-opening this, as it still seems to intermittently occur.

**Comment by HamishBrownPFR** [comment]
@hol430 is it possible to give this fix some priority.  I am trying to review a couple of pull requests from @byzheng but it is a but tricky without being able to see the xy graphs.

**Comment by hol430** [comment]
Yeah will do

**Comment by HamishBrownPFR** [comment]
thanks @hol430

**Comment by hol430** [comment]
@HamishBrownPFR I think I've fixed this, although some pages are still somewhat slow to load. Is this working for you now?

**Comment by HamishBrownPFR** [comment]
Yep that is working for me now thanks @hol430
