### ISSUE TITLE
APSIM almost stopped working after output file became very large

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3612]
I have been running APSIM with a large dataset on my laptop. Simulations were expected to take at least 20 hours. But they got extremely slow after half of the simulations were done. I have 50GB of free space on my HDD and 32GB of RAM.

I am not sure if it has something to do with them being run on a laptop or the size of the output file. I am sharing this in case there is a problem in the code which makes scaling troublesome.

![image](https://user-images.githubusercontent.com/39573622/54319016-e3c31480-4633-11e9-9e69-43eccabaf9d2.png)

![image](https://user-images.githubusercontent.com/39573622/54319030-ef164000-4633-11e9-92c0-7e069ab6d47a.png)

**Comment by byzheng** [comment]
@BenAbabaei I don't think SQLite has a good performance for the large database. It might be better to separate your simulations into smaller files.

**Comment by BenAbabaei** [comment]
Thanks @byzheng I am trying to do that. Cheers.

**Comment by hol430** [comment]
You could have a look inside your temp directory. We had a problem a while ago with Apsim generating huge numbers of temp files and not deleting them, which led to collisions when looking for new temp filenames. I thought this problem was fixed, but someone reported running into this a few weeks ago. Would be curious to know if this is causing you any grief.

**Comment by BenAbabaei** [comment]
@hol430 It could be that as I have not updated for a couple of weeks. I will have a look into it. Cheers.

**Comment by zur003** [comment]
@BenAbabaei - I would be interested in knowing whether the fix for #3614 has made any difference here.
