### ISSUE TITLE
Improvements to APSIM.info

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#383]
I tried redirecting a potential APSIM user to the website to find contact information for the APSIM initiative.  We found it almost impossible to find this information from the website.  (I ended up reading out Chris's email address to them).

1) The links page is empty.  It includes no links or text of any kind.
2) There is no information about links to "us" in the About us page.  Not even info on the footer.
3) The main welcome page has an email address, but it is in the footer and you need to scroll down several pages to reach it.  When you do, the link is in a colour that is almost invisible on that footer background.
4) That contact information is not on the footer of any other page.
5) There are links to people on the welcome page within the news items.  But if you click on any of those links, the link takes you to ... the welcome page.  The links to people are in red, which seems strange.
6) There should be a contact us link on the main menu that provides clear information on who to contact and how to contact them.

A few other bugs
6) The "Go" button for the search box is detached from the search bug and floating on the menu bar
7) If you log in to the site you get a link to your profile on the menu bar.  But it is also coloured in a way that it is invisible on that background.
8) The links for news items titles simply changes the date of news items shown.  I see no reason for them to be links.  It just causes confusion and hides information.
9) The footer has three parties as being members on the AI.  Is this still correct?

**Comment by fai04d** [comment]
1) Links page has been renamed to Contact Us which now has contact information.
2) Info now in Contact Us section.
3) Fixed the colour, link is also in the new Contact Us section.
4) Fixed.
5) Disabled profile links on news articles.
6) Still working on it...
7) I think I fixed that awhile ago. The link is more visible now.
8) This is part of the news module functionality. What you're actually seeing on the front page is supposed to be a summary. The idea is that you click it then the rest of the article comes up. Since we only have short news articles we don't really use more than the summary.
9) This has been updated.

**Comment by hut104** [comment]
Good to see the system works.

On 22/01/2016 3:09 PM, Justin Fainges wrote:

1) Links page has been renamed to Contact Us which now has contact information.
2) Info now in Contact Us section.
3) Fixed the colour, link is also in the new Contact Us section.
4) Fixed.
5) Disabled profile links on news articles.
6) Still working on it...
7) I think I fixed that awhile ago. The link is more visible now.
8) This is part of the news module functionality. What you're actually seeing on the front page is supposed to be a summary. The idea is that you click it then the rest of the article comes up. Since we only have short news articles we don't really use more than the summary.
9) This has been updated.
