### ISSUE TITLE
On MacOS the dropdowns don't work

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#3959]
On several MacOS computers, I've seen the problem where clicking the drop down button with the mouse on a combo box causes the dropdown to appear and disappear very quickly. The work around is to click in the combobox and hit a key on the keyboard. This displays the dropdown and lets you select an item. On the computer in Iowa, I checked the Mono version. Here is the screenshot:
![IMG_20190612_141833](https://user-images.githubusercontent.com/1943827/59891747-bac3d400-9419-11e9-8676-e6c356635f6d.jpg)

**Comment by hol430** [comment]
This often happens on Linux as well for drop-downs in grids. They seem a little unreliable at the best of times. The file chooser button in the excel input component is similarly difficult to use.

**Comment by zur003** [comment]
This is an odd one, and very annoying. I doubt that it has anything to do with the version of Mono. It seems to be an issue at the Gtk level. From what I can tell, the drop-down appears when the mouse button is pressed, but disappears again as soon as the button is released.

**Comment by zur003** [comment]
For what it's worth, I've tested this is a number of old releases, and this problem appears to have been introduced with the GridView refactoring in July/August 2018. It's still not at all clear what's going wrong, or why it isn't a problem on Windows.

**Comment by zur003** [comment]
This is all very odd. On the non-Windows platforms, a mouse press initiates editing and immediately expands the combo's list of items. The subsequent mouse release is then treated as a "selection" action and terminates the editing. Windows works differently - the combo goes into editing mode, but doesn't immediately display the list, so that explains why it works on Windows - sort of. The odd thing, though, is that this problem didn't happen before the August 2018 refactoring, even though there doesn't seem to have been significant changes in the way editing is being initiated. I have not been able to figure out why.

As a work-around, I've submitted a pull request which delays putting the comobox renderer into edit mode until the mouse release event. This works, but we really shouldn't have to do things this way.

**Comment by zur003** [comment]
I'm reopening this because there appears to have been a small regression. On non-Windows (mono) systems, if the user closes the combo box without changing the selection, it blocks the user from any additional edits in the grid. The grid apparently thinks the cell is still being edited, and won't initiate any new edits.

**Comment by hol430** [comment]
I think this might also happen on Windows(?)...I seem to recall seeing this behaviour, but I must have forgotten to log it.

**Comment by zur003** [comment]
@hol430 - You are correct - this can be a problem on Windows as well. Pull request #4192 should resolve the problem on all platforms.
