### ISSUE TITLE
Refresh data store does not work

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4007]
Right clicking on a data store and selecting 'refresh' does not work - a message is displayed in the status panel saying 'Post processing models have successfully completed' but this appears to be a lie because the post simulation tools do not get run.

**Comment by hol430** [comment]
Sometimes the datastore's filename gets set to :memory: which causes the excel input component to fail. This also causes any subsequent simulation runs to fail until the file is closed and reopened. This often seems to occur when running with the f6 multi-process job runner.

**Comment by jbrider** [comment]
This is caused by not having any simulations to run.
The function PostAllRuns which will call the postProcessing tools only gets called when the last job completes.  No jobs, no event gets published.
Possible solutions:
1. a dummy job to ensure the event is published - only added when there are no jobs.
2. add the postprocessing functions as a job - this will also show that there is still 1 job running in the interface - would be useful.  It would need a flag of some sorts to wait until all the other jobs have finished - not sure how easy that is.
3. add a check for no jobs that then calls the postprocessing?

**Comment by hol430** [comment]
Re-opening because error messages don't appear in the UI.
