### ISSUE TITLE
Weather graphs not displaying

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#4019]
With some recent upgrades, the weather graphs are not displaying at all for the tabs: Rainfall Chart, Temperature, and Radiation, but back-grading to say 2019.6.27.3976 produces the correct graphs. I've tried this on several simulation files and two computers. The error message is in this screenshot
[Weather graphs not displaying.pptx](https://github.com/APSIMInitiative/ApsimX/files/3394537/Weather.graphs.not.displaying.pptx)
:
![image](https://user-images.githubusercontent.com/49378212/61254848-7bcf3700-a7a9-11e9-8feb-37533d724c13.png)

**Comment by rcichota** [comment]
I came across the same error while trying to debug a simulation. It seems the issue is when dates are re-analysed (in DataTableUtilities.cs). The input data there contains dates that are not in a recognised format, even though all seems ok to me. The first date that breaks is always a 13th (like 13/01/1940 for Goond.met), which hints that the code is interpreting month-day-year, but the input is not in that format... It doesn't seem to cause any error in how the rest of Apsim runs.
Here is the lines where it crashes:
![image](https://user-images.githubusercontent.com/12175986/61419264-96dcab00-a951-11e9-97d2-1251fef20452.png)

**Comment by hol430** [comment]
I'll have a look at this next week
