### ISSUE TITLE
Popup appears after clicking on ZoneClem node

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4040]
If I open a clem example and double click on a ZoneCLEM node, a popup appears which is hard to remove. Note that before double clicking, I have to have a different node selected.

**Comment by lie112** [comment]
Can you better explain this problem? I did have a problem where one of my tabs in the GUI would revert to a popup because the Properties presenter took too long to propagate in its tab as it is the slowest to create especially the first time. I reordered my tabs to put the properties tab last as I was unable to identify why GTK would revert to making a popup instead of placing the presenter inside a tab item. This was often a problem in development or when the system was under strain such as webex.
CLEM does not create any popups, but everything is placed in the GUI. I don't understand GTK enough to resolve the problem and I thought my work around had fixed the issue as we hadn't seen it for ages. It could be that a double click of the CLEMZone node tries to quickly build the display twice and one of the tabs is again thrown to a popup instead of a tab control.

**Comment by hol430** [comment]
Here's what I do to cause the problem:

1. Open CLEM_Example_Cropping.apsimx (one of the example files shipped with apsim)
2. Expand the 'cropping examples' folder (without selecting this node)
3. Expand the 'single and mixed cropping' simulation (without selecting this node)
3. Double click on the node called CLEM

At this point the contents of the versions tab pops up in a new window.

**Comment by lie112** [comment]
You have identified a way of reproducing the original problem that was also with the versions tab.
I'd appreciate any help with Gtk to fix this.
As you will see I am simply calling three or four presenters and placing them inside a Gtk tabs of a tab control.
I don't know why Gtk would revert to creating a popup as I have no mention of any popup windows.
