### ISSUE TITLE
Clock.StartDate and EndDate should be optional inputs

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4048]
When they aren't specified they simply run whatever dates are in the weather file. Sometimes StartDate might be specified but not EndDate. This should also be possible.

**Comment by hol430** [comment]
What if the simulation has no weather component?

**Comment by hol353** [comment]
Then throw an exception.

**Comment by lie112** [comment]
CLEM uses StartDate and EndDate to identify period of simulation as no weather component is required.

**Comment by hol430** [comment]
That should still work as long as the user provides a start and end date.

**Comment by hol430** [comment]
@lie112 As part of this I've made some changes to the grid view; I've moved data validation out of the grid view and into the presenters because the grid view often lacks a lot of necessary context such as what type of data it's displaying. Unfortunately this also means that the grid view will no longer update its own contents automatically after the user changes them; the presenter will need to manually update the grid view's DataSource. I was tempted to have the grid view automatically update itself with the value entered by the user, but what happens if the value is invalid? Should the presenter have to manually reset the grid's contents to their state from before the change before it throws an exception?

It's a bit annoying but it will only affect grids which are editable - ie it won't affect the grid used in the data store view.

The reason I mention this is that there are a few clem components which use the grid view. I've tested them where possible but some views (such as `CLEMFileSQLiteGraspView`) are not used in any of the examples/tests. Do you have any sample clem .apsimx files which I can use to test these views?
