### ISSUE TITLE
Scenario crashes with latest version APSIM2019.08.06.4066

### ISSUE THREAD

**Issue by HemdaLevyNZ** [APSIMInitiative/ApsimX#4073]
Scenario that worked fine with APSIM2019.06.03.3879 crashes with the latest version: APSIM2019.08.06.4066

[P2_1_1-June-2014_to_1-June-2016.txt](https://github.com/APSIMInitiative/ApsimX/files/3475177/P2_1_1-June-2014_to_1-June-2016.txt)

Please note: 
I had to use extension .TXT for the  uploaded scenario, because .APSIMX wouldn't upload.
Also version number in the file should be 57 at most (in order to load in the older version of ApsimX)

**Comment by hol430** [comment]
The problem here is that in your 'Allow' factor, you're trying to change a property of the manager script called `IrrigationOnDeficitManager`. However, this manager script has been disabled so we can't change any of its properties (all disabled models are removed from the simulations tree when the simulation is run).

**Comment by markhanigan** [comment]
Thank you for replying, but I find your reply disappointing.  

I have specifically mentioned that a version of 2 months ago worked just fine. 
The fact that the manager is disabled never caused a problem with the version from 3.6.2019 (and previous versions) and in my opinion it shouldn't cause a problem with any later version. A missing property or manager should not be an excuse for a crash in the software -  **this is a bug that should be fixed.**

Also I did enable that manager and ran it again only to get another crash.

**I would see this simulation as an opportunity for you to fix crashes rather than to get away with some "explanation" and to put the blame or responsibility on the user.**

**Comment by BenAbabaei** [comment]
This is an open forum for an open source software. You have not paid for this and these people are already doing a great job supporting all the active developers. So, cool down for APSIM's sake!

**Comment by markhanigan** [comment]
to BenAbabaei: This forum is titled  "Issues" and I had an issue to report which I did. And that's my contribution to the project. I didn't have to report and I could still carry on my work without reporting (and without a fix).
The fact I didn't pay for the product has nothing to do with its quality. 
I would have much more appreciated  a reply of "this is too minor and we are not going to spend any time on fixing it" than being told off about my bad simulation.
These people are indeed doing a great job, and therefore I am using their product (in spite of many problems, which I don't bother to report because I know they will be fixed at some point). This time it was a crash, which I didn't think other people bumped into and that's why I reported it and got dismissed as a reaction.
If APSIM's sake is indeed the top of your priority than you should be encouraging them to embrace ANY issue reported as a contribution rather than trying to calm me down (which is absolutely redundant and beside the point).

**Comment by hol430** [comment]
You need to specify a value for XF in the bottom layer of SwardSoil (Simulations -> AgPasture -> Sward -> Sward -> Field -> Soil-> Water -> SwardSoil). If your simulation still fails you will need to post either an error message or a met file so I can run it myself.

**Comment by markhanigan** [comment]
to hol430: Thank you for your comment. There was indeed a missing 0 in XF which I never noticed before. Adding it removed the "second" crash.

Am I right to conclude that the original issue is not going to be handled by APSIM?
