### ISSUE TITLE
Ensure resources are kept up to date

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4110]
- Write a unit test that will fail if any resource isn't current. 
- Remove simulations node at top of resource. Put version number into Model.cs instead?
- Remove oats1.json and potato1.json resources
- Some resources e.g. oats don't display correctly by default. If you click on 'source' tab at bottom of window it is Ok.
- In GUI, change the 'Convert XML file' to 'Convert files'

**Comment by lie112** [comment]
Can you explain what "version number into model.cs" relates to?

**Comment by hol353** [comment]
It means move the version property from Simulations.cs into model.cs. It won't have a major implication for users. It will mean each model has a version number rather than the whole .apsimx file.

**Comment by lie112** [comment]
Thanks. That is the functionality I was after as I realised that it is version of the models that needed to be tracked not the over install. I had used the MS Version attribute that I associated with my CLEM models as I was able to keep the history of model numbers in the attributes rather than simply the latest. Is the new model property a developer set value?

**Comment by zur003** [comment]
Temporarily re-opening because part of the patch breaks undoing the addition of a model (see comments in #4129).
