### ISSUE TITLE
Problem entering numbers into MicroClimate View

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4118]
If a users tries to type a decimal fraction into the box for the rainfall multiplier, the "." starts intellisense and the user cannot enter a number thereafter.

**Comment by hol430** [comment]
The problem here is that the .apsimx file contained a model called 0 (I think it was a factor in an experiment controlling irrigation). After typing 0. into a grid, apsim showed intellisense suggestions for the '0' model.

I can't remember what we decided as the solution for this one (or if we even came up with a solution). Do we prevent users from assigning model names which are numbers? Do we prevent model names starting with numbers (as in most programming languages)? I suspect that both are reasonably common use cases.

**Comment by jbrider** [comment]
Preventing model names starting with numbers makes sense.

**Comment by hol430** [comment]
@hut104 @hol353 after thinking about this some more, I'm not so sure that we should prevent model names which are numbers. It's fairly common to see factor names which are numbers. Having a constant called 0 might also make sense. Maybe we should never show intellisense for a model name which is a number, even if such a model exists?

**Comment by hol353** [comment]
There are lots of cases where model names have numbers, particularly under factors. I don't think we should stop users using numbers in model names. Is there another way to fix the problem?

**Comment by hol430** [comment]
We could prevent the intellisense from appearing if the model name is a number.

**Comment by hol353** [comment]
Does the property presenter have the concept of number (double) cells. If so, then we could stop the intellisense when the user is typing into a cell with a data type of double.

**Comment by hol430** [comment]
We could do that, although that still wouldn't work in the case of the ExpressionFunction, where we type numbers, operators and variable names all into the same box.

**Comment by hol353** [comment]
Hmm true. For now go with your suggestion. Prevent the intellisense from appearing if the model name is a number.
