### ISSUE TITLE
Unexpected crash of UI

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4197]
This simulation crashes - with no nice messages even! I was trying to find out which link was not working and ended up with this. Adding this as I thought we have caught all the UI crashes.

[nextGen lesson.zip](https://github.com/APSIMInitiative/ApsimX/files/3640614/nextGen.lesson.zip)

**Comment by zur003** [comment]
What were you doing when it crashed? For me, it gives a somewhat reasonable message:

> The name 'nutrient' does not exist in the current context. Line number: 82

Requesting "More information" makes it clear that the problem is in "Fertilise on fixed dates".

So I'm wondering what you did to trigger a crash, rather than a semi-cryptic error message. Exception handling is meant to deal with most of these things.

**Comment by hol430** [comment]
I think I've isolated the crash - it seems to occur if the manager script does not compile, then I fix the manager script (in this case by commenting out the references to nutrient variable) then immediately clicking on another node.

There are two problems - the first is a gtk event handler with code that's not wrapped in a try-catch block (in TreeView.cs:433). The second problem is that the property presenter's model variable is set to null for some reason.

Actually, just looking through TreeView.cs, there are a number of event handlers for gtk events without exception handling, which could potentially cause crashes.
