### ISSUE TITLE
Property drop downs not working with dark theme

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4211]
When using the dark theme drop down boxes follow the theme, but the remaining properties are based on light theme such that the background of the grid is white and entries are black text and therefore the drop downs in their collapsed state do not show up and we can't see the drop down icon.

The value is there, but not showing up because the light text is the same colour as the grid background (which is incorrect)

This fault is present in windows and mac on the latest code for both @her123 and myself

**Comment by hol430** [comment]
The data store view also sometimes shows black text on white background in dark mode. Will look into it when I get the chance.

**Comment by hol430** [comment]
@lie112 Which view or node did you observe this in? I've fixed the problem with the data store showing up as white, but I want to double check that it fixes your problem as well.

**Comment by hol430** [comment]
@lie112 is this still an issue?

**Comment by lie112** [comment]
Yes. The font colour changes so you can't see the entry.
Here is the same drop down box in each theme.

![image](https://user-images.githubusercontent.com/19215637/73714142-8823dd00-4757-11ea-8922-904eb76e2c56.png)

![image](https://user-images.githubusercontent.com/19215637/73714181-ad185000-4757-11ea-95c1-029db4b67c8b.png)

**Comment by hol430** [comment]
Ah, thanks - I didn't look at the clem components. Will see what I can do.

**Comment by lie112** [comment]
These are just standard drop down boxes not CLEM controls and the problem should happen for any drop down enums.

**Comment by hol430** [comment]
Strange - the dropdowns in a regular PropertyPresenter work ok for me:

![image](https://user-images.githubusercontent.com/36427516/73714594-05058580-475d-11ea-8943-6928c41e0cc5.png)

But yeah - I'm seeing the same white view on the properties tab of a ZoneCLEM.

**Comment by lie112** [comment]
It should all be in the ProperyTablePresenter (line 465). if the display type is a CLEMResourceName it should use EditorTypeEnum.DropDown with set values. How and where does the DropDown editor get its colour and why not for your enums?

**Comment by lie112** [comment]
I just realised it was the white background and black text that was the problem. 
Maybe this is a problem of the nested presenters for the CLEM model wrapper and it misses some dark theme colour settings. I have had a look but not sure where the theme colours are set. I assumed it would use default like all the other parts of the wrapper that work.

**Comment by lie112** [comment]
I am having a look seeing this is a CLEM issue.
Can someone explain where the attributes of a GridView are set?
The onCellSetData method (line 448 of GridView.cs) sets cell background and foreground to white and black based on attributes.BackgroundColor  etc. This may be a problem of the CLEM table and groups property presenters copying another presenter that has since changed to allow dark theme. Is there a attibutes passed or set to change to dark theme? This section was developed by Shaun and I am trying to get my head around all the wrapping.

**Comment by hol430** [comment]
In theory you shouldn't have to do anything special to make the view work in dark mode - the widgets should automatically respect the gtk theme.

This doesn't seem to be the case in the grid view however, because we modify some of the colours in the PopulateGrid() function before the grid is realized (and therefore before the rc style settings have been applied). I'm not sure why we manually alter the colours here but if I disable this, it fixes the immediate problem here but seems to break custom colouring (e.g. PAWC columns in the soil profile view).

Regarding your question - the idea with the colAttributes is that the presenter can intervene and manually modify the foreground or background colour of a column. The PAWC columns in the profile view are one example of this. In practice though this mechanism seems a bit convoluted and could probably do with a redesign. I'll have a look at this next week.

I don't think this is a CLEM-specific problem - you can observe the same issue in the report component when you click on the data tab.

**Comment by lie112** [comment]
Very odd.
The first time I click on this model to view it all works

![image](https://user-images.githubusercontent.com/19215637/73803380-2f604d00-4808-11ea-8a7a-2ef2ab21f476.png)

But when I click off and back on, the settings have been lost

![image](https://user-images.githubusercontent.com/19215637/73803399-39824b80-4808-11ea-90fc-8c37c1cc6087.png)
