### ISSUE TITLE
Remember the last expanded state of simulation tree 

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4214]
Would it be possible to provide functionality to store the expanded state of each model in the simulation tree, save this with the apsimx file and reinstate the expanded state when the simulation is loaded?

Also would it be possible to add an expand all (ctrl right arrow) and collapse all (ctrl left arrow) right click menu option for treeview branches?

CLEM users develop complex tree structures and need to continuously expand the tree whenever a simulation is opened or apsim restarted.

**Comment by hol430** [comment]
This should be possible - I think there is a `TreeView.ExpandToPath(TreePath)` method which will do what you're looking for. Should apsim also scroll to your previous scroll position as well?

@her123 are you assigned to this because you're planning to implement it?

**Comment by her123** [comment]
Feel free to work on it @hol430

**Comment by hol430** [comment]
I have a working prototype of this feature. I'm planning to save the state of the expanded nodes into the configuration file (ApsimX.xml) rather than the .apsimx file. This means if Neville sends an .apsimx file to Adam, when Adam opens the file it won't expand to where Neville left off.

This requires changes to the structure of the configuration class however, which means that the first time a user opens the new version of apsim, their configuration settings (MRU file list, theme, font, etc) will be wiped out. This has been a problem for a while which I think people just put up with, but I think it would be good to solve this once and for all.

My suggestion would be to implement a converter for the configuration file format, similar to the converter for the apsimx file format. I've half-implemented this already, just thought I'd check that this is something which we want to pursue, before I progress any further.

**Comment by hol353** [comment]
Why is it wiped out? We deserialise the file don't we? If this is the case then adding a new property shouldn't upset the deserialisation.

**Comment by hol430** [comment]
We need to associate some data (list of expanded nodes) with each file in the MRU list. Yes, I could add another property and then we have separate array properties for each file in the MRU list. We would just have to make sure we always modify both at the same time.

I opted instead to add a new type which represents a recently used file, which contains the file name and the data I need. This is more work in the short term as I will have to implement a converter for the config file but in the long run we may end up needing this anyway.

**Comment by hol353** [comment]
Ahh OK. That sounds reasonable.

**Comment by her123** [comment]
Would it be cleaner to have an 'expanded' property for each model object? Then the state of the simulation being viewed stays within the simulation.

**Comment by hol430** [comment]
We could do it that way. I guess the advantage is that it's easy to show people what you're looking at/working on. On the other hand, if you add it as a property of each model, then expanding nodes in the tree will count as a change to the file. So you if you open a file, expand a node, but don't make any changes, then close the file, apsim will prompt you to save changes.

**Comment by her123** [comment]
It always asks to you to save changes after opening everytime anyway.

**Comment by hol430** [comment]
Only if the converter is run - which should only happen the first time you open a file after an upgrade.

**Comment by hol430** [comment]
@her123 @lie112 @hol353 what do we want - save the expanded nodes info in the config file or in the .apsimx file? There are some problems/implications either way.

**Comment by hol353** [comment]
Save in the config file please. If there is a problem where the GUI always asks, on exit, whether to save a file, then as issue for that should be created. If we save the expanded node state in the .apsimx file then the GUI will definitely always ask.
