### ISSUE TITLE
Presentation of versions in the Upgrade form

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4215]
In the upgrade form the user is presented with a list of versions (recent or all since the installed version? am curious but that is not my question/issue) but they do not seem to be in any sort of Version order (might be sorted by Description). Recommend changing to have the tip revision at the top adn possibly highlighted.

![image](https://user-images.githubusercontent.com/12176269/65655388-2dbf9500-e070-11e9-94be-370ed64c7acb.png)

**Comment by hol430** [comment]
The versions shown in here should be all versions more recent than the version you're using. There is a checkbox to change this list so that it displays all versions ever released, allowing you to 'downgrade'.

The versions are shown in the order in which they were released, with the most recent version up the top. The reason they look like they're out of order comes down to how the version numbers are generated:

year.month.day.issueNumber

Because we fix issue numbers in whatever order we feel like, it often appears as if your version is old. In this case, the second version in the list looks quite old but from the first three numbers you can see that it was released on 24 September 2019 so in fact it's not that old.

**Comment by sno036** [comment]
Thanks for the explanation Drew - I had assumed that the last number was some weird timestamp.
