### ISSUE TITLE
Summary file no longer rendering in html in the UI view

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#43]

**Comment by hol353** [comment]
The seem to work ok for me. Which simulation are you looking at?

**Comment by HamishBrownPFR** [comment]
All the simulations I look at on my computer and that I have looked at on Edmars are displaying the summary file in raw text

**Comment by zur003** [comment]
The summary view has quite a few problems. It seems to be very slow to load and draw initially; the current style looks very "raw" - possibly this is a style sheet issue (could that be the source of Hamish's issue?); backslashes in front of text "swallow" the following word (because it's now trying to parse RTF rather than HTML?), so file paths display as just the file extension.

**Comment by zur003** [comment]
Looks like things were changed to use RTF for display rather than HTML (hence avoiding the problem of finding a good HTML display engine). Is this what Hamish is describing? It certainly doesn't look as polished.

**Comment by hol353** [comment]
The HTML component has having all sorts of issues so we decided to ditch it in favour of something (simple RTF control) that would run on MONO as well. I suspect that Hamish is seeing that the tables of numbers are no longer HTML tables. This is because I didn't have the time to support tables.

BTW: I notice the font has changed to a proportional one. This upsets the formatting of tables. Can we put it back to the way it was?

**Comment by HamishBrownPFR** [comment]
This is what it looks like for me.  The summary file view stops scrolling part way down the file so you can't see all the contents

![image](https://cloud.githubusercontent.com/assets/7295858/7465146/920b1bda-f31f-11e4-8468-670aa208e2c0.png)
