### ISSUE TITLE
Releases are not being built

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4315]
There hasn't been a successful release build of APSIM for a while now. Need to fix this ASAP.

**Comment by lie112** [comment]
Any news on the fix for this?
I have users needing to implement the fixes and improvements I have done to CLEM.

**Comment by hol353** [comment]
I have removed the certificate signing from the releases. They are now being built again. My PR that was merged this morning worked and is now available as an upgrade for users. However, because the installation hasn't been signed, Cylance on CSIRO computers will stop the upgrade from downloading and users won't be able to upgrade. On AgResearch computers this doesn't seem to be a problem.

**Comment by jbrider** [comment]
@Dean Holzworth <dean.holzworth@csiro.au> Will that fix Apsim Classic
builds as well?

**Comment by hol353** [comment]
Nope. Just APSIM Next Gen.

**Comment by lie112** [comment]
Is there a way of getting the list of upgrades available that the user sees in their upgrade popup? I only have APSIM as a development version in Visual Studio so don't see the upgrade window. It's hard to tell the users what version of upgrade will include the fixes and changes they are after. This is especially true if an upgrade includes another resolved issue

**Comment by hol353** [comment]
Something like this:
http://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/GetUpgradesSinceVersion?version=2019.01.01.1

**Comment by hol430** [comment]
You can always just comment out the line of code which checks if you're using a development version - it should be somewhere in UpgradeView.cs I think. Then you can just click upgrade on your development build and the list of upgrades should show up. That's how I normally check.

**Comment by lie112** [comment]
I was wondering if we could allow the Upgrade popup in development version by default and simply disable of hide the Ok/Submit/Upgrade button and even display "Upgrade not available in Development version". It is useful to know what upgrade list your users are being presented with. My current crowd seems to be coming to grips with getting upgraded but never know which item to select. I think you mentioned if multiple issues are resolved at similar time they will be presented in the same upgrade rather than have an upgrade for every resolved issue.

**Comment by femiguez** [comment]
Is ApsimX being built for all platforms? For Debian, I have downloaded version 4236 back in October and when I requested this again today I receive 4118.

**Comment by hol430** [comment]
The final number in the version doesn't necessarily always increase. Whenever a pull request is merged, a new upgrade is generated. The final number in the version string comes directly from the issue which was fixed by the pull request. Yesterday, pull request #4507 was merged which fixed an old issue, #4118, causing a new upgrade with a final number 4118 to be generated.

The first three numbers (yyyy.mm.dd) are a better indication of the vintage of the apsim upgrade - they come from the date the pull request was merged.

**Comment by femiguez** [comment]
Thanks so much for the explanation Drew! I also received the Mac version which is 3010. Is this expected? I mean that the different platforms would have a different number when requested on the same date. Would this imply that the 3010 fixed a Mac specific issue? (Since it differs from the Debian number).

**Comment by hol430** [comment]
Odd...the latest version for all three platforms should always be the same. If they're not then that would probably be due to an issue in our CI system. Of course, there were a number of upgrades generated in quick succession yesterday and there are a few more being built right now so I guess it's possible that the latest version changed between you checking the Debian and macOS versions. If I check now, the [windows](http://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Windows) [MacOS](http://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Mac) and [Debian](http://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Debian) versions are all identical (3010).

**Comment by femiguez** [comment]
Probably there was a difference of 10 minutes between the Debian and Mac downloads, so that explains the difference. I guess I was not expecting it. Thank you so much again!

**Comment by hol430** [comment]
Closing this - it has been fixed.
