### ISSUE TITLE
Stock sometimes runs very slowly - why?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4332]
@her123 - working with @MarkLieffering on a simulation to compare some local data against Stock we are finding that Stock will sometimes run very slowly. There are four simulations in the attached. The first two run in about 3 seconds but the other two take 6 times as long - 18 sec. The difference in the status of the animals when they are bought. See the "BuyLactatingCows" script - the four simulations vary in the last two parameters on the UI and it seems that if the Stock are lactating when bought (pregnant or not) the simulation slows dramatically. 

Thoughts?  Any solution?

@APSIMInitiative/team-stock-forage-and-related-matters 

[SlowStockEvent.zip](https://github.com/APSIMInitiative/ApsimX/files/3812111/SlowStockEvent.zip)

**Comment by MarkLieffering** [comment]
Just after Val sent that issue, I was playing around with the simulation - I wasn't feeding the animals enough and I suspect that there were a bunch of calculations that were grinding away at this - when I fed them enough (actual reduced numbers) - the simulations went much faster. So I suspect that it has something to do with this - will close the issue.

**Comment by her123** [comment]
The main issue with this slow down is that when animals die the animal groups can get changed and there is some splitting and copying in the background. In C# this process is more difficult to achieve than in the original Pascal. 
At the root of this problem is ObjectCopier.Clone<T>(T source) (in graztype.cs). It serializes and deserializes some objects.
