### ISSUE TITLE
Documentation development needed

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4333]
- Need need need a way to break out of generating the documentation (escape, control+C)
- Would it be possible to right click on a component and have the option to exclude all components of the same name from documentation?
(I am trying to get the Lifecycle documentation down from 500 pages long)

**Comment by hol430** [comment]
> Need need need a way to break out of generating the documentation (escape, control+C)

Maybe a progress bar with a cancel button, similar to when we run simulations? Would be nice if creating autodocs didn't freeze up the UI as well.

> Would it be possible to right click on a component and have the option to exclude all components of the same name from documentation?

What is your use case here? Normally, removing a component from autodocs will also remove all descendant nodes as well. Would this new feature behave similarly and find all components of the same name and then remove them and their descendants from autodocs?

**Comment by sno036** [comment]
Yes to the first point.

My use case was over an hour trimming Jeremy Whish's Lifecycle documentation from 500 to 50 pages by excluding all the models that didn't need to be included. The kicker is that all it takes is 1 second of inattention or mouse-clumsiness near the top of the simulation tree and it is all undone with all 500 pages back!

**Comment by hol353** [comment]
I spent a few hours trying to put the auto-doc code on a thread so that it can be cancelled. The problem is that much of the code can only be run on the user interface thread because it requires the UI e.g. Map, Nutrient bubble diagram, graphs etc. In the end I gave up. Need to redesign chunks of the code to not need presenters and views.

**Comment by hol430** [comment]
Can't you just wrap the UI code in `Application.Invoke`?

**Comment by hol353** [comment]
I tried putting in code to run parts of it on the UI thread. This kinda worked but made the code messy. It was also a problem when run from the command line (i.e. what Jenkins does).

**Comment by hol430** [comment]
Well we could make the views responsible for ensuring that appropriate code runs on the UI thread. It is still messy of course (you may need to wait for the Gtk event loop to process its queued events?) but I'm not sure how you're going to render graphs, maps, images, etc without the frontend. That being said, maps may be possible to render without gtk - I've done some experimenting with a library called [SharpMap](https://github.com/SharpMap/SharpMap), and I was able to rewrite most of the map view to use SharpMap instead of the HTMLView. It's far more primitive than the current javascript implementation (zoom/position are only editable via property presenter currently) but if you only care about autodocs, I expect it will be a lot more reliable than the embedded browser widget.

If the views handle the "run on UI thread" logic, then I don't see command line runs posing a problem, as long as the entrypoint function has a `[STAThread]` attribute.

**Comment by hol353** [comment]
For documentation, graphs and maps should be able to be exported as an image without a view / presenter and images are just an instance of Bitmap class. I suspect it is possible to do the whole auto-doc without gtk and views/presenters. I'll keep investigating.

**Comment by hol353** [comment]
I don't have time to make big changes to the auto-doc but I will capture my thoughts here:

We should be able to get an image from a 'graph' instance somehow without needing GTK e.g.
```c#
Graph graphDescription = new Graph();
graphDescription.Series.Add(
    new Series()
    {
        Name = "Series",
        TableName = "Report",
        XFieldName = "Col1",
        YFieldName = "Col2"
    });
GraphRenderer renderer = new GraphRenderer(graphDescription);
Image img = renderer.ToImage();
```

The new GraphRenderer would be created by moving a lot of code from GraphView i.e. all the code that deals with a OxyPlot.PlotModel (which doesn't use GTK). The GraphRenderer essentially wraps an OxyPlot.PlotModel. If we ever want to change graph widgets we can do so more easily.

GraphView.cs would be much smaller, which is a good thing, and only deals with user interaction and an instance of OxyPlot.PlotView (which does use GTK). It will then be easy to call the GraphRenderer on a worker thread.

I think we should do the same for Maps. 

The views in the GUI are generally too big and contain too much logic which hinders flexibility.
