### ISSUE TITLE
Intellisense not working in functions

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4414]
Intellisense is not working in any presenter that allows the user to type the address of a variable. e.g. in sorghum model/stem/criticalNconc is an interpolation function based on [Phenology].Stage.  When typing this address, focus is lost once the "." is pressed.  the same happens in variablereference functions.

**Comment by peter-devoil** [comment]
Would it be very hard to add function arguments to the intellisense popup? eg [Wheat].Sow(_double density, ..._

**Comment by hol430** [comment]
This should already work in a manager script context. Unsure about other areas - which view/component do you need it for?

**Comment by peter-devoil** [comment]
Ah. They do indeed, well done. I was trying to use an Operations component.

**Comment by hol430** [comment]
@zur003 I've looked into this and the problem seems to be related to the HTMLView. We've recently modified the property presenter to show a HTMLView containing the model description above the GridView. There seems to be some code in the HTMLView which messes with the focus of the main window. I'm not sure on the exact details but this code seems to somehow steal focus from the intellisense popup which is designed to disappear as soon as it loses focus. If I comment out the code in the `MainWindow_SetFocus` method, the problem disappears, but I'd rather not do this without knowing a bit more about the problem this code is trying to solve. Do you remember how to reproduce the problem that this code is trying to fix?

```csharp
/// UGH! Once the browser control gets keyboard focus, it doesn't relinquish it to 
/// other controls. It's actually a COM object, I guess, and running
/// with a different message loop, and probably in a different thread. 
/// 
/// Well, this hack works, more or less.
if (vbox2.Toplevel is Window)
    (vbox2.Toplevel as Window).SetFocus += MainWindow_SetFocus;

...

private void MainWindow_SetFocus(object o, SetFocusArgs args)
{
    if (MasterView.MainWindow != null)
        MasterView.MainWindow.Focus(0);
}
```

**Comment by zur003** [comment]
@hol430 - I don't recall the details. I think there was initially problems with keyboard control of the embedded browser (scrolling with arrow keys, copy and paste). Capturing focus was a hack that got things working.

**Comment by zur003** [comment]
No, I don't really remember what the problem was. Feel free to change it; I've tried it and didn't notice any problems.

**Comment by hol430** [comment]
There's a problem with the memo component if I remove this workaround; I can't edit the text in the text editor after selecting text in the HTMLView beneath it (browser seems to steal focus as per the comment). Will have a closer look at this when I get the chance.
