### ISSUE TITLE
System.TypeLoadException: Method 'AddView' in type 'APSIMRunner.StorageViaSockets' from assembly 'APSIMRunner

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4478]
I get an error when using multi-process job runner on Eucalyptus test set.
System.Exception: 
Unhandled Exception: System.TypeLoadException: Method 'AddView' in type 'APSIMRunner.StorageViaSockets' from assembly 'APSIMRunner, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at APSIMRunner.Program.Main(String[] args)

Testing suggests this may be due to the commit "Implemented new IDataStore and IDataReader interface"

**Comment by hol430** [comment]
@hut104 can you try and do a rebuild all of the entire solution. I suspect your problem may be due to the APSIMRunner project not being rebuilt after you pulled down changes to that project (no other project lists APSIMRunner as a dependency).

**Comment by hol430** [comment]
The problem here is that APSIMRunner has a dependency on the Models project, so whenever Models changes, APSIMRunner will be rebuilt. I'm guessing that when Neil did a git pull a few days ago, APSIMRunner changed but Models did not change. Neil would have run ApsimNG, which doesn't reference APSIMRunner, so APSIMRunner would not have been rebuilt automatically, leading to an error when running simulations with the multi-process job runner.

The obvious solution would be to add a reference to APSIMRunner in the Models project but doing this would create a cyclic dependency, because APSIMRunner already has a reference to Models. @hol353 any thoughts? I'm not sure there is a good solution here and it's probably not a huge problem. APSIMRunner rarely changes, and Models frequently changes.

**Comment by hol430** [comment]
Closing this after discussion with @hol353.
