### ISSUE TITLE
Database extension used for datastore

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4529]
Does APSIM only use SQLite to write output data to dataStore or is the FireBird database used for this task on some systems? I was wondering why .db was selected as the database extension for the main datastore. We are using other software to analyse the database (SQL query builders etc) and they assume .sdb or .sqlite for this type of database. At present we require an additional step to rename the extension before using the files in some applications. 
Any thoughts of switching the the standard sqlite extensions for the main datastore?

**Comment by jbrider** [comment]
It's a common extension for SQLite to be saved in, so it's surprising your
analytical tool isn't allowing for it?
Even more surprising is that it requires it to be renamed in order to read
it.

Having said that I'm not against using sqlite as an extension.

**Comment by lie112** [comment]
I must admit it is just one free Query builder for SQLite and they limit the extensions in their open database dialog.

**Comment by zur003** [comment]
Firebird is not currently being used anywhere as the datastore. It has potential to provide a way to quickly shift between a local database and a client/server architecture (so, for example, multiple Apsim runs on Condor nodes could all store results in a single destination), and should theoretically do a better job of handling multiple threads, but I never got it to the point where I was really happy with it.

It could be removed from ApsimX (meaning a few less DLLs to distribute), and no-one would notice. It's there because we might want to make use of it some day, and we didn't want to discard the work that has already gone into it.

**Comment by hol353** [comment]
.db is a common extension for SQLite. Let's leave it as it is.
