### ISSUE TITLE
Sugar Example has Nutrient component in soil

### ISSUE THREAD

**Issue by DavidJohnston491** [APSIMInitiative/ApsimX#4572]
I am trying to set up a simulation including both maize and sugarcane. The sugarcane example in APSIMX 2019.12.3.4449 has a soil subcomponent of Nutrient.  It is not in the models list to add.
Is it required for sugarcane, or not?

**Comment by hol430** [comment]
The nutrient model isn't officially released so I guess it probably shouldn't be in any of the examples. That said, I doubt it's required - you should be able to use SoilN instead (disclaimer: I haven't tested this).

**Comment by mpandreucci** [comment]
Hi David.
I had to put the SoilN into one of the soils I recently downloaded from APSIM (I deleted the Nutrient node). I was having trouble because I didn't have the solute nodes that need to be added in the soil file (otherwise the crop doesn't get any N). So make sure this is checked. Not sure if this helps you, I hope it does.
Regards,
Mariana

**Comment by hol353** [comment]
We are in the process of replacing SoilNitrogen with Nutrient in all simulations in Examples (and elsewhere). Having Nutrient in Sugarcane is what we want. For me, when I right click on Soil and go 'Add model' I can see the option for adding both Nutrient and Soil Nitrogen models. This is OK for now. 

So as far as I can tell, there isn't a problem. I'm closing this issue. Reopen if you still think there is a problem.
