### ISSUE TITLE
Caliberation of APSIM for Maize and estimation of plant height

### ISSUE THREAD

**Issue by rahulrajias** [APSIMInitiative/ApsimX#4681]
Hi, 
1. Does APSIM need calibration with local farm data before implementation on a farm? If yes, then how to calibrate it? Is there detailed instruction for this?
2. I am trying to estimate canopy Height and LAI of maize crop. When I run the model, I see extream underestimation of canopy height. Is APSIM not a good option to estimate crop height?

**Comment by hol430** [comment]
@hut104 are you able to answer this one?

**Comment by Afiasarwar** [comment]
hello Rahul!
yes APSIM need caliberation for local farm.For caliberation you need meteoroligical data of your site Crop management data and soil data.Feed the model with all of this data and then by hit and trial method of cultivar specific parametrs  you will caliberate our model.
for question nmber 2 you can adjust height of your palnt by changing parametrs in ini file.these two parametrs are used to adjust height of the plant.
<x_stem_wt units>  <y_height units>

**Comment by hut104** [comment]
Hi,
Calibration is best undertaken in the following order
1) Phenology - fit photoperiod response for the inductive phase to floral initiation
2) Most growth parameters otherwise should be mostly OK (they seem conservative between varieties) but you can check against data on leaf appearance, LAI and growth of organs.
3) Calibrate soil water holding parameters to get water stress responses and soil organic matter pools for nitrogen stress responses.

The height model in APSIM Next Generation is a simple model in which height (mm) is a function of growth stage
You can change this for each cultivar as has been done in calibrating the model on data from Wageningen for cultivar "Atrium"
                "[Structure].HeightModel.PotentialHeight.XYPairs.X = 3, 4, 5, 6",
                "[Structure].HeightModel.PotentialHeight.XYPairs.Y = 20, 40, 50, 2370"
