### ISSUE TITLE
Graph results change with more than one experiment in a simulation in AgPasture

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#4746]
When we have more than one Experiment in a simulation, every time we run one of the experiments, the graph results are also displayed in the graph of the experiment that wasn't run. 
FOr example, if I run Experiment 1 and then Experiment 2, the results from the obs x pred graph of Experiment 2 are displayed in the obs x pred graph from Experiment 1.

**Comment by hol430** [comment]
@mpandreucci I'm also unable to reproduce this one...I tried with a custom setup and then again with the agpasture example. Which file are you seeing this in?

**Comment by mpandreucci** [comment]
Hi Drew. 
I have a simulation where I have multiple folders, each with an experiment, factors, composite factors and a simulation. I'll put the simulation in the AgPasture folder so that you can see it

**Comment by mpandreucci** [comment]
[CompetitionTestValidation.zip](https://github.com/APSIMInitiative/ApsimX/files/4277839/CompetitionTestValidation.zip)

**Comment by hol430** [comment]
Hi Mariana, looks like the problem is that you have two experiments with the same name and treatments. Normally you're not allowed to have duplicate simulation names, but there appears to be a bug where it doesn't properly consider experiments' simulation names. So the short answer is if you change an experiment name then your graphs should work better.

I also notice that these simulations are running really slowly...on closer inspection it looks like you're getting divide by zero errors on every day of the simulation from the DoReporting manager script in the Comp_Validation folder's radcliffe experiment, on line 208 (`harvestReport.DoOutput`). The problematic variable in the harvest report is:

```
([AGPWhiteClover].StolonWt / [AGPWhiteClover].HarvestedWt + 1)
```

So I guess `HarvestedWt` is zero sometimes...possibly because it hasn't been harvested? I don't know much about the simulation setup here. These divide by zero errors are being thrown on every day of the simulation but are being hidden, although I suspect they should be logged as warnings in the summary file. Either way, they're really slowing down your simulation.

**Comment by mpandreucci** [comment]
Thanks for that Drew. I'll change that. This simulation was just built to do some tests, so not something that is really important.
In relation to the dividing by zero problem, I thought that adding 1 (HarvestedWt+1) would fix this? Not sure why this isn't working.
Also, the harvest report should be working only for when there is a harvest (theoretically shouldn't report the days that there isn't a harvest). I'll have to look at the manager that controls this. I didn't write it so hopefully I can find what is going on.

Thanks a lot for that Drew

**Comment by hol430** [comment]
Well I think our expression parser respects the order of operations, meaning the division will occur before the addition.

**Comment by mpandreucci** [comment]
Oh, of course!!!
Sorry for that Drew!
I'll fix that. Thanks a lot.
