### ISSUE TITLE
APSIM looks for removed soil layers

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#4873]
In the following simulation, I removed 5 bottom layers from soil profile, but APSIM still looks for those layers when I 'Check Soil'. Initial soil water is also strange. I think the problem is that I have not removed the whole table and missed a few already-empty cells. I think APSIM should ignore a row if nothing is on it.

[TemplateNG20112012 2020.03.10.zip](https://github.com/APSIMInitiative/ApsimX/files/4309759/TemplateNG20112012.2020.03.10.zip)

```
OC value missing in layer 3
OC value missing in layer 4
OC value missing in layer 5
OC value missing in layer 6
OC value missing in layer 7
```

**Comment by hol430** [comment]
When you want to delete a layer, you need to select every cell in the row by shift clicking and then hit delete. Otherwise, you'll end up with something looking like this (note all the empty rows):

![image](https://user-images.githubusercontent.com/36427516/76272024-ea777c80-62c5-11ea-85ba-9a6641b2f676.png)

Ideally the gui would realise when there's nothing left in a row and delete that row - I'll see what I can do.

**Comment by hol430** [comment]
Hi Ben, in #4880 I've implemented automatic empty row detection/deletion which triggers whenever you click away from the profile view. Once merged, you should be able to just click around your soil nodes such as physical/soilwater/initialN/etc and they should fix themselves up. Let me know if it gives you any problems.
