### ISSUE TITLE
Export of met and soil input data 

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#5010]
For some purposes it would be useful to have an option to export met and soil data in a spreadsheet format, e.g. .csv or .xlsx. Maybe others would also like to export other inputs. We have export options for outputs, but not yet for inputs as far as I can see, apart from as a summary file as text or printed. It would be appreciated if our option for this could be expanded.

**Comment by hol430** [comment]
I'm not sure how met data would look in a .csv file (how do you specify tav/amp/latitude/etc?) but an export to Excel (.xlsx) should be possible.

What sort of soil data do you want in your excel file? How would it be formatted? Are you just talking about the profile grid, or do you want the other properties as well?

**Comment by hol353** [comment]
There is already c# code somewhere that imports/exports soil data to a spreadsheet.

**Comment by hol430** [comment]
@hol353 any idea where this code lives or where it's used?

**Comment by hol353** [comment]
In APSIM Classic there is this class:

Model\ApsimFile\Soil\SoilDataTable.cs

This can import and export soils from/to 'standard' APSoil ssheet format. I used the import code of this just recently. Files are here:
[SoilsDataTable.zip](https://github.com/APSIMInitiative/ApsimX/files/4472168/SoilsDataTable.zip)

**Comment by sme016** [comment]
Using APSoil is a good idea, but I can't test APSIMx two-way compatibility. 

I can export a .soil file from APSoil, but I can't paste it into an APSIMx simulation as I receive the error message:
System.Exception: Silt (BARI-05 No663)1: Unable to find soil temperature child model
   at Models.Soils.Soil.FindChildren()
   at Models.Core.ApsimFile.Structure.Add(IModel modelToAdd, IModel parent)
   at Models.Core.ApsimFile.Structure.Add(String st, IModel parent)
   at UserInterface.Commands.AddModelCommand.Do(CommandHistory commandHistory)

Also, APSIMx does not offer an option that I can see to load or export a .soil file.

**Comment by hol353** [comment]
You should be able to copy and paste a soil from APSoil into APSIM Next Gen but not the other way around.

Going back to the original comment box at the top, why can't you just output weather and soil data in report and then export the datastore to csv files?

**Comment by sme016** [comment]
1. When copying an APSoil to APSIM Next Gen I receive this error message:
System.Exception: Grey Vertosol (Rolleston No106): Unable to find soil temperature child model
   at Models.Soils.Soil.FindChildren()
   at Models.Core.ApsimFile.Structure.Add(IModel modelToAdd, IModel parent)
   at Models.Core.ApsimFile.Structure.Add(String st, IModel parent)
   at UserInterface.Commands.AddModelCommand.Do(CommandHistory commandHistory)

It would be good to go the other way too if that option was available.

2. Yes - doing a soil <initial> report would work. Can a complete soil report be put in Examples, please. It could take a lot longer and more questions if I did it, as yesterday, for example, I tried to output a temporal trend in soil C (%), but I couldn't select the correct variable to report (several were just not reported) and I didn't receive an error message. For example, the one I remember was [Soil].SoilOrganicMatter.Carbon[1]. Eventually I made do with a kgpha option that I found. So knowing how to report particularly soil variables can be tricky.

**Comment by hol430** [comment]
This code from apsim classic is not going to work due to things having been moved/rearranged in Next Gen. E.g. properties like SummerU are not part of the ISoilWater interface but are implementation-specific - they don't exist in SWIM, for example.

Re met data - Excel should already be able to read met files ok so I'm not sure what is needed here exactly.

**Comment by sme016** [comment]
I agree - drop the need for met file output.

**Comment by JJguri** [comment]
I am trying to get the initial soil carbon in sorghum sims NG using an Initial report and the following codes:  `[Soil].Organic.Carbon` and for the sum: `(sum([Soil].Organic.Carbon)) as TotalOC`. For some reason, it is not exported as an output.

**Comment by hol430** [comment]
Setting the reporting event to [Clock].StartOfSimulation doesn't work for me. This is probably a bug, I'll look into it. In the meantime, you may need to change your reporting event if you were using StartOfSimulation. One option might be to use the start date in the format yyyy-MM-dd.

Other problem is that `[Soil].Organic.Carbon` is set to null. Unsure if this is a bug or not, I'm not really sure how all of the soil infrastructure is supposed to work. What works for me is `sum([Soil].Initial.OC) as TotalOC`.

![image](https://user-images.githubusercontent.com/36427516/89368033-e25d2500-d71d-11ea-9a7a-eb1ae74e16fd.png)

**Comment by JJguri** [comment]
I am using the new date format as suggested. I cannot put an exact date because of the start of the simulation change between sims. Interestingly, I cannot get TotalOC as output after the change. Maybe its because I do not have the node `Initial` in the soil.
![Untitled](https://user-images.githubusercontent.com/41041705/89368993-3ff27100-d720-11ea-92da-ab7b5a30e2fd.jpg)

**Comment by hol430** [comment]
Strange, it works for me in a soil with no Initial node. Could you upload your .apsimx file? Also, you can change the colour/style of the text editor by right clicking in the text area -> use style

**Comment by JJguri** [comment]
Thanks @hol430 , I already set up Oblivion. Here is the apsimx file.
[Sorghum_V6.zip](https://github.com/APSIMInitiative/ApsimX/files/5026430/Sorghum_V6.zip)

**Comment by hol430** [comment]
Hi @JJguri, I notice that quite quite a few of your simulations (all of the ones I checked anyway) have the same date for start date and sowing date. You could set the reporting frequency to `[Sorghum].Sowing`. It's not ideal - I'll see about fixing this so that `[Clock].StartOfSimulation` works - but it does work for me with your file:

![image](https://user-images.githubusercontent.com/36427516/89473095-65858600-d7c5-11ea-9cd9-c6df42591a04.png)

![image](https://user-images.githubusercontent.com/36427516/89473110-6dddc100-d7c5-11ea-8871-a7e0264a357f.png)

**Comment by JJguri** [comment]
Thanks @hol430 it is working now. The StartOfSimulation is the same but the sowing date changes between sims.
