### ISSUE TITLE
Root activity must not use RootProportionInLayer 

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#5076]
Proportion of the last soil layer through which root has penetrated is already accounted for when calculating water uptake.

**Comment by HamishBrownPFR** [comment]
@BenAbabaei  can you provide some more info.  Where is  the other place the proportion of penetration through the layer is accounted for?

**Comment by BenAbabaei** [comment]
Hi @HamishBrownPFR . I tracked the code and in my understanding, potential water supply is first calculated by Root.CalculateWaterSupply. it is then scaled down with supply/demand and becomes actual water uptake. In CalculateWaterSupply, there is RootProportions which, for the default setting, is calculated with soil.ProportionThroughLayer, while soil.ProportionThroughLayer is also used in Root.CalculateWaterSupply.

**Comment by HamishBrownPFR** [comment]
@BenAbabaei , it is not a problem that ProporionThroughLayer is called twice because it  each call is doing different things.  In Root.CalculateWater Supply it is used to scale back the potential extraction in the lowermost rooted layer to account for partial exploration of that layer by the roots.  This is intended.  The  CalculateRootActivityValues is used to calculate where root activity is most active to determine priorities for biomass partitioning throughout the root profile.  This is having no direct impact on the calculation of Water supply so it not double accounting.  

@hol353  I may be misunderstanding the issue but I don't think the proposed change is correct.  @BenAbabaei  please reply with further justification it you think I have this wrong.

**Comment by BenAbabaei** [comment]
It depends how the code was intended to work. I believe the 'contribution/weight' of each layer when determining priorities for biomass partitioningis is already accounted for when WaterUptake was calculated. I would even remove **soil.Thickness**. 

This is all I got. Please feel free to close to issue if you are not convinced this change is needed.

**Comment by HamishBrownPFR** [comment]
@BenAbabaei , I think you are misunderstanding the intent of the rootActivity factor.  It is used to create a weighted relative activity of roots in each layer which is used inturn to partition most biomass to the layers that are currently giving the greatest water uptake per g of root mass (invest where return is greatest).  The thickness of the layer and proportion of root exploration need to be accounted for in this to normalize for the relative depth contribution of that slice of roots.

I don't want to close your pull request if you still think the code is incorrect, it is quite possible I am wrong.   I will leave it to you to come back with further discussion or close it if you wish.

**Comment by BenAbabaei** [comment]
@HamishBrownPFR Thanks for the clear explanation. I now understand that root activity is for each **unit length** of each slice/layer, not the whole slice. I appreciate your time. Cheers.
