### ISSUE TITLE
Revise git/github usage documentation

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#5106]
- APSIM.Shared is no longer required
- Replace sourcetree screenshots/terminology with git fork equivalents

**Comment by hol430** [comment]
@hut104 @hol353 - git fork costs money. Do we really want to encourage people to shell out $50 just to contribute to apsim? Especially when there are plenty of [free alternatives](https://git-scm.com/downloads/guis).

**Comment by lie112** [comment]
I use SourceTree. It works if you treat it well and only have general git requirements. Its a good step to learning to use git in the APSIM world. There does need to be good info on the pull from APSIM Git repo steps for new users.

**Comment by jbrider** [comment]
For the amount I use it, it's cheap at that price.
I've tried at least 5 of the others listed and Fork has been more usable
and stable than others by a fair margin.
Working across operating systems doesn't hurt either.

There's nothing stopping them from using any of those others - perhaps we
should just give a recommendation with the link to free ones.

**Comment by zur003** [comment]
Just show them a git command line.

**Comment by hol353** [comment]
Are Fork and SourceTree still sufficiently similar that we can have instructions for one and it applies to the other as well?

**Comment by hol430** [comment]
I've just used Fork to follow our instructions for using sourcetree and there are some differences which I think could trip up new users who haven't used git before. In sourcetree, a lot of your options are accessible through the Repository -> Repository Settings button. In fork, that button doesn't give you many options, and a lot of the functionality seems to be available via right click context menus. Even something as simple as adding a new remote is quite different between the two. Also worth noting that Fork doesn't appear to have translations available.

$50 is probably a fair price for a programmer using this program every day but for a model builder who only uses git to occasionally push changes to their prototype model, I don't know that Fork provides anything that you can't do with another package. Not that I use either on a regular basis.

@lie112 which info in particular do you think we need to expand upon?

**Comment by lie112** [comment]
I'm always open to the best method to use and would pay if it makes life easier. 
I should have a look at git in VS for APSIM too. I know for my other solutions I use git to store to my personal VS and CSIRO git repositories through the team explorer and it is pretty simple.
I guess the biggest issue is the learning curve for anyone needing to move to source control which I have now been through. I know other programmers who still steer clear because of the learning curve and the fact they don't need to work in a team. The question is what level of understanding are new users going to have and what is APSIM responsibility and what can be read by searching google and how many people is this needed for.
I would say the most useful info would be a short description of the overview of git and APSIM. Just the difference between push and pull changes depending upon your vantage point.
So either articles online or our own to get people up to speed on
1. using git to 
a access apsim code
b store in your own repo and branching (I'm still a trunk developer I must admit and branches confuse the situation)
2. Pulling from APSIM via the git apsim web page
a what jenkins does
b how to address jenkins errors
3 etiquette for creating issues and pull requests 

The bespoke info is actually APSIM rules and regs (coding style, commented code etc, should we have a VS code style?), linking issues to pull requests and working with Jenkins (when to retest), how to find errors and how to implement validation. Just what can be changed and what needs to be discussed through issues. Can you combine working into one pull, or should we have an issue for each change to the code. I have tended to use the first approach when doing mass development and multiple fixes on CLEM,

**Comment by hol430** [comment]
Well we already have [documentation](https://apsimnextgeneration.netlify.app/development/contribute/sourcetree/) covering most of these points. Which bespoke info are you referring to?

**Comment by lie112** [comment]
I hadn't got to see the new documentation. Great. That would have helped me get up to speed.
