### ISSUE TITLE
Refactor the model resource handling code.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5118]
We need to rethink how models are deserialised from resource files. Currently models that can be deserialised from a resource must inherit from 'ModelCollectionFromResource'. This isn't a good use for inheritance.

Instead, let's have a new class (called ModelResources?) that manages all interaction with the resources in Models.exe

1. Resource files can be put in sub directories under Models.Resources like the stock genotypes are now.

2. `IModel CreateInstance(ModelDescription metadata)`. This will create an instance of a model given model metadata. The resource name in the metadata can be a full path ("Models.Resources.Wheat.json") or a model name ("Wheat") which is searched for. The class _ModelDescription_ is already defined in Apsim.cs and should be moved to this class. Perhaps _ModelDescription_ should be renamed to _ModelMetaData_? 

3. `IEnumerable<ModelDescription> AllResources()`. This will return an enumeration of all resources. There is already code to do this in Apsim.cs that can be moved to this class. ModelDescription.ResourceName should always be a full path. This method can then be called by AddModelPresenter.cs to display a hierarchical tree of model resources.

4. Stop models inheriting from ModelCollectionFromResource. This will mean any model can be created from a resource file if we want to.

5. Add a new property to Model.cs called ResourceName.

6. Once an .apsimx file has been deserialised, there will need to be a method somewhere that goes through all deserialised models. If it finds a non-null Model.ResourceName it will call CreateInstance above and copy properties and children from the model returned by CreateInstance into the model from the .apsimx file. This is what ModelCollectionFromResource.OnCreated currently does.

7. Write unit tests for new functionality.

This should remove a lot of code from AddModelPresenter.cs. 

I'm open to suggestions, improvements or other designs.

**Comment by hol353** [comment]
8. `void UpdateResources()`. This will update the resource files on disk to the latest version. The GUI can then call this when the user clicks 'Convert files'. No need to ask the user where the resource files are located. That code can be removed.

**Comment by lie112** [comment]
I didn't know about resource files. Is there a description of how they work? How do you include one (e.g. Wheat) in your simulation, or are they provided in the toolboxes? Do they provide the user with a parameterised model (json) to include via cut and paste? We were thinking we had to provide a parameterised list of example models in an apsimx file for users (e.g. ruminant breeds). Are toolboxes dynamically created or supplied as a json file? If dynamic, how do you specify the tree structure used to store the examples in?

**Comment by HamishBrownPFR** [comment]
It will be good to automate the updating of resources.  Now that the stock resources have been added in folders you have to navigate into 6 folders to find all the resources to updata, easy to miss some

**Comment by jbrider** [comment]
sounds good.

**Comment by hol430** [comment]
Hi @lie112, I must have missed your comment the other day. Like much of the internal workings of apsim, there's little to no documentation to be found, so the only way to see what's really going on is to look at the code.

The reason the resource models were introduced was because the full wheat model (and other models too) is quite large. If you've got an .apsimx file with a couple dozen simulations with wheat in it, you're going to end up with a couple dozen identical copies of the released wheat model. To get around this, we embed the wheat json into Models.exe, and we just serialize a very small object to the .apsimx file which basically just points to the embedded resource. When you run a simulation, the small version of wheat is replaced with the full model which is deserialized from the json stored as an embedded resource.

To include one in your simulation, you can right click on a paddock and click add model, then select wheat from the menu. Like any apsim model, they can be copied and pasted in the gui. I think some plant models are included in toolboxes, but the general direction seems to be one of moving away from toolboxes. Toolboxes are not generated dynamically, they are basically just .apsimx files stored as embedded resources inside ApsimNG.exe (have a look under ApsimX/ApsimNG/Resources/Toolboxes). To provide your ruminant breeds, the resource models sound like the way to go.
