### ISSUE TITLE
Graph legends don't appear as expected

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#5153]
When using multiple graphs on one view the legends don't show up until you click on them with the mouse. Noticed on Mac and Windows.
![image](https://user-images.githubusercontent.com/11879671/81768262-dea27380-951d-11ea-9ad9-eb3d274f9e3a.png)

**Comment by hol430** [comment]
It appears this is deliberate - see #510. @HamishBrownPFR @hol353 do you recall why this was implemented?

**Comment by her123** [comment]
Interesting

**Comment by hol353** [comment]
I think it was because often there isn't space for the legends in the autodoc and the full page of graphs in the GUI. Some of the validation graphs have very large legends. I  guess we now have the ability to turn legends on/off (didn't previously) so perhaps we can honour that setting and see how it looks.

**Comment by her123** [comment]
I can see that the legends could be a nuisance. May be good to use a setting to turn them on/off.
