### ISSUE TITLE
Huge name of factorial simulation when using the weather file as a factorial

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#5186]
When a factorial simulation is done using the weather file as factorial as 
[Weather].FileName=C:\blabla\blablabla.met
you end up with a simulation name of 
ExperimentFactorC:\blabla\blablabla.met
Not ideal to build the observed data file where the name of the simulation needs to match this.

For now we can avoid this by using the weather as a node in the factor but I guess it would be better if we could change this?
Thanks,
Mariana

**Comment by hol430** [comment]
We can change this behaviour, but what should we change it to? We could check if the factor value points to a file on disk, and then change the simulation name to contain the file name without path or extension but this could lead to duplicate simulation names. It would also mean the simulation names could be different on different people's computers.

**Comment by mpandreucci** [comment]
This might be a very silly question (apologies) but couldn't we just keep the name of the simulation as 
'ExperimentFactor' , just without the file path?

**Comment by hol430** [comment]
You could do that, but if your factor specifies multiple met files, then you'd end up with multiple simulations all called "ExperimentFactor".

![image](https://user-images.githubusercontent.com/36427516/82517565-bab7e100-9b60-11ea-91f9-4c17bc2cabb3.png)

**Comment by hol353** [comment]
Maybe we do a special case where if the left side of the equals sign is FileName then the name of the simulation will have the name of the file without path or extension (e.g. Dalby).

**Comment by hol430** [comment]
That seems pretty fragile, it won't work if the property we're modifying isn't called FileName - e.g. if the user decides to change `[Weather].FullFileName` instead of `[Weather].FileName`. That said, I don't really have a better suggestion. Maybe we could look for a file name if the property has a display attribute with `[Display(Type = DisplayType.FileName)]` but again this will still have all of the issues I mentioned earlier.

Perhaps apsim is doing the right thing here, and if the user wants more control over the simulation names, they should use the composite factor approach? It doesn't actually require you to dump a whole weather node on there, you can just specify the path:

![image](https://user-images.githubusercontent.com/36427516/82523516-d1196900-9b6f-11ea-816e-c446d07f9b4d.png)

**Comment by mpandreucci** [comment]
Yeah and that’s an easy way of doing it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hol430** [comment]
Closing this one, as the compound factors already allow for finer control over individual simulation names, unless anyone can think of a better way of doing things.
