### ISSUE TITLE
FOM, FBiom, FInert and SoilCNRatio report

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#5198]
I created a long-term simulation in APSIMX to get some soil initial values to start another simulation. I cannot get the FOM (kg ha-1), FBiom (0-1), FInert (0-1) and SoilCNRatio (g g-1) values. I tried the following scripts (example for FInert) but it provided me the initial values set in the Organic module however I want the values at the end of the long-term simulation.

Soil.FInert
Soil.Organic.FInert
SurfaceOrganicMatter.FInert
Soil.SoilNitrogen.FInert

**Comment by hol430** [comment]
@rcichota do you know where these variables live?

**Comment by rcichota** [comment]
Things have changed a bit since the introduction of *Nutrient*, which I assume is what you're using (*SoilNitrogen* can still be used, but no longer is the default).  The values of the fractions are now only used in the initialisation, if you want them at any other time you can compute them using the amounts:
```[Soil].Nutrient.Microbial.C / ([Soil].Nutrient.Humic.C + [Soil].Nutrient.Inert.C + [Soil].Nutrient.Microbial.C) as FBiom```
```[Soil].Nutrient.Inert.C / ([Soil].Nutrient.Humic.C + [Soil].Nutrient.Inert.C) as FInert```
Important to note that FInert never changes during the simulation, unless the amount in Inert is deliberately changed (say using a manager script), in Apsim the inert is really inert.
The values for FOM (I assume you mean dry matter weight of FOM) are no longer used, but you can compute using:
```[Soil].Nutrient.FOMC / 0.4 as FOM```
And SoilCNRatio took the same fate, disappeared. This was done because now each pool in the soil is its own model (with its own CN), and very few soil-encompassing variables have remained (which follows the developments done in Plant PMF). Again you can compute SoilCNRatio by:
```([Soil].Nutrient.Humic.C + [Soil].Nutrient.Inert.C) / ([Soil].Nutrient.Humic.N + [Soil].Nutrient.Inert.N) as SoilCNRatio```

**Comment by JJguri** [comment]
Thanks @rcichota !, I will be working on that next week. It helps me a lot to understand where this variables are located. We are creating sorghum simulations. I was using Soil Nitrogen due to it was as default in the Sorghum model which is under review.  So I can shift to Nutrients to get these variables from the code you described.

**Comment by KoldaEFK** [comment]
Thank you very much for the explanation, it was helpful! However, it seems to me that FBiom is defined as `[Soil].Nutrient.Microbial.C / ([Soil].Nutrient.Humic.C + [Soil].Nutrient.Microbial.C)`, without including the `[Soil].Nutrient.Inert.C`.
