### ISSUE TITLE
Digestibility in PMF

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5218]
There are negative digestibility values coming from PMF, specifically the Plantain model but I suspect all models. This causes problems with SimpleGrazing and probably Stock.

The crop modellers would also like to remove digestibility out of PMF as it is as much to do with the animal as it is with the plant. Any suggestions where it should live?

**Comment by her123** [comment]
You are right that they are dependant on both the herbage and the consumer. In a model that is meant to be generalised like APSIM it would not be strictly correct to have these values in one or the other. We could put them into an obscure parameter file somewhere in the bowels of the system. Maybe we could to think about some sort of 'layer' or host that goes between the provider and consumer. It may be asking a bit much for the consumer to contain an infinite list of possible herbages. The digestibilities of the herbage is also very reliant on the stage and conditions that the herbage is under.

**Comment by zur003** [comment]
I think the ideal thing would be for the PMF model to provide values for things like protein content or structural and non-structural carbohydrates. Then the consumers could work out how digestible the material is (what is digestible to a ruminant might not be so digestible for a non-ruminant). Unfortunately, making that work would probably require a lot of modelling effort on both the plant and consumer sides. How much of that sort of detail is currently available from the PMF models?

**Comment by hut104** [comment]
I agree with Eric.  I think we make the move and start using the structural/non-structural components of the model.  We could use both the N and DM components of these.

PMF has structural, non-structural and metabolic DM and N for each organ.  This is the case for live and dead biomass.  It would be interesting to give it a go, and would be a real win if we could have plant models actually providing what the animal models require.

**Comment by her123** [comment]
Currently stock is assuming storage and metabolic are 100% digestible and it's only getting the dmd of structural.

**Comment by rcichota** [comment]
I agree with Neil and Eric. Taking Metabolic and Storage as highly digestible while Structural having low digestibility seem sensible to start with. I'd bet this approach could be used to link to decomposition of organic mater in surface and soil. Probably the pools should align, for consistency.  
The actual values of digestibility would vary for different species (not sure our current balance of structural/non-structural pools are validated for this use), and likely for different ages of the organ. As the plant grows the organs have more cellulose and then lignin (would we have to split Structural into two to account for cellulose and lignin separately, probably later on). Not sure how we could account for age, which could be important for plants grazed under different rotation lengths...
AgPasture computes digestibility based on simple two pools approach...

**Comment by HamishBrownPFR** [comment]
I would very much like to see digestibility removed from plants and have animals work out how digestible based on there composition.  The problem we will run into is there are many organs that have not been parameterised with digestability in mind.  Most crops only have metabolic biomass in the leaf, some organs have all their biomass in structural to make parameter fitting easier even thought this is not realistic.  For instance, grain is all structural!  This is done because structual is given higher priority in partitioning.  We have a better partitioning method implemented now that would allow storage to be given a higher priority so we can achieve more realistic partitioning.  It would be a big job to implement this for all existing crops.  
I propose we remove stock from APSIM and make life simple again :-).  Now seriously, it might be a good idea to start with a stock take of how each of the crops are parameterised for partitioning of DM into Storage, Metabolic and Structural.  Then the issue would be how to fix those with setups that are not appropriate for stock consumption.  This might be a good one for reference pannel to pick up and work out how AI members can combine resource and skill to tick this off.

**Comment by hol353** [comment]
Tagging @APSIMInitiative/livestock-and-forages

**Comment by Keith-Pembleton** [comment]
I agree digestibility is animal specific so should be in the animal, but the plant needs to provide the required information to the animal to work it out.  Looking at just the structural and non-structural components to determine digestibility is a bit simplistic.  How the structural components are laid down and their composition is very important.  I think APSIM tries to capture that a little bit with age but we should aim to do better.

**Comment by hol353** [comment]
This issue is the same as #6258. Closing.
