### ISSUE TITLE
Reporting of variables stops during run

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#5298]
Some variables stop reporting during the run filling the remaining cells with zero or blank.
Screenshots of report properties and data attached.
![image](https://user-images.githubusercontent.com/29561776/84608440-ceebc580-aef5-11ea-8a7d-03393c82b4c7.png)
![image](https://user-images.githubusercontent.com/29561776/84608454-e32fc280-aef5-11ea-9459-d83489079806.png)

**Comment by hol430** [comment]
Hi @JodyBig can you upload your .apsimx file?

**Comment by JodyBig** [comment]
I'm working on the Nutrient test set. The error above is in the Horsham test.
[Nutrient.zip](https://github.com/APSIMInitiative/ApsimX/files/4777636/Nutrient.zip)
Thanks

**Comment by hol430** [comment]
Hi Jody, I ran the attached file and get the same result as you. Upon closer inspection it looks like there are some missing/strange soil parameters (see screenshots below). I filled these empty cells with values, then reran horsham and am no longer getting blank cells in the report.

![image](https://user-images.githubusercontent.com/36427516/84611802-360f7700-af02-11ea-8ca2-66530ec7306f.png)

![image](https://user-images.githubusercontent.com/36427516/84611891-62c38e80-af02-11ea-8d03-4ebda5942b3b.png)

![image](https://user-images.githubusercontent.com/36427516/84611842-4c1d3780-af02-11ea-92f4-9351e5cdd0e7.png)

**Comment by JodyBig** [comment]
Thanks! I never thought to look there because it was working and then stopped mid run.???

**Comment by hol430** [comment]
Yeah, the empty cell in the depth column of the SoilWater node actually had a value of 160-NaN, because the 999999 you see in thickness appears to be some sort of error value. Generally speaking, empty cells aren't a huge problem, unless the empty cell is depth.

In this case, the result was a 10th soil layer with NaNs everywhere, so when the simulation started running, the NaNs started to spread/proliferate, and eventually made it into the nutrient code. We don't display NaNs in the user interface (we show empty cells instead) which is why you see the empty cells in the report.

To fix the problem, you should be able to get rid of the empty row with NaNs from the soil water grid. To do this, click the empty cell in the depth column, then shift click on the cell furthest to the right, then hit delete.
