### ISSUE TITLE
No values for Wheat.SowingData.Cultivar for some simualations

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5304]
In the wheat.apsimx under Test folder, some simulations don't report Wheat.SowingData.Cultivar.

For example, there are 203 simulations under `Experiment PalmerstonNorthCE`. However there are 7 simulations don't report `Wheat.SowingData.Cultivar` under table `SowingReport`, and no `FolderName` under table `Simulations`.

See list of simulations below. 
![image](https://user-images.githubusercontent.com/1657381/84723314-a2ed4480-afc8-11ea-9b9b-f679016f7386.png)

PS: There are 336 simulations without report `Wheat.SowingDate.Cultivar` in `Wheat.apsimx` in total.

The wheat.db is obtained under command line with arguments ` /MultiProcess /NumberOfProcessors:7`.

**Comment by hol430** [comment]
Hi @byzheng, which table is this in? If this is the daily report, then there will be some rows where cultivar is null, because it doesn't get set until the plant is sown. If it's in the harvest report, that sounds like it might be a bug.

**Comment by byzheng** [comment]
@hol430  In the table `SowingReport` which is reported at `[Wheat].Sowing`. It is strange as only a few simulations don't report Wheat.SowingDate.Cultivar in the same experiment.

**Comment by byzheng** [comment]
Further investigation for experiment `PalmerstonNorthCE`

* 208 simulations in the interface (8 x 2 x 13)
* 196 simulations when right clicking at the APSIM Interface to `Run APSIM`. Which is the number of simulations in the table `SowingReport`
* 203 simulations in the table `_Simulations`.

**Comment by hol430** [comment]
Some of the simulations in this experiment are disabled, which is why only 196 are being run. By default, when you click on the experiment, only the first 50 simulations are shown. There is a text box at the bottom which allows you to increase this number, which should show you the disabled simulations.

The simulations which have empty cultivar in your screenshot are the disabled simulations - they're not being run, which is why there is no cultivar. I suspect that the only reason those rows exist in your .db file are because you haven't emptied it in a while. Could you try and delete the .db file (or in Apsim, right-click and select "empty the datastore") and then rerun the experiment?

**Comment by byzheng** [comment]
Thanks it makes sense for disable simulations which have 12 in total. This explain the number of simulations under table `SowingReport`. However still cannot explain the number of simulations under _Simulations table. 

I always delete the DB file before running my simulations under command line.

**Comment by hol430** [comment]
The reason there are less than 208 palmerston simulations in the _Simulations table is that not all of the palmerston simulations are being run - some are disabled. The reason that it's not exactly 12 less is that there are some simulations - such as "PalmerstonNorthCETreat1oC0hCvWinterDurat12", which exist in the observed data, but the simulation is not being run. In this case, "PalmerstonNorthCETreat1oC0hCvWinterDurat12" and a few others get added to the _Simulations table when it is read in by the excel input component.

**Comment by byzheng** [comment]
@hol430 Thanks for your explanation. It makes sense to me now.
