### ISSUE TITLE
Performance test of multiple process

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5312]
Not sure how is working and how to use argument `/MultiProcess`. I have done a simple test.

```
Models.exe Wheat.apsimx 
   user  system elapsed 
   0.06    0.02  339.33 

Models.exe Wheat.apsimx /MultiProcess /NumberOfProcessors:7
   user  system elapsed 
   0.11    0.06  312.42 

Models.exe Wheat.apsimx  /SingleThreaded
  user  system elapsed 
   0.00    0.01  441.77 
```

Seems there are no much difference if 7 processors are used. Do I correctly use the argument `MultiProcess`?

PS: I have modified Wheat.apsimx in the Validation folder with 798 simulations.

**Comment by hol430** [comment]
The similar performance is probably to be expected, you won't notice much of a difference in speed unless you have a lot more vcpus - I would say >16 at least, and our main testing environment for this feature is 32, where it makes a big difference.

**Comment by BrianCollinss** [comment]
@hol430 Apsim classic would use all cores by default. Is it not the case with NextGen? Do we have to use MultiProcess explicitly?

**Comment by hol430** [comment]
By default, if you don't use /MultiProcess, apsim will attempt to create as many threads as you have vCPUs. Each simulation is run on a separate thread. If you use /NumberOfProcessors:xx, this will limit the number of threads which apsim creates for the purpose of running simulations.

If you use /MultiProcess, apsim will, instead of creating threads to run simulations, create new processes to run the simulations. `/MultiProcess` does not at all affect the number of threads/processes created, the default behaviour will always be to create as many as you have vCPUs. All it changes is whether it runs simulations on separate threads or processes.

The reason that we added `/MultiProcess` is because each process gets a single garbage collector thread. However, if you have many vCPUs, and thus many threads running simulations, the single garbage collector thread struggles to keep up, which causes the simulation threads to start to wait for the garbage collector, which results in your effective performance taking a hit. There are supposed to be different garbage collection modes available in .net but I haven't really looked into this area very much.

Regardless, if you don't have many vCPUs - ie if you are just running apsim on your laptop - then you won't see much difference in the way of performance between default vs multi-process mode, which is what bangyou has found. On workstations with a moderate number of vCPUs, then the multi-process mode can start to make a big difference in runtime if you have many simulations. If you scale up again to a cluster context though, you will probably need to start looking at other solutions as mentioned in #4573.

**Comment by byzheng** [comment]
This strategy might be better and flexible to run simulations in parallel for a single apsimx file, but require to develop external script. 

* List all simulations in an apsimx file (#5300 )
* Split simulations into number of groups (equal to vCPUs)
* Run Models.exe with arguments `/SingleThreaded` and `/SimulationNameRegexPattern:xx`.
* Merge db files into a single db file with argument `/MergeDBFiles`

Just not sure which types of regex pattern are supported. Some examples would be useful.

**Comment by hol430** [comment]
That sounds basically the same as what the `/MultiProcess` option does - what problem are you trying to solve here? Is it related to farming out the jobs across a cluster? As for what regular expressions are supported - any valid [.net regular expression](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expressions) should work.

**Comment by byzheng** [comment]
Yes it should be the same as /MultiProcess, but would be easier to split jobs in multiple nodes.
