### ISSUE TITLE
Generalise interpolation method

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#5325]
Following on from #5121 which looked to make yesterdays and tomorrows temperature available.  The AirtemperatureFunction needs to be generalised so it can do sub daily interpolations of any variable.
Much of this has already bee done under #5121 but some renaming needed

**Comment by hol430** [comment]
@HamishBrownPFR  if a simulation ends on the same date as the last weather reading in the met file, we will get an exception thrown on the final day of the simulation. The exception is handled internally so it's not really a huge problem, but it might be more convenient to just not attempt to read tomorrow's met data in this situation. If I implement this, will it muck up your interpolation code? I think what is happening now is that the `TomorrowsMetData` variable holds today's data on the final day, so that behaviour wouldn't be changed.

**Comment by HamishBrownPFR** [comment]
So long as the behavior is not changed you can changed I am happy for you to change what ever you need to
