### ISSUE TITLE
Why is there a using for System.XML when we don't do XML anymore?

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5444]
See issue title for issue

All XML ignores should be Json ingnores

**Comment by hol430** [comment]
@hol353 it turns out that our `LinkAttribute` actually inherits from `XmlIgnoreAttribute` which I found surprising, although it makes sense in hindsight. Unfortunately, `JsonIgnoreAttribute` is a sealed class so we can't change `LinkAttribute` to inherit from it. I'm thinking it might actually be better to be explicit about all this and add `JsonIgnore` attributes to all members which have a `LinkAttribute`. Any thoughts?

**Comment by hol353** [comment]
I don't really like have another attribute on links. Inevitably developers will forget to add them. Leave this as it is?

**Comment by hol430** [comment]
Well, instead of extending XmlIgnoreAttribute, perhaps we could change the serialization code to look for LinkAttribute rather than XmlIgnoreAttribute?

**Comment by hol353** [comment]
Yep that might work.

**Comment by hol430** [comment]
I'm reopening this issue, as many manager scripts still contain XmlIgnore attributes. This is a problem because manager will serialize all of the script properties except those which have a JsonIgnore, so any properties with an XmlIgnore attribute are currently being serialized when they shouldn't be.
