### ISSUE TITLE
Use interfaces for links in Plant.cs

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5447]
Plant.cs has links that are resolved on type rather than interfaces

        /// <summary> The plant's zone</summary>
        [Link]
        public Zone Zone = null;

        /// <summary>The phenology</summary>
        [Link]
        public Phenology Phenology = null;
        /// <summary>The arbitrator</summary>
        [Link(IsOptional = true)]
        public IArbitrator Arbitrator = null;
        /// <summary>The structure</summary>
        [Link(IsOptional = true)]
        public Structure Structure = null;
        /// <summary>The Canopy</summary>
        [Link(IsOptional = true)]
        public ICanopy Canopy = null;
        /// <summary>The leaf</summary>
        [Link(IsOptional = true)]
        public ICanopy Leaf = null;
        /// <summary>The root</summary>
        [Link(IsOptional = true)]
        public Root Root = null;

**Comment by hol430** [comment]
@hut104, @hol353 - why are links such as arbitrator, root, and leaf optional? Do any of our models of type Plant *not* have a root?

**Comment by hol430** [comment]
@hut104, @hol353 - I've added an IRoot interface. The question is what do we want inside this interface? A lot of manager scripts reference plant.Root.ZoneNamesToGrowRootsIn, plant.Root.ZoneRootDepths, plant.Root.ZoneInitialDM. Do you think these belong in the interface?

**Comment by hol430** [comment]
@hol353 as part of this, I've added an `IPhenology`, and changed `Plant` to link to an instance of this interface. In your stock sensibility you have a manager script called "ManageStock", which allows the specification of a 'criteria to move animals to field'. This criteria is currently set to `Wheat.Phenology.Zadok > 0 && Wheat.Phenology.Zadok < 31 && Wheat.AboveGround.Wt >= 240`.

Because this is compiled to C# code, this is reliant on `IPhenology` having a property called Zadok. Do you think Zadok belongs in `IPhenology`? This is probably related to #5290.

**Comment by hol430** [comment]
Reopening, as the converter for this PR has caused issues.
