### ISSUE TITLE
Explore means to remove IPlantDamage.Organs in Plant.cs

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5458]
/// <summary>A list of organs that can be damaged.</summary>
        List<IOrganDamage> IPlantDamage.Organs { get { return Organs.Cast<IOrganDamage>().ToList(); } }

**Comment by hol430** [comment]
Even if we change IOrgan to inherit IOrganDamage, Plant cannot implement the IPlantDamage interface with a list of IOrgan. The only fix I can think of which eliminates one of the Organs properties is to remove the `public IOrgan[] Organs` and use the `List<IOrganDamage>` for everything. I don't think we should do this though, as it would (theoretically) allow Organs to contain an organ which is not an IOrgan, such as PastureAboveGroundOrgan.

@hol353 any suggestions? Otherwise we will have to leave this as is.

**Comment by hol430** [comment]
Even if we change IOrgan to inherit IOrganDamage, Plant cannot implement the IPlantDamage interface with a list of IOrgan. The only fix I can think of which eliminates one of the Organs properties is to remove the `public IOrgan[] Organs` and use the `List<IOrganDamage>` for everything. I don't think we should do this though, as it would (theoretically) allow Organs to contain an organ which is not an IOrgan, such as PastureAboveGroundOrgan.

@hol353 any suggestions? Otherwise we will have to leave this as is.

**Comment by hol353** [comment]
Perhaps the pattern should be that plant models just have ```public IOrgan[] Organs { get; set; }```. The caller then needs to determine which of those Organs also implement IOrganDamage. This will be cleaner for the plant model but not as clean for the caller.

**Comment by hol430** [comment]
So you would change `IPlantDamage` to also have a `public IOrgan[] Organs { get; set; }`? The problem then is that you cannot return, for example, a `PastureAboveGroundOrgan` as part of this collection, because it implements `IOrganDamage` but not `IOrgan`.

**Comment by hol353** [comment]
Yes I would change IPlantDamage. I would also change PastureAboveGroundOrgan to implement IOrgan. This would be easy because IOrgan only has 
```c#
        /// <summary>
        /// Biomass removal logic for this organ.
        /// </summary>
        /// <param name="biomassRemoveType">Name of event that triggered this biomass remove call.</param>
        /// <param name="biomassToRemove">Biomass to remove</param>
        void RemoveBiomass(string biomassRemoveType, OrganBiomassRemovalType biomassToRemove);
```
and PastureSpecies already has a RemoveBiomass method that is very similar to this but has an extra argument. Another method could be added to PastureSpecies to match the interface.

I do wonder why IOrgan only has one method in it. I suspect it should have other stuff as well e.g. IsAboveGround.

**Comment by hol430** [comment]
What's the point of having separate interfaces in that case? We could just force all organs to implement `IOrganDamage`?

**Comment by hol353** [comment]
Except that not all organs are damageable.

**Comment by hol430** [comment]
Ahh ok. Seems awfully cumbersome for the caller to have to sort out which organs are damageable though - doesn't seem like good interface design. In fact looking a bit closer, it seems like the only reason plant needs a public-facing list of IOrgans is because it's used in OrganArbitrator. If we could refactor the OrganArbitrator to connect to the Organs in a different way, we could just remove the `public IOrgan[] Organs` and keep the `IOrganDamage` version.

On a side note it would be good to consolidate on collection types. I'm not sure that using Lists everywhere is a good idea (you can add to a list even if there's no getter). Arrays also have some overhead with runtime type checking though. Perhaps IEnumerable or IImmutableList is the answer...

**Comment by zur003** [comment]
@hol353 - I have a chainsaw that make the argument that all organs _**ARE**_ damageable!

**Comment by hol353** [comment]
Hmm so do I. Perhaps all organs should be damageable.

**Comment by hol430** [comment]
Maybe we need a Damageosity after all

**Comment by HamishBrownPFR** [comment]
What is the rational for wanting to remove IPlantDamage.Organs

**Comment by hol430** [comment]
The rationale here is that plant has two properties called `Organs` with different types, which are required by the different interfaces it implements. We could just rename one of the properties, but it does raise the question of why we need both.

**Comment by hol353** [comment]
# Proposal for a redesigned Biomass removal / plant damage interface

Other issues related to this:
#5472 ReduceCanopy method should be in Leaf models
#5471 Plant.RemoveBiomass(...) should be part of the ICanopy Interface
#5470 RemoveBiomass methods should all return an amount of biomass removed.
#5469 The event mechanism in RemoveBiomass in Plant.cs needs refactoring
#5462 Remove Harvest () from plant.cs

The current IPlantDamage is implemented by plant models to allow livestock and insects to damage organs of a plant and APSIM users to damage the plant in different ways. The current interface is at the plant level, not the organ level. It is used like this:

```c#
RemovalFractions consumption = new RemovalFractions();
consumption.SetFractionToRemove("Leaf, FractionLiveToRemove: 0.1);
consumption.SetFractionToRemove("Leaf", FractionDeadToRemove: 0.2);
consumption.SetFractionToResidue("Leaf", FractionLiveToResidue: 0.0);
consumption.SetFractionToResidue("Leaf", FractionDeadToResidue: 0.0);
consumption.SetFractionToRemove("Stem", FractionLiveToRemove: 0.1);
consumption.SetFractionToRemove("Stem", FractionDeadToRemove: 0.2);
consumption.SetFractionToResidue("Stem", FractionLiveToResidue: 0.0);
consumption.SetFractionToResidue("Stem", FractionDeadToResidue: 0.0);
Wheat.RemoveBiomass("Graze", consumption);
```
The first argument ("Graze") is used to lookup default removal fractions from a lookup table when fractions are not specified. This is typically the case when a Harvest is done as no fractions are specified by the user. The defaults are crop and management action dependent. Because of this I don't think they belong in the plant models as new management actions can be defined by the user in their manager scripts (e.g. pluck) that the plant model won't know about. I propose the Harvest method in plant does lookups to get defaults and we remove the defaulting mechanism for all other management actions (e.g. "Thin", "Graze" etc). Looking through the test suite, I can't see any cases where biomass removal defaults are used for 'Thin', 'Graze', 'Cut' etc.

Instead of calling the plant to perform a remove biomass on behalf of its organs, I propose we call the organs directly. We should also do the same for the other damage functions.

Instead of passing an object instance (e.g. 'consumption'), we can pass extra fraction remove arguments to the RemoveBiomass method instead. We should also add a return value specifying the amount of biomass removed from the organ. 

This is the result:
```c#
removedLeaf = Wheat.Leaf.RemoveBiomass(liveToRemove: 0.1, deadToRemove: 0.2, liveToResidue: 0, deadToResidue: 0);
removedStem = Wheat.Stem.RemoveBiomass(liveToRemove: 0.1, deadToRemove: 0.2, liveToResidue: 0, deadToResidue: 0);
Wheat.Leaf.ReduceCanopy(deltaLAI: -0.1);
Wheat.Root.ReduceRootLengthDensity(rootLengthModifier: 0.9);
Wheat.Structure.RemoveAssimilate(deltaAssimilate: 100.0);    // NB: This has never been implemented.
Wheat.Structure.ReducePopulation(newPlantPopulation: 80);
```

This seems much cleaner and will reduce the amount of code in PMF. There are 33 simulations in our test suite that will need to have their manager scripts modified to this new approach. I'm not sure a converter can be written.

The RemoveBiomass method in Plant also publishes events for 'Harvest', 'Prune', 'Cut' etc. I propose that we keep the 'Harvest' event but remove the others. If an APSIM user wants an event for 'Prune' or something else they can publish it from their manager script.

Thoughts? Comments?

**Comment by hol353** [comment]
So it turns out that this is very hard to do. The coding is straight forward but there are a lot of manager scripts that need manual modification because the converter can't do it all.

The main problem is that there are a lot of scripts called 'defoliation' and 'defoliationmanager' in various .apsimx files that are at times subtly different. Each script is about 1200 lines long. Look in:

Examples\RedClover.apsimx
Prototypes\MultiSpeciesPasture\MultiSpeciesPastures.apsimx
Tests\Validation\AgPasture\AgPasture.apsimx
Tests\Validation\PlantainForage\PlantainForage.apsimx

These need to be consolidated into one.

Branch [hol353:removebiomass](https://github.com/hol353/ApsimX/tree/removebiomass) contains my work so far.

**Comment by par456** [comment]
I believe this was eventually solved as IPlantDamage.Organs no longer exists.
