### ISSUE TITLE
Report view 2.0

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5530]
There are a few future improvements for Report View (+Grid View) that would be great, especially for working with large tables. Some of these may relate to the Speed Up changes being made and may be due to unneeded background work only apparent when working with lots of data.

1. Display empty grid when no table found (empty as never wrote data) for selected report or the report is disabled rather than the data from the first table in the list (even though the table drop down selector is blank)

2. Lazy loading of report and grid view. Is is possible to only load the grid when the user is on or selects the Data tab (maybe with a loading spinner), or use async loading of data?

3. Is it possible to have lazy loading of data to display in the grid view based on scrollbar position, or maybe only load first 50 lines until the user touches scrollbar or down arrow or page down. This may be a builtin feature of future UI controls.

These will significantly improve the UI responsiveness especially with large data tables. 
The same may be true for working with graphs and large data tables.

**Comment by hol430** [comment]
Yes, this would be very useful (may be related to #5387). Some other views are affected by this as well (graphs, models with a lot of autodocs such as wheat, ...), so it would be good if we could have a general solution which isn't tied to this one view. Maybe the event handlers for the gtk events should all be `async void`? Maybe `IPresenter.Attach()` should be async? Maybe there is a better solution?

Note that implementing async methods on the datastore component which uses SQLite is going to be difficult/impractical until we adopt the nuget package for SQLite.

**Comment by hol430** [comment]
After doing some experiments with the GridView, it appears that a large part of the unresponsiveness while scrolling/navigating is due to the implementation of cell selection. The underlying gtktreeview control doesn't actually support selection of individual cells - it only supports selecting an entire row. To work around this, in the cell data function we check if a given cell is selected, and if so, set its background colour appropriately. While this does work, this function is called pretty regularly (thousands of times per second while moving the mouse), so the time spent in this function adds up very quickly.

As a test, I created a standalone gtk app which creates a treeview with a million rows and a hundred columns and fills it with data. Without all of our hacks for cell selection/navigation, the treeview is perfectly usable and very responsive (once it loads).

I'm not sure if there's a better way of hacking the treeview to achieve what we want - I certainly haven't been able to find one. Some solutions might be:

- Don't allow selection of individual cells in the datastoreview. Since we can't edit cells here anyway, this might not be so bad. Unfortunately we wouldn't be able to copy individual cells - only an entire row.
- Try and override the bits of treeview which handle cell selection. I've looked into this and I don't think it will be possible from managed land, so it would also require us to distribute our own platform-specific gtk binaries. And we'd also need to go and do it again when we move to gtk3 (I'm not sure how much the treeview code has changed between gtk2 and gtk3)
- Use a different widget. I don't think any of the stock widgets do what we want, but something like gtksheet might work
- Write our own widget. No idea how hard or easy this will be, but for what it's worth, the stock treeview widget is ~20k LOC
- Do nothing

**Comment by lie112** [comment]
Great detective work and effort @hol430 .
Seeing our time with GTK2 and maybe even Gtk might be limited over time, I don't suggest anything too involved, as shifting, or updating to versions with better widgets will be the best option. Seems making treeview the base for grids limits functionality and would b better the other way around.
I would be happy with only having row selection. Do most time people selecting cells just want to get some data into Excel (and there is export report anyway) or are they grabbing individual cell values for other reasons?
I would vote for speed and performance in rendering and working with larger report tables over single cell selection (so option 1 above).

**Comment by jbrider** [comment]
Is there any way to utilise a js grid within a web component?

**Comment by her123** [comment]
Your first option of only selecting a row sounds good.

**Comment by hol430** [comment]
I'd rather not use javascript if we can avoid it - the javascript comms in the htmlview is platform-specific, so maintaining it is a real pain. Plus at this stage we don't have a htmlview implementation for .net core/gtk3, and that doesn't seem likely to change soon.

Only selecting an entire row at a time does sound like the obvious solution here. I'd be interested in hearing from some users how often they actually copy an individual cell or range of cells.

For other grids (property grids, profile grids, ...) - we can probably leave these as-is, performance tends to be ok (in my experience) since the grids themselves are rather small.

**Comment by jbrider** [comment]
I'm ok with the reports being row only - but I can see where people would
want to be able to select cells/columns to copy.
Is it difficult to add an option to dump the current table's filtered data
to a file or copy it to the clipboard?
That would be handy and would also provide a work around.

**Comment by hol430** [comment]
Yep, copying data would still work, with the caveat that you'd be copying the entire row(s).

**Comment by par456** [comment]
Closing this issue, the report view has been refactored multiple times now.
