### ISSUE TITLE
How to stop ApsimNG overwriting saved version of model?

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5553]
ApsimNG frequently saves the model you are working on, overwriting the previous saved version, without any indication it is doing so. I just deleted a simulation from a model for a test, and found it had overwritten the complete version and I could not get the deleted component back. The only way to avoid this is to always save any model you are working on under a different name before editing it.

**Comment by hol430** [comment]
Hi @jal-frezie, the way this is supposed to work is that apsim will save in any of these situations:

1. You press save
2. You try to close the file (either close the tab or the whole gui) and you click "yes" when asked whether you want to save your changes
3. When you run simulation(s)

Apsim should not save under any other conditions as far as I recall. The saving when you run simulations is the one that I've found catches most people by surprise - could that be what's happening to you?

Also worth noting that whenever apsim saves the file, it will create a backup of the previous version of the file called for example "filename.apsimx.bak".

**Comment by jal-frezie** [comment]
Yep, its saving when running simulations that I was unaware of. Of course after a few runs the .bak will not be the original model either. This seems confusing and pointless to me, is there any good reason for it?

**Comment by hol430** [comment]
Yeah the reason for saving a .bak is probably in case saving the file fails for some reason (e.g. disk/IO error?) and the .apsimx file gets destroyed/corrupted/whatever. Personally I just use git for making incremental changes to my files, so I can undo changes when I need to or go back to an earlier version of the file. Otherwise I end up with myfile_v16_final_2_fixed.apsimx.

I'm not sure why we save when running simulations, other than 'it's always been done that way'. Maybe @hol353 recalls why it was implemented this way.

**Comment by hol353** [comment]
I personally don't like it saving when it runs a simulation for the reason stated above. You might want other opinions before removing this though.

**Comment by hol430** [comment]
Does anyone have any objections to removing the "save the file to disk whenever we run simulations" behaviour? I will interpret no response as "that sounds like a great idea".

**Comment by her123** [comment]
Saving when hitting the run button probably causes more issues than losing your changes from not saving using the save button. Might be worth checking that CTRL+S works no matter which part of the UI has focus.

**Comment by hol353** [comment]
I think I'm in favour but it has been handy when the GUI crashes unexpectedly - which happens fairly regularly. It has saved me many times.

**Comment by hol353** [comment]
I think I'm in favour but it has been handy when the GUI crashes unexpectedly - which happens fairly regularly. It has saved me many times.

**Comment by hol353** [comment]
I think I'm in favour but it has been handy when the GUI crashes unexpectedly - which happens fairly regularly. It has saved me many times.

**Comment by hol353** [comment]
I think I'm in favour but it has been handy when the GUI crashes unexpectedly - which happens fairly regularly. It has saved me many times.

**Comment by hol430** [comment]
The gui should never crash. If it does, please file a bug report. It almost never crashes for me, perhaps because I mainly use it in short bursts.

**Comment by hol353** [comment]
I would file a bug report but it isn't consistent. It uses happens after using it for > 10 minutes and editing values in grid or manager or copying and pasting nodes in the tree. It is always a GTK 'read/write protected memory' type of error.

**Comment by hol430** [comment]
Perhaps open a master issue for these crashes, and each time it happens, post a comment describing what you were doing at the time. Maybe with enough data points a pattern will emerge. If I don't see any issues about this sort of thing, and it works perfectly for me, then I tend to assume there is no issue.

My suspicion is that it's due to our abuse of the gtk libraries, which is visible via the Gtk-Critical "assertion failed" messages being printed to stdout while using the gui. These should probably be fixed regardless.

**Comment by lie112** [comment]
I'm in favour of removing save on run if it affects people, but I have become somewhat used to the feature and know my last run is saved and never really use the save button.
I find that when I encounter a bug in the UI the simulation had not been saved for ages as most problems occur during long periods of working with the simulation and are very difficult to repeat and report. I'll dig up with error log next time.

**Comment by zur003** [comment]
I suppose we could have a user-settable flag for "automatically save on run", but would having this as a configuration option be confusing to the user? 

I vaguely remember that @sno036 expressed an argument for auto-saving a few years ago, but I don't recall the details...

**Comment by hol430** [comment]
The argument for implementing auto-saving is usually to avoid data loss when the program crashes. Personally I don't like auto-saving and prefer to do regular manual saves, but then I don't really use software that crashes regularly. Having global hotkeys (ctrl +s) will help with this as @her123 pointed out. Fixing the crashes that some people are reporting will also help with this.

Adding this as a user option might be a good compromise, and would be easy enough to implement, as we already have infrastructure to support user settings. The only question would be how to expose the option to the user, as we don't really have a central settings dialog.

**Comment by jal-frezie** [comment]
Perhaps it should do what Simile does, and record each change made in a log file so in the event of a crash (of the OS of course -- Simile never crashes :-) the user can get back to exactly where they were?

**Comment by sno036** [comment]
@zur003 (aren't you supposed to be on long-service leave?) you have a good memory. The argument was in the early days of NG when it was (even more) unstable. I had done some innocuous error (e.g. forgetting a ; at the end of a manager script line) that was found by running the simulation. That run saved the file and because it compiled everytime I touched the script or opened the file it would not let me back into script to fix - it kept throwing the error message. The only fix I had at the time was to edit the file in a text editor.

@hol430 ("but then I don't really use software that crashes regularly") - oh yeah! Of course ... I forgot ... :-)

For my opinion, users have now become accustomed (perhaps reliant on) to the auto-save and I think it would be dangerous to change it now.

We could highlight the checkpointing and perhaps even strengthen it.

There is no 'right' answer for auto-saving and now the undo feature is enabled (and it is more stable!). I'd probably vote for continuing with the auto-save. A log file would be great though.

**Comment by sno036** [comment]
PS - if this is a serious proposal to change then I would consider this a Major (even though not a science issue) and would kick it to the RP.

**Comment by Keith-Pembleton** [comment]
I have been in both situations, ie not wanting it auto saved and then also having my skin saved by the auto save function.  Why couldn't it save it as a temporary file (that could be recovered from) when the simulation is run and only save the over the original file when the save button used?

**Comment by peter-devoil** [comment]
I'm in favour of a micro version control system - storing either base + deltas, or simply entire copies. Disk space is cheap.

**Comment by hol430** [comment]
Not stale. What do we actually want to do here?

**Comment by peter-devoil** [comment]
@sarahcleary wil be putting together the @APSIMInitiative/reference-panel agenda later this week - let's discuss there.

**Comment by sarahcleary** [comment]
@hol430 - please note the decision at the last RP meeting - @APSIMInitiative/reference-panel agreed that a button to allow autosave should be included. Default to on.

**Comment by lie112** [comment]
I think this leads us to the need for a APSIM settings file that allows this and a range of other UI/system settings to be set by the user. For example there is the Dark/light theme switch and find size that could also be in this category. Defaults would be used if this file not not available and a file is better than trying to save system settings across multiple os. I'm sure more examples will appear over time. It could also relate to settings used at command line. 
These settings could all be a properties model and accessed via a single settings button to via a property presenter.
I would vote for not adding many more buttons to the button bar, but in fact removing theme etc to this settings section and not adding an autosave button.

**Comment by hol430** [comment]
We already have a settings file, on windows it's located at `%appdata%\ApsimInitiative\ApsimX\ApsimX.xml`. You can access the settings from the code via the `Utility.Configuration` class. These settings are only for the user interface, so they can't be accessed from models. I agree that we don't really want more buttons on the home screen. I've proposed having a gui editor for the settings file but that idea has been shot down before. Let me know what you guys think is best.

**Comment by her123** [comment]
It may be time to do a settings dialog

**Comment by peter-devoil** [comment]
@hol430  - In the [november RP meet](https://github.com/APSIMInitiative/ReferencePanel/issues/77), the panel agreed that "... a button to allow autosave should be included. Default to on." That button could be on a dialog or settings tab, or both.

**Comment by hol430** [comment]
Sure. What did you have in mind exactly? It just saves on a timer?

**Comment by peter-devoil** [comment]
No - an option to use the present behaviour (auto save when running model), or not (save only when user clicks save).
