### ISSUE TITLE
Can Agroforestry tool run crop zone models in parallel?

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5554]
If you have several separate models in your simulation, or if you have an experiment which runs several variations of one model, then the runs happen in parallel and if you have multiple processors they can run on separate cores. But this does not seem to be the case with the different crop zones in the AgroforestrySystem model. Can it be fixed so they run in parallel?

**Comment by sarahcleary** [comment]
@hol430?

**Comment by hol430** [comment]
I won't say it's impossible, but it would be a lot of work. Parallelisation at the simulation level works very well because every simulation you run is completely independent of every other simulation, so there is no synchronisation required. Zones on the other hand are not totally independent, you would need to ensure that they remain synchronised which might create noticeable overhead. Also, none of the models are thread-safe. And this would only help if you were running a single simulation - if you're running many agroforestry simulations together, you would still be able to reap the benefits of parllel processing. I really don't know anything about agroforestry - is this a common scenario, having one huge simulation which takes a long time to run?

Perhaps what is called for here is some time with a debugger/profiler, to see if we can improve performance in multi-zone simulations. It should be possible to achieve noticeable improvements without introducing parallelisation.
