### ISSUE TITLE
Console.WriteLine() produces no console output in AgroforestrySystem

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5555]
I have been using WriteLines to debug my manager scripts, with the output appearing in the console from which I started Apsim (this is in Linux). But trying the same thing within an AgroforestrySystem, the manager compiles and runs OK but the output is not seen in the console. Do the scripts run in a virtual console or something?

**Comment by hol430** [comment]
Hi @jal-frezie, this happens for me as well when I have two scripts which have very similar code and the same class name. Can you try changing the class name on one of the scripts and see if that fixes the problem? If that doesn't fix it you might need to upload your .apsimx file.

I believe that having multiple different classes with the same name is not technically supported by the runtime, and we have implemented a few hacks to make it generally work, but in scenarios with very similar scripts, the clr can still get a bit confused.

**Comment by jal-frezie** [comment]
Guessing the class name is the name of the manager module as it appears in the tree view? Tried changing it to a unique one but still not Console.WriteLine() output. Model and met file attached; I have changed the Harvesting manager in annular zone B to be called HarvestingB, but the WriteLine in its script is not producing output, although the crop is getting harvested. 

[sample.gz](https://github.com/APSIMInitiative/ApsimX/files/5095353/sample.gz)

**Comment by hol430** [comment]
By the class name, I mean if you click on the manager and go to the script tab your script contains something like `public class Script : Model`. In this case, `Script` is the class name.

However I don't think the class name is the problem here. What is happening is that you have the 'reset on date' script inside each zone which is supposed to do a `Console.WriteLine()`, however, you also have a 'reset on date' script under replacements. When you run the simulation, apsim will see the 'reset on date' script under replacements, and it will go and replace every 'reset on date' script in the simulation with the version under replacements. And the version under replacements doesn't have any `Console.WriteLine()`.

So the fix would be to either

1. Don't have the script under replacements
2. Change the version under replacements so that it does the `Console.WriteLine()`. E.g.

```csharp
[Link(Type = LinkType.Ancestor)] private Zone zone;
...
Console.WriteLine("Resetting zone " + zone.Name + " on " + Clock.Today.ToString("yyyy-MM-dd"));
```

**Comment by jal-frezie** [comment]
Not sure this is the whole answer. Looking at the WriteLine() I put in the Harvesting manager script in soil zone B, I changed 'Script' to 'Different' to avoid the similar names problem, and checked that there is no Harvesting manager under Replacements. As an added precaution I ran the simulation by right-clicking on the NotPollarded node rather than the top level Simulations node, so the replacements should have been out of scope. And still nothing got written to the console! Is there perhaps a better way of debugging scripts?

**Comment by hol430** [comment]
Well the replacements node is not very flexible, it will *always* be applied to your simulation, no matter what. The only way to stop this is to delete the replacements node. (Or maybe you could disable it, I'm not sure.) That being said, you don't have a harvesting manager under replacements, so it's not going to be the issue here.

To the question of why HarvestingB is not working correctly, I had a look at your sowing rule, and you have this code inside which runs every day:

```csharp
                if (Wheat != null && Wheat.IsReadyForHarvesting)
                {
                    Wheat.Harvest();
                    Wheat.EndCrop();    
                }
```

This is doing exactly what HarvestingB is supposed to do, execpt that it's being executed *before* the HarvestingB manager (order of execution for components subscribing to the same event is generally the order they appear in the tree in a depth-first search, although I wouldn't suggest relying on this behaviour). So you could either get rid of the harvesting manager, or get rid of this code in the sowing manager (remember that you need to edit the manager under replacements).

As for debugging manager scripts, you can write to the summary file instead of stdout for a more persistent log. Another alternative if you have a debugger attached to ApsimNG.exe, you can add

```csharp
using System.Diagnostics;
...
Debugger.Break();
...
```

Calls to `Debugger.Break()` will act just like a breakpoint inside code. Execution will be paused and you can step through your code, inspect variables, etc. I do this when I'm completely stumped, otherwise `summary.WriteMessage()` is my go-to.

**Comment by hol430** [comment]
Hmm you're right zones do have a numerical index for some reason. It is literally just returning `Parent.Children.IndexOf(this)`, which seems kind of redundant. @hol353 do you recall why this exists?

As for why it goes from 2 to 7 for your zones - your zones are the 3rd - 8th children (0-indexed so indices 2-7) in the simulation. If you add another component into the simulation and move it up above the zones in the tree (right click -> move up) then the value of `Index` in the zone will change. In general you would probably want to be careful about using this property.
