### ISSUE TITLE
Addition of Agroforestry Model 

### ISSUE THREAD

**Issue by fainges** [APSIMInitiative/ApsimX#56]
An agroforestry model is required. Implementation will be by Neil Huth and Justin Fainges. The implementation will involve the creation of a multi-Zone aware tree model and associated GUI.

**Comment by fai04d** [comment]
Moved model to Prototypes directory.

**Comment by hol353** [comment]
This is the initial reviewers report by Michael Battaglia dated 30th August 2016

**Comment by sarahcleary** [comment]
@hut104 - can you please provide an update on where this is at?

**Comment by sarahcleary** [comment]
@hol353 to discuss progress with @hut104

**Comment by sarahcleary** [comment]
Please note action from RP 8/19 action: @hol353 to discuss with @hut104 and provide update

**Comment by hol353** [comment]
From @hut104: Agroforestry model still to be incorporated into release sometime this financial year.

**Comment by hut104** [comment]
@hol353  and @sarahcleary  please see the response to the reviewer's report.

[Agroforestry_System_Model_APSIM_ReviewersReport_v1 3 Response.docx](https://github.com/APSIMInitiative/ApsimX/files/4089197/Agroforestry_System_Model_APSIM_ReviewersReport_v1.3.Response.docx)

**Comment by hol353** [comment]
Looks good to me. @sarahcleary - can this be signed off by the RP out of session?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note the response to the reviewer's report above.  Please review and confirm this is ready for release.

**Comment by peter-devoil** [comment]
Fine by me.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel  - would be good to be able to sign this off out of session - but need a representative from each AI organisation to confirm.  At this stage I only have UQ's approval.

**Comment by hol353** [comment]
I'm happy for Agroforestry to be included in the release.

**Comment by jbrider** [comment]
Approved.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - still awaiting approval from AgR and USQ

**Comment by LouisAK** [comment]
Approved

**Comment by sno036** [comment]
I will try to look at this before the meeting but tomorrow is pretty packed - might be later in the week

**Comment by sarahcleary** [comment]
@sno036 - just a reminder we are awaiting AgR's approval.

**Comment by sarahcleary** [comment]
@sno036 - just a reminder we are awaiting AgR's approval.

**Comment by sno036** [comment]
@hut104 - sorry - I don't think this is ready for release. I'm very interested to have a good look at it but it needs documentation. 

I can't see any documentation (which is a problem to begin with),
I opened the Single Tree Example simulation:
•	the last parameter on the zone has a spelling error and the unit is obscure (H = multiples of height? I assume. But it needs some explanation)
•	Having rainfall interception as a straight fraction of rainfall is a really bad idea – the fraction should be relatively large for small rainfall events but small for large rainfall events – there is a maximum interception possible. Or is this supposed to be stemflow or something? Either way I think it needs some more work (even if it just relabeling as stemflow) (and some documentation).
- I didn't investigate much further because there wasn't any documentation so I didn't know what I was doing.

**Comment by sarahcleary** [comment]
Any update @hut104?

**Comment by hut104** [comment]
It's my understanding that this is now released.


________________________________

**Comment by sarahcleary** [comment]
@hol353 - where is this at?

**Comment by hol353** [comment]
Looks like this has made it into release but it can still be improved upon. The documentation seems to be fixed and is available on the web site.

**Comment by sarahcleary** [comment]
@sno036 - I assume this can be removed from the RP agenda?  please let me know if it needs further discussion

**Comment by sarahcleary** [comment]
In Release
