### ISSUE TITLE
Editing graphs by clicking the interface does not appear to work 

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5600]
Editing graphs by clicking the interface does not appear to work - for instance double clicking the axes used to enable changing things. First noticed this last Friday

**Comment by hol430** [comment]
Hmm, seems to be working ok for me. The only problem I see is that changes are not applied until I click away a different node and back onto the graph. Is this the problem you're seeing? I'll see if I can fix it either way, just want to make sure I'm not missing something here.

**Comment by MarkLieffering** [comment]
Nope – double clicking on graph does nothing, nada. I am using the LAG (latest and greatest) version from this morning.

**Comment by MarkLieffering** [comment]
Nope – double clicking on graph does nothing, nada. I am using the LAG (latest and greatest) version from this morning.

**Comment by hol430** [comment]
Interesting...I did notice a performance regression from my changes last week. This was noticeable for me in the soil temp prototype. I double clicked on the axis label and had to wait 5 seconds or so for the options to show up. I wonder if your issue is similar - I expect the wait time will be longer if you have more series/data points on your graph. For example, the wheat example has an extremely simple graph, and the wait time after double clicking on the axis is barely noticeable. I'm going to make a "working on" pull request to see if it makes a difference for you.

**Comment by MarkLieffering** [comment]
You are right WRT the wheat example - clicking opens the editor. No luck on the sim I sent to Drew regarding the other issue today, though other similar sims work OK. Maybe a one-off?

**Comment by hol430** [comment]
Yeah I haven't looked into the other manager script issue yet, although off the top of my head I think I have seen something similar.

As for this issue, can you pull down latest changes and see if that fixed it?

**Comment by MarkLieffering** [comment]
Hi Drew - all g now wrt the graphing issue.

Cheers
