### ISSUE TITLE
issues encountered in Sensitivity analysis tutorial

### ISSUE THREAD

**Issue by cranju** [APSIMInitiative/ApsimX#5655]
Hi I was trying the tutorials on Morris method, Sobol method and Factorial ANOVA and has some issues which I am posting here.
1. There is no information on simulation log displayed on the Summary node for Morris and Sobol method, but I could view the same for factorial ANOVA.
2. When I clicked the report note after running my simulation for the tutorials, following errors popped up:
Morris & Sobol method- no column: T. SimulationID
Factorial ANOVA method- no column: S. Name
3. How are the example statistics shown in DataStore calculated for each of these methods?

Regards
Ranju

**Comment by DavidJohnston491** [comment]
Hi Ranju (@cranju) ,  What version of ApsimX are you running?
I am open to being corrected by the developers of these routines, but from what I can see (for APSIM 2020.9.3.5602) ...

-    1. Summary log is not created for Morris or Sobol because the simulations for these are controlled and run from outside the  ApsimX UI, and the summary log is not, or cannot be passed back into the datastore for the simulation run. The ANOVA is run and controlled by the ApsimX UI and has been coded to retain the summary log information.

-    2. These are bugs in the report generation routines, but are not affecting the actual outcomes of the analysis. You can make a copy of the 'Report' node under the 'Simulations' node to see the results for the analysis and this is not affected by the reported column name errors.  Or you can view the Report details in the DataStore. Potentially some of the columns that report component expects to find have either been named differently, or have been omitted. The analysis is not compromised.

-    3. For Sobol, the SobolMethodSetup memo says  'The (very) mathematically inclined reader may find a detailed account of Saltelli's version of the Sobol method in [Saltelli2002].' 
For Morris you could refer to 'Campolongo, F, Cariboni, J & Saltelli, A 2007, 'An effective screening design for sensitivity analysis of large models', Environmental Modelling & Software, vol. 22, no. 10, pp. 1509-18.'

Regards
David

**Comment by cranju** [comment]
Hi David,

Thank you for answering my queries.  I very much appreciate it.  I am currently using APSIM 2020.09.09.5640. 

Regards
Ranju
