### ISSUE TITLE
How to install using VS Code

### ISSUE THREAD

**Issue by schrummy14** [APSIMInitiative/ApsimX#5663]
Hello,
I am trying to compile the project.
I see the solution file, which suggests that this is all that is needed for visual studio, but I also noticed the .vscode file and was hopeful that I did not need to install visual studio. Is there a write up on how to do this? I saw that there was an installation header in the README file but there are no instructions there.

I do not wish to install visual studio and worst comes to worst I can always compile via the linux instructions in wsl.

Any help would be appreciated. Thank you.

**Comment by hol430** [comment]
Hi @schrummy14 - yep building and debugging via vscode is certainly possible, although it's mainly geared towards use on linux, since the debug configuration uses mono. Building should work out of the box if you have the MS build tools installed and on PATH. I haven't actually tried to use them on windows without an existing visual studio installation but would be interested to know how it goes. If you don't already have them installed, you should be able to download the build tools from [this page](https://visualstudio.microsoft.com/downloads/) (in the tools for visual studio section at the bottom). You will also need the nuget command-line tool. I'm not sure if it's included in the MS build tools but I think it's available via chocolatey if all else fails.

If we can get this working I'll add some instructions to the site on using vscode on windows.
