### ISSUE TITLE
Cultivars replacements

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5706]
Following the issue #5309, I still have confusing behavior of Cultivars replacements and am not sure whether it is an expected behavior

I setup two simulations with cultivar Hartog and Axe.

Case 1:  Cultivar Axe is not found as it is no replacements for Axe under folder Cultivars

![image](https://user-images.githubusercontent.com/1657381/94777112-3fb3e080-0406-11eb-954e-dfa1f510b831.png)

Case 2: Hartog replacement is working under "Replacements"

![image](https://user-images.githubusercontent.com/1657381/94777181-5eb27280-0406-11eb-82ba-25f43f6ade59.png)

Case 3: Any other folder names are not working to find a cultivar

![image](https://user-images.githubusercontent.com/1657381/94777506-eb5d3080-0406-11eb-8c4b-66ce7f84c6f1.png)
 

It seems models.exe looks for [Replacements].Hartog, and then [Replacements].Cultivars. If [Replacements].Cultivars is found, other cultivars will be ignored in the resources.

I would expect to find a cultivar in any places of tree structure.

See attached file for example
[Desktop.zip](https://github.com/APSIMInitiative/ApsimX/files/5309953/Desktop.zip)

**Comment by hol430** [comment]
I'm pretty sure all 3 of these are the intended behaviour. If you're overwriting individual cultivars from replacements, my recommendation would be to not use a cultivar folder. Just put the cultivar directly under the replacements node. To be honest I don't know why cultivar folders even exist, I don't think they actually do anything.

**Comment by byzheng** [comment]
Thanks @hol430. I understand cultivar can be directly added under replacements node, but will be mess if there are big list of cultivars. Would be useful to allow cultivar in any folder.

Just tested: the cultivar replacement is not used if it adds into a folder.

 
![image](https://user-images.githubusercontent.com/1657381/94884398-b73e4a00-04b0-11eb-98f5-7f7d142468d1.png)

**Comment by hol430** [comment]
Yep, the replacements only looks at its direct children - not descendants. In this case, it sees a child called "Folder" so it will try and replace a model in the simulation called "Folder". That's why using a CultivarFolder called "CultivarTest" doesn't work - there is no model in the simualtion called "CultivarTest". It's also why the first example deletes all cultivars except for Hartog - the CultivarFolder in the simulation is replaced with the one beneath replacements, which contains only one cultivar (Hartog).

So if you wanted to keep things tidy, you would need to create a CultivarFolder under replacements called "CultivarFolder" and add as children all cultivars required by your simulations. Or just add all of wheat's cultivars, that could also be an option.

**Comment by byzheng** [comment]
Thanks @hol430. it make sense now.
