### ISSUE TITLE
Introduce a Markdown widget in the GUI

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5719]
The Markdown widget should be able to read Markdown directly and render it.
Change memos to use the Markdown view instead of using HTMLView.

**Comment by hol430** [comment]
@hol353 I'm working on converting the summary UI to use the markdown view. It's working pretty well, the problem is going to be when someone wants to search for text, or select all and copy everything (as per #2695). Because the markdown view is made up of many widgets the question will be which widget do we search in? It's also not going to be possible to select everything for the same reason.

If we only want to select/copy/search the simulation log then everything should be fine, because currently the simulation log is all in one big textview. The initial conditions will be trickier because they are setup as tables containing labels (you can't select text in a label, and even if we change the labels to textviews, you still can't select text in multiple textviews at once - I think). In fact this will probably be an issue with the regular markdownview as well.

**Comment by hol353** [comment]
Yes, I'm not sure what to do about this. The multiple widgets approach is a bit of a hack really but I can't think of any better way of doing it.

For initial conditions in the summary log, can we change them to not be tables? I can't think of a way that would still display nicely though.

**Comment by hol430** [comment]
We could render the initial conditions tables as plaintext, but in order for them to line up properly we'd have to show them in a monospace font.

**Comment by hol353** [comment]
Ok then let's do that then. Use a code block and make all code blocks monospaced font.

**Comment by hol430** [comment]
@hol353 I've changed the summary view to use markdownview as discussed above. Do you think this looks ok to replace the current summary display. The initial conditions tables are a bit clunky due to the need to select all/copy all. The simulation log looks basically the same in both.

Old summary view

![image](https://user-images.githubusercontent.com/36427516/96799468-89607b80-1446-11eb-8307-ad882f27afef.png)

New summary view

![image](https://user-images.githubusercontent.com/36427516/96799512-9f6e3c00-1446-11eb-995f-c8cb463819c3.png)

**Comment by hol353** [comment]
Yep that's OK. Still very readable.
