### ISSUE TITLE
More information when listing simulations in an apsimx file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5721]
Continuing the question #5300, Is it possible to add more information to the list without running the model e.g. cultivar, sowing date? It might be difficult for simulations across multiple years with sowing rules, etc.

**Comment by hol430** [comment]
I can't think of a reliable way to query info like this. The problem is that there are so many different ways of sowing a plant and overriding your options. Even if we could perfectly discern the intent of a manager script (which we can't), the manager script can be modified or overriden in complicated ways, such as by a factors of an experiment, replacements node, etc.

If you know in advance that all of your simulations work the same way in terms of how the plant is being sown, then you could probably write a script which interrogates the json or uses the ApsimFile API to read in the file and examine its structure.

**Comment by byzheng** [comment]
Thanks @hol430  That's I am worried too. Reading json might be the only way or run apsimx file once to get my required information.
