### ISSUE TITLE
Report variables are not exist

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5733]
I would like to export latitude and longitude in the wheat.apsimx under test folder

```
[Weather].Latitude
[Weather].Longitude
```

However, the experiment `LincolnCE` and `PalmerstonNorthCE` don't have model `Weather` instead of `ControlledEnvironment`. If variable is not existed, could we report as missing?

**Comment by hol430** [comment]
Hmm, what if you try `[IWeather].Longitude` in the report? In theory this should work for both `Weather` and `ControlledEnvironment` implementations.

**Comment by byzheng** [comment]
@hol430 Nice tip. It is working for latitude and longitude. 

Could we move `FileName` into `IWeather` then I can export the weather file and read in external script? It is not necessary, but will be handy for me.

**Comment by hol430** [comment]
Probably can't move `FileName` into `IWeather` because it's specific to the `Weather` implementation. Other implementations of `IWeather` (such as `ControlledEnvironment`, `LocalMicroClimate`, etc) don't have a file name property. The contents of `IWeather` should describe the common behaviour of all of its implementations.

**Comment by byzheng** [comment]
No worry. I will parse the json file to get filename.

**Comment by byzheng** [comment]
@hol430 Another question in the issue. In the report module, could we report as NULL if an variable is not existed? it might cause some troubles to figure out the empty value in the database. But it would be useful to setup as optional.

**Comment by hol430** [comment]
Yeah in the older versions we used to report null when the report variable doesn't exist. The problem with that approach is that you're not sure if it's reporting null because the variable is actually null, or if it's because the variable doesn't exist. So we changed it to throw an error when the variable is not found.

For your use case of trying to report the filename of all weathers you could always use a manager script similar to this (warning: this code hasn't seen a compiler :):

```csharp
using System;
using Models.Climate;
using Models.Core;
using Models.Interfaces;
using Models.PMF;
using APSIM.Shared.Utilities;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] private IWeather weather;

        public string WeatherFileName
        {
            get
            {
                if (weather.GetType() == typeof(Weather))
                    return ((Weather)weather).FileName;
                return null;
            }
        }
    }
}

```

And then in your report you could add `[ManagerName].Script.WeatherFileName`.

**Comment by byzheng** [comment]
@hol430 Thanks for the tips. Will try it.
