### ISSUE TITLE
Report outputs used in report calculations

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5854]
@hol430; @hol353  - how difficult would it be to make report outputs able to be used within a report to generate a new output variable. At the moment this is not possible. A purely hypothetical example:

([AGPRyegrass].HarvestedNConc*[AGPRyegrass].HarvestedWt) as XXX

([AGPWhiteClover].HarvestedNConc*[AGPWhiteClover].HarvestedWt) as YYY

XXX + YYY as ZZZ

I can do this as a calculation on one line but with more than a few variables it gets quite cumbersome.

It is not a biggy - at the moment I am using a manager script to do the calculations and then using report to output them. If it is only a couple of lines of code it may be useful so people don't need to take the extra step of writing a manager script.

Cheers

Mark

**Comment by hol430** [comment]
I was able to get this somewhat working, but it's complicated by the 'group by' feature in report. Basically, at the time when the variable names are resolved, we don't have the context to know which group (if any) the variable belongs to. It's not a problem when not using the group by feature, but it will cause problems when using these two features together. @hol353 any suggestions? The locater code is separated from the reporting logic by several layers of abstraction.

Another problem to consider is the potential for a crash due to a stack overflow exception when reporting something like, say, `2 * x as x`.

**Comment by hol353** [comment]
No suggestions. The group by feature isn't used a lot. I used while at AgResearch to produce some very specific report files. If your solution works (partially) then perhaps that is ok for now.

At some point I'd like to redesign report to clean up the code mess and make it more flexible.

**Comment by MarkLieffering** [comment]
Thanks @hol353 and @hol430 . As I mentioned, it is no biggy - my auxiliary reporting script works fine and I may the only person who wants this!
