### ISSUE TITLE
WEIRDO wheat not growing

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#5863]
Hi,

This might be a bit too generic, but when I use WEIRDO with the Wheat model, the wheat is not really growing. 

Just wondering if WEIRDO can work with a proper crop model such as the Wheat model please.
If not, what is required to enable it?
What is the best way to check why my wheat is not growing please?

My simulation can be found at this link https://github.com/Chloe0317/APSIMsims

Thank you very much!

**Comment by HamishBrownPFR** [comment]
In theory it should work but it has not been tested.  I will take a look at your simulation

**Comment by HamishBrownPFR** [comment]
The wheat crop is not growing because it is not getting any water from the soil.

There has been quite a lot of refactoring in soil interfaces since WEIRDO was implemented and it appears the water uptake is no longer getting from the soil to the crop.  

I will need to fix this.  @hut104 @hol353 is there any doco on the coms between Plant <-> Zone <-> Arbitrator <-> Zone <-> SoilWat (or SWIM) ?

@Chloe0317  I am not sure how involved it will be to make this fix.  I am a bit rusty on this area of the code and it is quite complex.

**Comment by hol353** [comment]
I'm not aware of any doco.

**Comment by hut104** [comment]
I know of no doco either, apart from maybe a sequence diagram in a PMF paper, but the soil arbitrator is relatively small (in terms of lines of code) and I think there is basically one method that is involved in the plant comms.

________________________________

**Comment by Chloe0317** [comment]
When using SLURP with the WEIRDO demonstration, the water extraction seemed
normal, does SLURP use different comms then?

**Comment by HamishBrownPFR** [comment]
Yeh, Slurp has no water stress feed back, It just has a static LAI and demands water which Werido extracts.  Wheat has a water stress feedback so if it does not get any water it will not grown LAI and so demand no further water and not grow either. 
I need to work out how to integrate Weirdo transpiration into the water demand interface.  The reason I have not already done this is because of the hourly time step.  I think I will need to just do transpiration once per day to fold it in with the rest of APSIMs time step.

**Comment by HamishBrownPFR** [comment]
@hut104 how do you do transpiration in SWIM, is it just done once daily?

**Comment by hut104** [comment]
In NG we don't.  We just allow crops to talk with the soil arbitrator, otherwise you couldn't do multi-point simulations with SWIM3.

________________________________

**Comment by HamishBrownPFR** [comment]
@hut104 yeah, but SWIM has a sub daily time step and arbitrator a daily time step.  I guess arbitrator asks SWIM how much water can be extracted at each point and tells it how much is actually extracted once per day?

**Comment by hut104** [comment]
No, we've made SWIM3 exactly the same as soilwat2 in NG.  SWIM does all its sub-daily stuff for distribution only (inc water tables, drains, etc) and solute movement, but uptakes of water and solutes are once a day via the soil arbitrator.

We just found it too hard maintaining a second way of doing things. It simplifies things.

________________________________

**Comment by HamishBrownPFR** [comment]
OK, thanks @hut104 I will need to do the same with Weirdo.

**Comment by Chloe0317** [comment]
Thank you all! Much appreciated!

**Comment by Chloe0317** [comment]
@HamishBrownPFR Let me know if there is anything I can do to assist you with this please. Thanks in advance!

**Comment by HamishBrownPFR** [comment]
@Chloe0317 I will implement a Physical node for Weirdo so it is consistent with the other soil water models and then program it to use KL to do transpiration in the same way as the other soil water models.  This feels a bit dirty because weirdo currently uses root length density and conductivity to calculate water extraction but it will be harder to integrate this with the plant model properly so I will implement the kl approach as a stop gap.

**Comment by HamishBrownPFR** [comment]
Issue #1155 is very relevant here and is the reason I did not implement uptake properly already.  I was hoping we could fix the interface first.  Would be nice to tidy this up so different soil models can easily use different approaches for water uptake.  This is longer term, I will go with a dirty fix in the mean time.

**Comment by Chloe0317** [comment]
Dear Hamish,

Thank you very much for the WEIRDO update! I really appreciate it!
