### ISSUE TITLE
Unable to merge with recent version

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#5928]
I used to use the following code to sum maninanance respiration and fixation of all organs. But I cannot use it when I merge with the latest version of trunk. May I please know what has changed in Arbitrator and how I can get this working again? It seems **MaintenanceRespiration** does not exist anymore.

```
                    List<IArbitration> Organs = new List<IArbitration>();
                    foreach (IOrgan organ in Plant.Organs)
                        if (organ is IArbitration)
                            Organs.Add(organ as IArbitration);

                    double grossAssim = Organs.Sum(organ => organ.DMSupply.Fixation);
                    double respiration = Organs.Sum(organ => organ.MaintenanceRespiration);
```

**Comment by hol430** [comment]
What error are you getting?

**Comment by BrianCollinss** [comment]
That **organ** does not have a definition for **MaintenanceRespiration**. 

I also cannot find **Plant.Canopy** anymore. What was it replaced with? 
(Sorry this is very old branch!)

**Comment by hol430** [comment]
Looks like the maintenance respiration stuff was removed from IArbitration by Hamish a few months ago in 9fe1039070c8e0740eb5d05603847f2a543bbcee. Unsure about the best way to access it now.

Plant has a `public ICanopy Leaf`, which should give you the same result as the old Canopy property. This may be removed in the future though, as we are reconsidering how these child models are accessible. You should be able to safely use it for a while, but an alternative might be instead of `Plant.Organs` use `Plant.FindAllChildren<IOrgan>()` or `Plant.FindAllChildren<IArbitration>()`.

**Comment by BrianCollinss** [comment]
If I add a link like:

public ICanopy Canopy = null;

Would this do the same?

**Comment by hol430** [comment]
Yep, although it will depend on where this code is going - if it's in a manger script in the zone, you might run into problems if there are multiple crops in the zone. If it's inside the plant then you should be fine.

**Comment by BrianCollinss** [comment]
Yes. It is **SupplyFunction**. 

@HamishBrownPFR Our transpiration module uses maintenance respiration (as it uses a modified version of **CanopyPhotosynthesis** for gross assimilation). May I know why it has been removed, and whether it is going to be back? Thanks. (I think I am the only one using maintenance respiration now).

**Comment by HamishBrownPFR** [comment]
Hi @BrianCollinss.  Maintenance respiration is still there but it does not pass through the arbitrator anymore.  See #5651.

Each organ can still calculate maintenance respiration and this will be removed from the organs mass but this does not need to be arbitrated because maintenance respiration of a given organ is independent of other organs.  If an organ is abscised from the plant it will continue to respire.

**Comment by BrianCollinss** [comment]
Thanks @HamishBrownPFR . Now that arbitrator does not receive the values, Is there a shortcut to calculating plant total respiration?

**Comment by HamishBrownPFR** [comment]
may be loop through each organ and sum their maintenance respiration?

[Link(Type = LinkType.Ancestor)]
public IPlant Plant == null;

TotalMaintenanceRespiration = 0
foreach (IOrgan o in Plant.Organs)
    TotalMaintenanceRespiration += o.MaintenanceRespiration

It would be necessary to add Maintenance Respiration into IOrgan to get this to work

Alternatively add it back into arbitrator so it can sum them.  Arbitrator is already pretty busy so it may be better to keep this out of there if possible.

**Comment by BrianCollinss** [comment]
@hol430 is it OK if I implement this into IOrgan?

**Comment by hol430** [comment]
Is maintenance respiration something which is common to all organs?

**Comment by BrianCollinss** [comment]
Yes. @HamishBrownPFR argued in #5651 that it should not be summed for all organs and subtracted from DMFixationsuppply. Is there an easier way to sum them, if needed, without making this change?

**Comment by HamishBrownPFR** [comment]
Maintenance respiration is common to all organs

**Comment by hol430** [comment]
Makes sense to have it in IOrgan then - you'll need it in an interface if your want to sum it easily.
