### ISSUE TITLE
Event order when reporting at event Flowering

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5938]
I would like to report flowering time at event `Flowering` to reduce the run time. See attached file for an example for wheat.

In the wheat model, the variable `[Phenology].FloweringDAS` is set at event `Flowering` and `Report` model is exported variable at event `Flowering`.

It seems The `Report` model is called before `[Phenology].FloweringDAS` at event `Flowering`. Consequently, the variable `Wheat.Phenology.FloweringDAS` equals to `0` in the data store. 

I would expect the `Report` model is called after others are called at the same event. 

![image](https://user-images.githubusercontent.com/1657381/101588817-5183b680-3a3b-11eb-96c0-4a2023c12f8b.png)
[example.zip](https://github.com/APSIMInitiative/ApsimX/files/5663665/example.zip)

PS: The variable `[Phenology].FloweringDAS` is not reset after `Harvesting` or `CropEnd`.

**Comment by hol430** [comment]
Yes, looks like a bug. The FloweringDAS function inside wheat actually subscribes to the `PhaseChanged` event, and if the phase that we've changed to matches the phase name specified in the GUI, it will update the value. So it's not actually subscribing to the flowering event - it's subscribing to the PhaseChanged event. The plant class also subscribes to `PhaseChanged`, and inside the plant's handler for `PhaseChanged`, it fires off the `Flowering` event, which then triggers the report in this case. So the problem is that the plant model receives the `PhaseChanged` event before the FloweringDAS model receives this event. For better or worse, this is a consequence of the way the events model has been written and I'm reluctant to try and fix it. I think the best workaround here would be to change your report, to report `[Wheat].DaysAfterSowing` when the event name is `[Wheat].Flowering`.

Good point about the value not being reset, that one at least should be easy to fix.
