### ISSUE TITLE
-ve value for solute was passed to SWIM   Total NO3(  3)

### ISSUE THREAD

**Issue by cranju** [APSIMInitiative/ApsimX#5979]
Hi.. I was trying to run SWIM model for Potato in next gen... However I got the error as:
-ve value for solute was passed to SWIM   Total NO3(  3) =     -1.24296

error information:
FATAL ERROR: ERROR in file: C:\Users\ranjuc\Desktop\PhD_workfolder\APSIM_example files\APSIM_X_2models_potato_eg_3.apsimx
Simulation name: SWIM
System.Exception: -ve value for solute was passed to SWIM   Total NO3(  3) =     -1.24296
   at Models.Soils.Swim3.ConcWaterSolute(Int32 solnum, Double[]& concWaterSolute)
   at Models.Soils.Swim3.GetSoluteVariables()
   at Models.Soils.Swim3.OnProcess()
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)

Can anybody help me with this?

Regards
Ranju

**Comment by hol430** [comment]
Hi @cranju, if you upload your .apsimx/.met files I'll take a look at it.

**Comment by cranju** [comment]
Hi @hol353, I couldn't attach my .apsimx/.met files files as it says the file type is not supported. I have sent you an email with my APSIM file.

**Comment by BrianCollinss** [comment]
@cranju Compress all files in a Zip file. Or, as not a clean idea, if it is just one file, change the extension to txt.

**Comment by hol430** [comment]
Hi @cranju, this is happening because you have both soilnitrogen and nutrient present in the simulation (under the soil). As I understand it, these two models essentially serve the same purpose and should not both be present in the same simulation. I removed one from your simulation and I no longer get the -ve number error. I then get another error about an invalid report variable - you're reporting `[soil].SoilWater.ESW` which fails because there is no SoilWater model in the simulation - you're using swim instead. Changing this to `[soil].Swim3.ESW` fixes the problem and the simulation runs without error.

There should really be an explicit error message when both nutrient and soiln are both present in the simulation - I'll see what I can do.

**Comment by cranju** [comment]
Thanks @hol430...Much appreciate it.
