### ISSUE TITLE
Graph axis legends not updated when X, Y columns changed

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#5986]
As in description. Copy a chart, change the X/Y variables, and the axes labels and units are still the same.

**Comment by hol430** [comment]
This actually seems to be working for me. Note that if you've fixed the axis title or max/min, then they're (by design) not going to change when you change the x/y variable. You can check this by double clicking in the axis area (e.g. on the axis title). If there's text in the title/max/min boxes, then they're locked into that value and won't update when you change the variables.

**Comment by peter-devoil** [comment]
Thanks, drew.
