### ISSUE TITLE
Webkit issue on Mac OSX

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#6085]
When trying to add a model to the tree this is the error generated on Mac OS - Big Sur

Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'UserInterface.Views.TWWebBrowserWK:Browser' (0) due to: Could not load file or assembly 'webkit-sharp, Version=1.1.15.0, Culture=neutral, PublicKeyToken=eaa1d335d2e19745' or one of its dependencies.

**Comment by zur003** [comment]
That's odd. On Mac, it ought to be trying to use Safari rather than WebKit (yes, I know Safari is based on WebKit, but we should be seeing "TWWebBrowserSafari" in the load message, not "TWWebBrowserWK".) I think it's likely to be a problem with the OS identification code in APSIM.Shared\Utilities\ProcessUtilities.cs.

**Comment by zur003** [comment]
What output do you see on Big Sur if you run "uname" from a command line?

**Comment by hol430** [comment]
I think what's happening here is that when you click add model, apsim will go and look for all known types which implement IModel. As part of this, it will attempt to load the TWWebBrowserWK type, which fails due to the missing dependency. A workaround should be possible but for me this raises the question of how did this ever work...

**Comment by zur003** [comment]
Apparently a number of people have run into system problems when upgrading to Big Sur. I think the first thing to check is whether @her123 has a working "uname", since we seem to be relying on output from that to distinguish OS X from Linux.

**Comment by her123** [comment]
uname returns Darwin.

**Comment by hol430** [comment]
May not be related to a specific version of macos - I'm seeing this on an old mojave box. Did this work previously? I think I have a workaround but I can't see any recent changes which might have caused this...

**Comment by zur003** [comment]
Could it be a change in Mono? I'm not seeing any problems under Catalina using mono 6.10. I'm currently doing the update to mono 6.12, and will see whether that makes a difference.

**Comment by hol430** [comment]
I'm seeing the problem on mono 5.11. I was able to work around this by copying ApsimNG/Assemblies/webkit-sharp.* into Bin/, which allows it to be loaded even if it's not really being used. @her123 could you see if this "fixes" the problem for you?

**Comment by zur003** [comment]
That sounds right. It needs webkit-sharp.dll, and that is included in the OS X distribution. It should not require the native libwebkitgtk.dll (or .dylib) to be present, however.

**Comment by her123** [comment]
Yes. Works ok with the dll's copied to Bin. Thanks.
