### ISSUE TITLE
issue while running SWIM in APSIM X

### ISSUE THREAD

**Issue by cranju** [APSIMInitiative/ApsimX#6108]
Hi, 
I was playing along with the SWIM model and got the following error. Can you please help me to understand, what wrong I am doing in my simulation?

[APSIM_SWIM_RC.zip](https://github.com/APSIMInitiative/ApsimX/files/5891720/APSIM_SWIM_RC.zip)

1.	In MapConcentraction, the number of values doesn't match the number of thicknesses.

System.Exception: Error in file: C:\Users\ranjuc\Desktop\PhD_workfolder\APSIM\APSIM_SWIM_29.01.2021.apsimx Simulation: ExpSBrC1SitesBranxholm ---> System.Exception: In MapConcentraction, the number of values doesn't match the number of thicknesses.
   at Models.Soils.Standardiser.Layers.MapConcentration(Double[] fromValues, Double[] fromThickness, Double[] toThickness, Double defaultValueForBelowProfile, Boolean allowMissingValues)
   at Models.Soils.Standardiser.Layers.SetAnalysisThickness(Chemical analysis, Double[] thickness)
   at Models.Soils.Standardiser.Layers.Standardise(Soil soil)
   at Models.Soils.Standardiser.SoilStandardiser.Standardise(Soil soil)
   at Models.Core.Run.SimulationDescription.ToSimulation()
   --- End of inner exception stack trace ---
   at Models.Core.Run.SimulationDescription.ToSimulation()
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)

2.	Cannot find a match for link SoilN in model .ExpSBlC1Sitesdevonport.Field.Reset on sowing.Script

System.Exception: ERROR in file: C:\Users\ranjuc\Desktop\PhD_workfolder\APSIM\APSIM_SWIM_29.01.2021.apsimx
Simulation name: ExpSBlC1Sitesdevonport
System.Exception: Cannot find a match for link SoilN in model .ExpSBlC1Sitesdevonport.Field.Reset on sowing.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail)
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) ---> System.Exception: Cannot find a match for link SoilN in model .ExpSBlC1Sitesdevonport.Field.Reset on sowing.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail)
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)

Regards
Ranju

**Comment by hol430** [comment]
The second error is caused by the reset on sowing manager script, which is trying to access soil nitrogen. You can fix this by removing this script and copying in a fresh copy from the management toolbox, which has been modified to work with nutrient. The ExtraVariables script also has the same problem - it's accessing some properties of soil nitrogen but you're running nutrient instead. I notice that you're not actually using this script from your report so the simplest solution would be to delete or disable this script.

As for the problem about MapConcentration - the BrC1 simulations are the only ones failing here so it's caused by the soil in the BrC1 factor. Specifically, it seems to be caused by the CL column of the chemical component in this soil. What I did was type 0 into the bottom cell in the CL column, and then delete the 0 (so the column should be blank once more). The simulation then managed to get past this error. I'm not 100% sure how this managed to happen but I'll see if I can improve the robustness of the MapConcentration code so that this doesn't happen again.

Anyway, after fixing the CL in that soil, I got an error about "SWIM doesn't implement a reset method", so I turned off the "reset soil water" in the reset on sowing manager script. At this point, some of the simulations are getting the "SWIM failed to find a solution" error and some of the simulations are getting stuck into an infinite loop in the swim code. I've found the bug and after #6109 it should be working. Or rather, instead of the simulation never finishing you'll get a typical "swim failed to find a solution" error message.

**Comment by cranju** [comment]
Hi,

I did try doing that for the second error. But I think the script from the management toolbox uses SoilWater and not SWIM. And may be that's why the second error you got "SWIM doesn't implement the reset method". Attaching the small section from the script for reset on sowing below: So does that mean, I cannot use reset method with SWIM? In that case, how to run such simulations in SWIM?

  public class Script : Model
    {
        [Link] private Plant Wheat;
        **[Link] private ISoilWater SoilWater;**
        [Link] private Nutrient nutrient;
        [Link] private SurfaceOrganicMatter SOM;
        [Link] private Summary Summary;

Regards
Ranju

**Comment by cranju** [comment]
Hi,

I also tried putting 0 for the first error in CL and removed the reset on sowing and extra variables, I am still receiving the following error:
1. In MapConcentraction, the number of values doesn't match the number of thicknesses.
2. Swim failed to find solution

Please find my simulation file attached.
Regards
Ranju

[APSIM_SWIM_RC.zip](https://github.com/APSIMInitiative/ApsimX/files/5891983/APSIM_SWIM_RC.zip)

**Comment by hol430** [comment]
At the moment, there is no code to reset SW in swim - that's why the reset manager script isn't working. I just asked @hut104 and it's apparently possible but no one has implemented this yet.

For the problem with CL/MapConcentration - do you get the same problem with this file?

[APSIM_SWIM_29.01.2021.apsimx.txt](https://github.com/APSIMInitiative/ApsimX/files/5900846/APSIM_SWIM_29.01.2021.apsimx.txt)

**Comment by cranju** [comment]
Hi,

Yes I am getting the same issue (CL/MapConcentration/ Swin failed to run) without the reset manager as well.

Additionally, I needed to run SWIM for 5 years, so I tried doing it individually. Surprisingly, the simulation completed in 3 secs for 1999 but the simulation is not ending for 2000. All datas except the clock and the irrigation event is same. And there is just one simulation for both years.
For your reference I am attaching both the files.

Regards
[SWIM.zip](https://github.com/APSIMInitiative/ApsimX/files/5901089/SWIM.zip)

Ranju

**Comment by hol430** [comment]
Yeah the problem with the simulation not finishing is a bug in swim. I've fixed the problem, but I don't think there's a new upgrade available yet which contains the fix. Once there's an upgrade available dated  today or newer then you can download it and those simulations should finish (with a "swim failed to find a solution" error). To fix the "Swim failed to find a solution" errors you'll probably need to speak to @hut104.

**Comment by cranju** [comment]
Thanks @hol430 .
