### ISSUE TITLE
SWIM failed to find solution

### ISSUE THREAD

**Issue by cranju** [APSIMInitiative/ApsimX#6149]
Hi,

I was trying to turn my APSIM file using SWIM. But the error I get is "SWIM failed to find a solution".

Can you please help me with this?

Regards
Ranju

[APSIM_SWIM.zip](https://github.com/APSIMInitiative/ApsimX/files/5969567/APSIM_SWIM.zip)

**Comment by sno036** [comment]
Hello @cranju - SWIM in NextGen is not in release yet and we are not really in a position to support pre-release adopters. You could persist (e.g. start with an example that runs and then change one thing at a time towards what you need), use SoilWater rather than SWIM, or use SWIM in Classic APSIM. Not very helpful I know but the model is still in development.

**Comment by cranju** [comment]
Hi @sno036,

Thanks.
