### ISSUE TITLE
Stats tests need better error message

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#620]
Currently when stats fail the message is does not give any insight as to what tests have failed or why.  It would be good if the the test object could report a list of the simulations that have failed and the reason (because the stats have got worse or for a technical reason such as data formats giving invalid stats)

**Comment by fai04d** [comment]
The problem you're seeing is a bug in the test module. There should not be null reference errors in the tests. I thought I'd already fixed this, but I'll have another look.

**Comment by fai04d** [comment]
Problem was due to an old test node being present. Recreated test node has solved problem. Suggested change is already in the code; failed tests will identify which simulation caused the problem. Full output is not included from the command line as it could cause the log to drastically increase in size and would not likely be very useful as you'd have to go into the UI to fix it anyway.

This issue can be closed.
