### ISSUE TITLE
Missing dependency SharpMap.Layers.BruTile

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6247]
My latest pull from master has missing dependencies
SharpMap.Layers.BruTile had the package source set to Hol430 when opened in NuGet and is not included
Do we simply add this package ourselves to get the latest version to build?
Just wondering if adding packages mucks up any files for commit?

**Comment by hol430** [comment]
In theory, you shouldn't have to change anything to get it working. How are you building apsim? I ask because you may need to restore the nuget packages yourself - I'm not sure if visual studio will restore them automatically. Not sure what you mean when you're talking about the package source; the source you mentioned shouldn't be used for the brutile package. You could also try cleaning out your Bin/ and obj/ directories.

**Comment by zur003** [comment]
I would advise that you NOT attempt to get the latest BruTile package. You need to be sure you're using the version required by SharpMap.Layers.BruTile, and typically that's not the most recent version. Trying to mix versions can cause a range of errors (as I discovered the hard way).

**Comment by lie112** [comment]
I thought I'd check to make sure it was all ok. 
A restart of Visual Studio after my release/master pull initially had the same problem but then corrected itself and all is working.
