### ISSUE TITLE
Setting Water Table Depth

### ISSUE THREAD

**Issue by env99** [APSIMInitiative/ApsimX#6250]
I'm trying to set the water table to different depths, but am getting an error. Is anyone able to support in this?

Looking at my models it seems the default water table depth is 0, but I'd like this to be deeper in the soil profile since 0 would be the ground surface. Reading the SoilWater literature for APSIM, this should be possible to do with a manager script and call upon with an operation. 

I've attached screenshots of the error and manager script. 

<img width="594" alt="Water Table Operation" src="https://user-images.githubusercontent.com/74792163/111187277-7a0ad780-8579-11eb-8525-d9ebd8cb78b5.PNG">
<img width="622" alt="Water Table Error" src="https://user-images.githubusercontent.com/74792163/111187281-7aa36e00-8579-11eb-8821-3eb5cc24395f.PNG">
<img width="633" alt="Water Table Manager Script" src="https://user-images.githubusercontent.com/74792163/111187285-7aa36e00-8579-11eb-958d-395e3a3051b8.PNG">

**Comment by hol430** [comment]
In the operations node, you're calling a method called `InitialDepth()` in the manager script - but the script doesn't have a method of that name (from what I can see). You probbaly just need to change the operations to `2020-04-30 [SetWaterTable].Script.SetWaterTable(60)`.

**Comment by env99** [comment]
I tried changing it as suggested, and added the extra closing bracket that was missing, but am still getting the same error message. Is there something else I might be missing?

Is there another way to adjust the water table depth (without using WEIRDO)?

**Comment by env99** [comment]
I also noticed when I click specifically on the new manager script _SetWaterTable_ that I get a different error message, shown below. 
<img width="335" alt="SetWaterTable Error" src="https://user-images.githubusercontent.com/74792163/111334411-2790f000-8639-11eb-9579-ee9d43200edd.PNG">

**Comment by hol430** [comment]
Well if the manager script doesn't compile, that will be the problem. From what I can see of your manager script, you need to define a body for your SetWaterTable function - that is, you need some code inside curly braces after the function definition. E.g.

```csharp
public void SetWaterTable(double InitialDepth)
{
    summary.WriteMessage(this, "SetWaterTable");
}
```

**Comment by env99** [comment]
I followed this instruction, but still get an error, now the error is with the new line of script: 

Errors found in manager model SetWaterTable
Line 18: ; expected

**Comment by hol430** [comment]
Sounds like there's a missing semicolon somewhere in your manager script. If you upload your .apsimx file I'll take a look.

**Comment by env99** [comment]
Okay, Thank you for your help. 

For the weather file I used sheet 1.

[WATER TABLE TEST.zip](https://github.com/APSIMInitiative/ApsimX/files/6207356/WATER.TABLE.TEST.zip)

**Comment by hol430** [comment]
Ok, yeah the problem was that there was an extra semicolon on line 17. If you remove it, so the line looks like this, then the script compiles without error:

```csharp
public void SetWaterTable(double InitialDepth)
```

I tried running the simulation at this point, but I get an 'object reference not set...' error. This seems to be caused by the WEIRDO component not being correctly initialised. Looking more closely, I see that you're running both WEIRDO and SoilWater in the same soil. These two models are meant to be mutually exclusive, so you would need to remove one or the other. I tried removing WEIRDO, and after doing so the simulation ran without error. I checked the summary file, and the SetWaterTable function is being correctly called from operations (although it still doesn't actually do anything other than write a message to the summary file). One other thing I noticed is that there are some NaN values in the physical component of the soil. You can see these in the initial conditions table in the summary file. I'm surprised the simulation runs without error despite these NaN values, but I'd recommend fixing them (they are the empty cells in the physical component).

**Comment by env99** [comment]
Thank you. 

What would I have to do to the script to actually get the model to set a water table depth that affects soil water, dynamics, etc.? I'm trying to look at the effects of shallow vs deep groundwater tables on crops and available soil moisture.

**Comment by hol430** [comment]
I would suggest using an experiment node, with one factor which changes the soil composition - I think this would be easier than trying to do everything from a manager script. If you haven't used the experiment node before, I'd suggest starting with the factorial example file (Factorial.apsimx). The OperationsExpt should essentially do what you want - you would just need to change the factor to override the soil instead of the operations. In the screenshot below, Base3 simulation will be run twice; each time, the soil in the simulation will be replaced with one of the soils in the factor. If you do something similar, you can change the soil composition as you want from the gui and have apsim run the same simulation multiple times with a different soil profile each time. Let me know if you haven't used the experiment before and I can give more detailed steps for how to configure it.

![image](https://user-images.githubusercontent.com/36427516/112933351-049b2b80-9163-11eb-95d2-707ace6483db.png)

**Comment by env99** [comment]
Thank you. I'm wanting to run the same soil/soil profile with only changing the depth of the water table. I've never used this experiment before so more detailed step would be appreciated, but looking into the factorial example it seems to have the same options as normal, so I still don't know how I would add a water table at a certain depth.

**Comment by hol430** [comment]
In the attached .apsimx file I've set up a simple experiment with a soil factor. When you run the experiment (or toplevel simulations node), it will run the simulation twice, once with each soil specified in the factor. Each time the experiment is run, it will go looking for a model named Soil, and it will replace it with the soils specified under the factor. If you navigate to experiment -> factors -> factor, you'll see that the first soil only has a single layer and the second soil has several layers. I've setup the report to output total soil depth/thickness to verify that it's working. To adapt this to your purposes, you can just delete the simulation and copy your simulation onto the experiment. Then just change the soils as needed.

[wheat.zip](https://github.com/APSIMInitiative/ApsimX/files/6294022/wheat.zip)
