### ISSUE TITLE
Ignoring public properties during serialisation

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6255]
Are we using the [JsonIgnore] attribute commonly used or the [field: NonSerialized] attribute as suggested by @hol430 to ignore properties in the serialised object?
APSIM Next Gen may require a search and replace operation to update to [field: NonSerialized]

**Comment by hol430** [comment]
Are you talking about json serialization, or binary serialization? Both occur at different times, and they work differently. I'm pretty sure there are some members which we don't want serialized during binary serialization but which we do want serialized during json serialization (or vice versa). I don't recall any specific examples but there have been a number of minor bugs related to this over the years (particularly related to manager scripts).

**Comment by lie112** [comment]
I am not sure I have come across binary serialisation in APSIM. All my serialisation is to make the aspimx json file.
I had been using JsonIgnore attribute as found elsewhere in code, but @hol430 made some field:NonSerialised attribute additions/suggestions.
I am just getting my head around which form is suggested for the ignoring of properties from the apsimx file so I am consistent with everyone.

**Comment by hol430** [comment]
Binary serialization/deserialization occurs prior to a simulation being run. We do this so that any changes to the model when a simulation is run aren't applied to the 'original' copy of the models (e.g. the copy of the models that is displayed in the UI). This happens in SimulationDescription.cs.

If you have properties that you don't want written to the .apsimx file - just use a JsonIgnoreAttribute. Out of interest, where did we need to add a `[Field: NonSerialized]` attribute?
