### ISSUE TITLE
Is Layering being properly/fully applied to Physical?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6290]
See this screenshot. It is suggesting that the layering component is not applying to the sand/silt/clay etc. If it is not then it will cause errors in a number of components in the end (temperature when we move to the new version, calculation of CEC).

![image](https://user-images.githubusercontent.com/12176269/111937778-5cb3ab80-8b2d-11eb-8ead-f893dce4c92a.png)

**Comment by hol430** [comment]
Can you upload your .apsimx file?

**Comment by sno036** [comment]
@hol430 - can you pull from my repo? It is the Buckthought branch and then Prototypes/Swim/Buckthought/LysimeterT1_f0u0.apsimx. There is a met file there but you wont need it for this bug.

**Comment by hol430** [comment]
Definitely a bug/oversight. I guess no one has tried to use a LayerStructure with any of these particle size properties. Fixed by #6292. I also notice that the summary has a thickness column instead of a depths column - is this intentional? Perhaps it might be nicer to have a depths column, for consistency with the other soil UIs.

**Comment by sno036** [comment]
Thanks Drew. It would be good to add a depths column (i.e. leave the thickness column in). Nice to have would be thickness auto-calculating in the layering UI itself so that it is easier to see that a sensible pattern has been set up. 

At some point in the future it may be needed to set up an indicators for a smoothing of hydraulic properties in the layering component to overcome some stability issues. Will discuss this more if/when it is needed.
