### ISSUE TITLE
Recent changes break CLEM UI

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6368]
The latest updates produces a number of serious issues for CLEM users
I have reported them here but they can have links to other issues provided as identified

1. All property tabs (in CLEMPresenter) no longer display so users cannot access the properties of models. Probably because of some hard coded links to SimpleProperty that have not been updated with name change.
2. My window expands to screen width (or wider than both screens) when I click on CLEM model
3. The new fonts are all bury and much bigger (more than double the height) than the text. Is this the intended font size?
4. I get an error after sitting for a minute or two with CLEM presenter open
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
5. Can someone explain the recent changes to scroll bars as many CLEM views do not work now and will need to be updated to scroll correctly.

**Comment by lie112** [comment]
I or someone can can fix the missing property presenter
Line 76 of CLEMPresenter should be
`                        propPresenterName = "UserInterface.Presenters.PropertyPresenter";`

I've broken my current working as I accidently pulled changes to my working branch

**Comment by lie112** [comment]
There's also a new error on a Presenter.Detach that tries to save changes and causes an object not found error

**Comment by lie112** [comment]
Sorry I am mucking things up. I thought I created a new pull request with the fix for #1, but it has added it to my last open request that I thought had been merged.

**Comment by lie112** [comment]
Is this the intended look of icons?
![image](https://user-images.githubusercontent.com/19215637/115174031-a29d6880-a107-11eb-863a-8772c7848122.png)

**Comment by hol430** [comment]
> My window expands to screen width (or wider than both screens) when I click on CLEM model

I'm having trouble reproducing this one...and I can't think what would cause that off the top of my head. Which node in which file are you clicking on? Is it any clem-related node? Is this happening under .net core or .net framework (or both)?

> The new fonts are all bury and much bigger (more than double the height) than the text. Is this the intended font size?

Fonts should be a user-controllable option (accessible from the settings dialog). I don't *think* anything has changed here recently - can you double check what your font size is set to? (And send a screenshot of the strange fonts?). I recall someone else in csiro mentioning strange fonts recently, but can't remember who. If I recall correctly it happened after a windows update, and other applications were affected as well, but it was all fixed after a reboot. Might be worth a try.

> I get an error after sitting for a minute or two with CLEM presenter open
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

This usually indicates a segfault in the gtk code, often due to our abuse of the API. Are there any Gtk-CRITICAL warnings/messages in your ApsimNG output when this occurs?

> Can someone explain the recent changes to scroll bars as many CLEM views do not work now and will need to be updated to scroll correctly.

This is caused by #6343. Previously, the explorerview would add the view into a ScrolledWindow widget with the scrollbar policy set to 'automatic'. This was useful in that the views being added to the right-hand panel didn't need to worry about scrolling too much, but the problem with this approach was that some views wanted to handle scrolling differently, and this parent scrolled window was getting in the way. For example, the experiment view contains a treeview (inside its own scrolledwindow), with other controls above and below the scrolled window, so that when there are a large number of simulation names inside the treeview, the user can scroll through the simulation names without scrolling away from the other controls on the screen. With the old behaviour, there would actually be two scrolled windows, which in some situations could result in two scrollbars appearing.

> Is this the intended look of icons?

That's not how they're supposed to look...when I try running on the .net framework build (as you are?) they look normal, but when I try the .net core build, I get what you're seeing. On windows it seems to be the other way around for some reason. I'll look into it anyway - I don't think it's a problem on your end.

**Comment by lie112** [comment]
Expanding window went away after a restart as I cannot repeat the problem. I'll do a restart in future.
The error appears to have gone away as well.

I meant the icons were fuzzy not the font. The fonts are fine.
I can't get the icons to display properly in either .net or core3.1

Am I correct that you have created GtkScrolledWindows to wrap your views and handle the scrolling. I am working out where to place the scroll bar in my clemPresenter that handles the tabs. It must be in each tab. I am creating some of my views on the fly in the code.

I also am looking into where the propertyPresenter view is set to null with the latest changes in my MiltuModelPropertyPresenter as the view.SaveChanges fails as view is not set.
