### ISSUE TITLE
Running APSIM on a Mac

### ISSUE THREAD

**Issue by femiguez** [APSIMInitiative/ApsimX#6378]
A few observations about running APSIM NG on a Mac.

1) Recent changes require upgrading mono to the latest version. I now have 6.12 (before I had 5.18). Perhaps this is useful information for others.

2) Since Oct from last year the APSIM icon is not associated with the app and instead a generic 'app' icon is displayed. A minor detailed, I know.

3) (This has always been the case, but I thought I would mention it). When opening the app I get the message that this is from an unknown developer, so I have to go to security and allow the use of the app. However, I think I have been able to run APSIM at the command line through mono without the need to do this authorization. Again, a minor detail and don't know if there is an easy fix.

Just posting these here in case it is useful information. Thanks!

**Comment by hol430** [comment]
Thanks for reporting these @femiguez - I'm hoping to look into them soon. Let me know if you notice any other oddities when running on mac.

Copying in an issue reported in #6833 so I don't forget it when looking into the mac problems:

> I'm not sure if this is related, but in version 2021.10.11.6842 on Mac the arcs in the directed graph in the RotationManager node are not visible. Interestingly, they are visible in the Nutrient node (under Soil).
> ...
> Open the 'Rotation.apsimx' example (APSIM2021.10.11.6842). Then click on 'RotationManager' (under Mar -> Mar -> field). I see the nodes (Maize, Wheat, initial, WinterFallow) but not the arcs. If I try to add an arc, nothing happens (I think the arcs is added, but not visible). It seems to run fine, so it must be a GUI issue. The issue is still there if I try to add a RotationManager using 'Add Model'.

**Comment by hol430** [comment]
> Recent changes require upgrading mono to the latest version

Mono is no longer a dependency of apsim, and these days we bundle the required runtime in the mac installer

> the APSIM icon is not associated with the app and instead a generic 'app' icon is displayed

Fixed in #7202

> When opening the app I get the message that this is from an unknown developer, so I have to go to security and allow the use of the app. However, I think I have been able to run APSIM at the command line through mono without the need to do this authorization. Again, a minor detail and don't know if there is an easy fix.

From what I can see, fixing this would require us to join apple's developer program, so this probably won't be fixed in the forseeable future. The 2 workarounds are to run from command line, or to right-click/control-click on the application and click open (rather than double-clicking). This will give you a prompt to trust the application or not. This also requires you to go to settings -> security & privacy -> allow apps downloaded from app store and identified developers
