### ISSUE TITLE
Why is N2O loss from nitrification (in Nutrient) set to zero?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6410]
Kia ora @hut104 - looking at N2O losses from Nutrient, there is a comment that losses from nitrification are set to zero. Was there a reason for this? And if there was a reason can we revisit? 

My thoughts - set the default value to 0.01 (1% of N nitrified, I need to verify but I think that is the generally no-better-information value) and allow users to override (at present it is read-only).  

Your thoughts?

**Comment by sno036** [comment]
PS - there is a constant on the DayCent function that Thorburn et al. identified as likely needing site-specific values. The current is fine as a default but it should be user settable.

**Comment by hut104** [comment]
The flow is set to zero because that is the approach used in SoilNitrogen.
Nutrient was added to reproduce the existing model.  Testing will be required for changes such as this.

Almost all N from the decomposition of N from plant material passes into the NH4 pool first and is nitrified from there to accumulate as NO3 until taken up (generally - though some plant models take up NH4 it is only usually after some period of time after the previous crop and NO3 pools end up larger than NH4).
That being the case, all mineral N starts as NH4.  Adding a 1% loss to this flow may impact on the overall N budget.  The impact of this change will need to be assessed on the complete APSIM test set prior to adoption.  Would require tests for long term simulations and checking of relative contribution of nitrification and denitrification to N2O.


________________________________
From: Val Snow ***@***.***>
Sent: Wednesday, 5 May 2021 10:47 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Huth, Neil (A&F, Toowoomba) ***@***.***>; Assign ***@***.***>
Subject: [APSIMInitiative/ApsimX] Why is N2O loss from nitrification (in Nutrient) set to zero? (#6410)


Kia ora @hut104<https://github.com/hut104> - looking at N2O losses from Nutrient, there is a comment that losses from nitrification are set to zero. Was there a reason for this? And if there was a reason can we revisit?

My thoughts - set the default value to 0.01 (1% of N nitrified, I need to verify but I think that is the generally no-better-information value) and allow users to override (at present it is read-only).

Your thoughts?

**Comment by sarchontoulis** [comment]
@sno036 @hut104 in some datasets from Iowa the 1% N20 from NH4 helped but not in all cases. Another challenge I see is the N20 production by depth in wet soils (with shallow watertables). Something to be considered if changes/tests are to be made.

**Comment by sno036** [comment]
@sarchontoulis - agree. There will not be much of a fix for that until SWIM is in action.
