### ISSUE TITLE
User interface become not responding so frequently

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#6419]
i found the user interface become not responding so frequently when i click a folder with several plots in it. Need to increase the stability of the user interface or visualize the plot only when you click it. I guess refreshing many plots at the same time causes lots of issues.

**Comment by junqi108** [comment]
![image](https://user-images.githubusercontent.com/13222562/117225240-fa590500-ae65-11eb-98a2-d43fee7e6b9f.png)
:-)

**Comment by hol430** [comment]
The UI will freeze when you click on graph(s) while it loads the data. This has always been an issue but there have been several graphing speedups over the last 6 months, so this should hopefully be a bit more bearable now. Do you have a sample file in which this is still too slow?

The screenshot above would be caused by copying the text of this issue and pasting it onto a model in the simulations tree - as indicated by the error message.

**Comment by junqi108** [comment]
Hi Drew,
thanks for the message. I am currently switching to Linux system and haven't well set up the APSIM environment yet. I may contact you later if i met problems in setting up in Linux.
The grapevine model is usually slow, you can have a try first. I will update you later.


Ngā mihi,
Junqi
________________________________
