### ISSUE TITLE
Need for simple multiline text box with word wrapping  in property presenter

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6465]
I am in need of a plain multiline text box in the property presenter as we cannot allow the commas in the text (SQL statements of ReportQuery) to be stripped away and converted to \r\n by the current multiline box functionality.
I noticed that GTK3 has a text view which will fulfil the task
https://python-gtk-3-tutorial.readthedocs.io/en/latest/textview.html
Or, is there there a way to specify the characters used to split the initial text string into lines in the PropertyType.MultiLineText?

**Comment by hol430** [comment]
Currently no way to specify which characters are split on. What does your property look like? If your property is a string (not string[]) then it looks like it should just work. If you want a string[] that splits on newlines rather than commas that might be possible with some careful changes to the PropertyPresenter and StringToObject() function (which lives in APSIM.Shared).
