### ISSUE TITLE
Column data type of observations in the sqlite database

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#6521]
In the barley.db, the data type for column `Observed.Barley.AboveGround.N` is `text` in table `AustraliaHarvestObsPred` is `text`, but `real` in the table `HarvestObsPred`.

I guess it is caused by there are no data in table `AustraliaHarvestObsPred`. 

Is it possible to use `real` in the observation columns to easily post-process? 

![image](https://user-images.githubusercontent.com/1657381/120566291-45107180-c452-11eb-8361-c72535798c79.png)

**Comment by hol430** [comment]
This can sometimes be caused by having the wrong data type in the spreadsheet. Can you try changing it to real/numeric type in excel, then refresh the datastore in apsim?

We need to respect the datatype coming from the spreadsheet, which will sometimes be text - e.g. in a cultivar or simulation name column.

**Comment by byzheng** [comment]
I have managed to convert them into numeric values in R and understand the text might be used in some columns. 

Could we convert into the same types when observed values matches predicted values?
