### ISSUE TITLE
Topographic wetness index

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#6543]
A question from one of the forestry projects:
Does APSIM utilise topography to account for surface and sub-surface run-on ? As plantation productivity in some break-of-slope zones seem to be more productive than otherwise expected from rainfall alone.
A topographic wetness index is available in SLGA data, I believe. 

I don’t think APSIM does that, i.e. uses a topographic wetness index. Has anything be published along those lines with APSIM? Are their any current projects working on that?

I think the catchment parameters in SoilWater are used for lateral drainage only – not lateral refill – correct?

**Comment by hut104** [comment]
In classic, one could have runoff becoming run on for another paddock.  Similarly, subsurface flow from perched water tables could become lateral subsurface inflow into a layer.  This was used in the CSIRO product called “Flush”.
Not all elements of this may be functional within NG until real applications are developed (ie these functions have not been prioritised as yet).  However, it may be possible to write scripts to route water between zones.

From: sme016 ***@***.***>
Sent: Friday, 11 June 2021 9:24 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Topographic wetness index (#6543)


A question from one of the forestry projects:
Does APSIM utilise topography to account for surface and sub-surface run-on ? As plantation productivity in some break-of-slope zones seem to be more productive than otherwise expected from rainfall alone.
A topographic wetness index is available in SLGA data, I believe.

I don’t think APSIM does that, i.e. uses a topographic wetness index. Has anything be published along those lines with APSIM? Are their any current projects working on that?

I think the catchment parameters in SoilWater are used for lateral drainage only – not lateral refill – correct?
