### ISSUE TITLE
Refreshing datastore in gui doesn't erase old data

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6586]
Right-clicking the datastore in the gui will re-run the post-simulation tools but won't run a CleanCommand because no simulations are run.

**Comment by lie112** [comment]
This also relates to discussion in #6577 
Does the post simulation tool run if the simulation fails due to an error?

I'm still doing more investigation as to the problem of Messages table in datastore not being cleared as it affects the way I report errors from validation and has annoying carryover errors for users (especially in descriptions that do not have access to the running model objects but relies on the information stored in the database).

As far as I can tell

- messages is set to null in Summary in Commencing
- This is initialised if anything is added (including simulation successfully terminated)
- In Completed this is written to storage?.Writer?.WriteTable(messages);
- I was just trying to learn when and where the table in the database is cleaned up and old data is deleted. It seems to me that _Messages is never emptied for a single CLEM simulation. The Clock/timestamp/Simulation terminated normally/0 entry is appended to the _Messages table every time I run a simulation checkpoint=1 simulation =1.

Maybe it looks in the datastore and realises all entries are for checkp = 1 and simulation = 1 and doesn't delete anything.
I would expect the messages table to be deleted on run, and left to append if multiple runs performed with different simulation and checkpoint ids

**Comment by lie112** [comment]
This problem seems to also exist for _InitialConditions with repeated Clock Start and End down the table as each is added to the table not cleared

**Comment by hol430** [comment]
> Does the post simulation tool run if the simulation fails due to an error?

It should do. If that's not happening, I'd call that a bug. Note that summary is not a post simulation tool, although summary should also save its data to the datastore even if the simulation fails with an error. (Because the Completed event is fired from Simulation class inside a finally block.)

> I was just trying to learn when and where the table in the database is cleaned up and old data is deleted.

The tables are cleaned by a CleanCommand which is issued by SimulationGroup, well before any simulations are run. The problem is that this only occurs if simulations are going to be run; so it doesn't happen when refreshing the datastore in the GUI because this doesn't cause any simulations to be run.

I think #6587 fixes all of this, however I seem to have introduced a different problem.

**Comment by lie112** [comment]
This may also be an issue that you have fixed.
When I generate a exception in "Completed" I get the following issue
Seems it's trying to save the Simulation Name to the id column
Finally tracked down this issue a user was getting reported as a very different error based on the old stuff still in the _Messages table I think.

---> (Inner Exception #1) ERROR in file: C:\Users\may137\CSIRO\NEXUS project - General\Bioeconomic modelling\CLEM_JuliaCreek_Baseline_2 August.apsimx
Simulation name: JuliaCreek_Baseline
Models.Core.SimulationException: Error while performing simulation cleanup ---> System.ArgumentException: Input string was not in a correct format.Couldn't store <JuliaCreek_Baseline> in CheckpointID Column.  Expected type is Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

**Comment by lie112** [comment]
Rather than delete a  comment. 
Ignore the last post as this error has now gone away.

**Comment by hol430** [comment]
I'm still able to reproduce - the problem seems to be that the messages table is being mutated when it's being passed into the call to `storage.Writer.WriteTable()`. The storage writer is adding a checkpointID column to this table which mucks up our expectations about the column structure. The simple solution is to pass in `messages.Clone()` instead.

However, I think that any messages added to this table after the summary handles the Completed event will ultimately be ignored anyway.

**Comment by hol430** [comment]
Out of interest, why does the report query need to run in the completed event? What's wrong with running earlier than this? (e.g. EndOfSimulation)

**Comment by lie112** [comment]
No reason. I guess Shaun V used the event link in Reports (OnCompleted) when creating the original CustomSQLReported as it was assumed that's where the report needed to be done. Report query does assume that all reports have been created before it is called as the SQL statements often need the table to be present in the database to work. They are often nested or below the reports they rely on in the tree structure therefore defining creation order.

**Comment by hol430** [comment]
Ah. Yes, that will indeed be a problem, as on one hand, reporting on EndOfSimulation is common, and on the other hand, writing to summary doesn't necessarily work during/after the Completed event as you've discovered. Perhaps this should be considered a bug, but if so, when should summary write to the DB? We could add another event for this which occurs after the completed event. Or we could have summary write its data to the DB immediately, during the calls to `WriteMessage()`.

Perhaps create a separate issue for this.
