### ISSUE TITLE
Wheat documentation

### ISSUE THREAD

**Issue by iMarang** [APSIMInitiative/ApsimX#6605]
Hi
There are a few parts of the APSIM wheat model docs that I don't understand.  In particular:

1. After 3.4.11 Ripening phase is vernalisation
2. The material after the tables in 3.4.14 is repeated 7 times and then has radn_mol_per_m2 stuck on the end
3. Several sections have equations with letters as operators (e.g., 3.5.5 has "d" between components, while 3.8.2 has "p" between them)

I understand the contents are automatically pulled from the code, so the first two are not big problems, but 3 is more of an issue.  Can you advise what the operators are meant to signify?

**Comment by hol430** [comment]
You're doing well if there's only a few parts of the wheat autodocs that don't make sense.

1 and 2 should be easy enough to fix. I'm not sure about 3 - section 3.5.5 looks normal to me. Does it look different for you?

![image](https://user-images.githubusercontent.com/36427516/124217533-dd764080-db3b-11eb-8a1a-dbc99e78b8cc.png)

**Comment by iMarang** [comment]
<img width="943" alt="Screen Shot 2021-07-02 at 2 14 14 pm" src="https://user-images.githubusercontent.com/22802468/124219847-2c25d980-db40-11eb-9fe7-0060c4181376.png">

That makes sense, "d" should be divide and "p" is plus? The multiply and subtract operations appear to be listing correctly.

There's a few other joys (e.g., find and replace should be done for calcualted), but these edits help, thanks

**Comment by hol430** [comment]
How bizarre. Can you link me to the pdf you're viewing? (Is it [this one](https://apsimdev.apsim.info/ApsimX/Releases/2021.06.22.6357/Wheat.pdf)?)

**Comment by iMarang** [comment]
Yes it was that one.  Interestingly when I view it now it works fine.  Must've been a problem with the pdf viewer I used before.

I did have another document related conundrum however ... **3.5.6 MeanPhyllochron** is fairly confusing.  It mentions that MeanPhyllochron is the moving average of Phyllochron over a series of 300 days.  It then mentions two variables for which we have no information (and I've looked through the code and can't find any mention of them).

StemSenescenceAge = 0 ()
MaxLAR = 0.021 ()

What are these?  How are they related to the moving average of Phyllochron?  My understanding of the purpose of the phyllochron is to increment growth development; a way of converting summed temperature over time into a meaningful biological signal (the number of leaves generated).  While senescence would play a part in this total developing over time, I've no idea with MaxLAR is.  This is one area the documentation could do with some elaboration.

**Comment by hol430** [comment]
These are separate to the MeanPhyllochron section - if you have a look in the wheat model in the gui, if you look under Structure you'll see them just beneath MeanPhyllochron. I'm not sure why they don't have their own headings - probably an autodocs bug.

As for what they do...maxLAR seems to be used by some components which aren't used in the wheat model (CAMP, CalcCAMPVrnRates, LARPTQmodel, and PTQPhyllochron). @HamishBrownPFR or @byzheng  may be able to comment on what these models do, as I see their names next the files in the git logs.

The ApexBase model references a child called stemSenescenceAge, but since this particular StemSenescenceAge isn't a child of an ApexBase model, I would hazard a guess that it's also unused.

**Comment by iMarang** [comment]
Ah, ok.  Thanks for looking into it.  I'll ignore them for now.

**Comment by par456** [comment]
Closing as the Wheat documentation has been refactored since and these issues dealt with.
