### ISSUE TITLE
Multi-process option

### ISSUE THREAD

**Issue by femiguez** [APSIMInitiative/ApsimX#6624]
In previous versions of APSIM NG there was an experimental multi-process option for running jobs, but that option has disappeared in recent versions. Will this be available in the future? Thanks!

**Comment by hut104** [comment]
I think you will find that this option is now the default for all simulation execution.  (ie we removed the old default)

________________________________
From: Fernando Miguez ***@***.***>
Sent: Friday, 9 July 2021 5:22 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Multi-process option (#6624)


In previous versions of APSIM NG there was an experimental multi-process option for running jobs, but that option has disappeared in recent versions. Will this be available in the future? Thanks!

**Comment by hol430** [comment]
More precisely, the multi-process is no longer needed. [This comment](https://github.com/APSIMInitiative/ApsimX/issues/5312#issuecomment-645115591) has some background info on the old multi-process job runner, which is no longer required because server-mode garbage collection is now the default (except in mono builds - so if you're running on Linux/mac machine with many CPUs I strongly recommend using the .net core version).

**Comment by femiguez** [comment]
Thanks Neil and Drew! That is very helpful!
