### ISSUE TITLE
GraphPresenter Error  no such column: SimulationID

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#6723]
It appears that after a recent update of APSIMX, I'm experiencing some difficulties with the plot function, i.e., no plot will show up with following error:

```

System.Exception: Error obtaining data from database:  ---> APSIM.Shared.Utilities.SQLiteException: no such column: SimulationID
   at APSIM.Shared.Utilities.SQLite.Prepare(String query) in C:\GitHub\APSIMInitiativeX\APSIM.Shared\Utilities\SQLite.cs:line 652
   at APSIM.Shared.Utilities.SQLite.ExecuteQuery(String query) in C:\GitHub\APSIMInitiativeX\APSIM.Shared\Utilities\SQLite.cs:line 546
   at Models.Storage.DataStoreReader.GetData(String tableName, String checkpointName, IEnumerable`1 simulationNames, IEnumerable`1 fieldNames, String filter, Int32 from, Int32 count, IEnumerable`1 orderByFieldNames, Boolean distinct) in C:\GitHub\APSIMInitiativeX\Models\Storage\DataStoreReader.cs:line 290
   at Models.GraphPage.ReadAllData(IStorageReader storage, IEnumerable`1 series, List`1 simulationDescriptions) in C:\GitHub\APSIMInitiativeX\Models\Graph\GraphPage.cs:line 166
   at Models.GraphPage.GetAllSeriesDefinitions(IModel parent, IStorageReader storage, List`1 simulationFilter) in C:\GitHub\APSIMInitiativeX\Models\Graph\GraphPage.cs:line 49
   at UserInterface.Presenters.GraphPresenter.DrawGraph() in C:\GitHub\APSIMInitiativeX\ApsimNG\Presenters\GraphPresenter.cs:line 106
   --- End of inner exception stack trace ---

```
The simulation was run successfully and the database appears to be intact. The graphs show up sporatically and I have no idea what is causing that. 

@hol430 Dear Drew, just wondering if you might know what is causing this please?

The simulation can be accessed from:
https://github.com/Chloe0317/APSIMsims/tree/main/nvol 

Thanks heaps!

**Comment by hol430** [comment]
That error is caused by the lack of a simulation name column in the observed data. Normally, apsim will try and only show data on the graphs for the simulations which are in scope. In this case, it's unable to determine to which simulation the Paddock1 data belongs, so it gives an error rather than displaying nothing for that series.

As a temporary workaround, you could delete (or disable, I suppose) the Paddock1 series under the graph. Or add a SimulationName column to the observed data and set it to 1_Johnson or 1_Schwenke in all rows.

@hol353 - what should happen in this case? If a table doesn't contain a SimulationID column, should it be shown on all graphs? Or none? It seems strange to me to drop a graph on a particular simulation, and have potentially unrelated data appear.

**Comment by hol353** [comment]
If the SimulationName column is missing in the observed data then it shouldn't be shown I guess. I can't help wondering if there is a use case where the user might want to simply plot the observed data that doesn't have a simulation name. I guess not.

**Comment by hol430** [comment]
That could be the case here - @Chloe0317, does your observed data (ie in table Paddock1) belong to a particular simulation?

**Comment by Chloe0317** [comment]
Thank you Dean @hol353 and Drew @hol430 both for the clarification!

We have implemented two differrent nitrogen volatilisation methods from literature, Paddock1 is the observed data, whereas 1_Schwenke and 1_Johnson denote simulations run using the two different methods. 
I'm thus trying to plot the observed data with the two different simulation results for comparison.
 
The simulation plots are working fine once I have disabled Paddock1, adding a SimulationID/SimulationName column doesn't seem to work though.

What would you suggest as a more elegant way to do this please? Thanks heaps!

**Comment by hol430** [comment]
That seems reasonable. @hol353 we could change this so that the scoping rules don't apply to tables lacking a simulation name/ID column. Of course, data from that table would only show up in graphs if the user explicitly added a series for that table on the graph. And even then, they could still setup a manual filter anyway, if need be. Let me know what you think.

**Comment by hol353** [comment]
Yep that sounds ok. If you implement this make sure you create a unit test for it.

**Comment by hol430** [comment]
I'll do that. @Chloe0317 did you refresh your datastore after adding in the SimulationName column? I changed my Paddock1 sheet to look like this this:

![image](https://user-images.githubusercontent.com/36427516/129828623-857cbafc-88e7-4be3-bec0-2e819712149c.png)

Then refreshed the datastore and the observed data started showing up for me.

**Comment by Chloe0317** [comment]
Dear Drew @hol430, sorry i didn't. Yes, the simulation is showing up once I have refreshed the datastore. Thanks!
