### ISSUE TITLE
Could not find PO table in D:\AGRI SOFTWAR\APSIME7.10\masoud\croptimizer wheat1.apsimx. Has the simulation been run?

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#6811]
observed table has been funded by predicted/observed module but tests child find noting? every possiblity tried.

**Comment by hol430** [comment]
Can you upload your .apsimx and observed data files?

**Comment by masooandy** [comment]
here it is
[wheat1.zip](https://github.com/APSIMInitiative/ApsimX/files/7215881/wheat1.zip)
thanks

**Comment by hol430** [comment]
- The .apsimx file you sent doesn't contain a predictedobserved or a tests node, so it runs without error
- The observed data has a simulation name column, but every value in this column is just "Simulation". These simulation names need to match the simulation names in apsim if you want to use this data as the observed table for a predicted/observed tool

**Comment by masooandy** [comment]
you right .my fault. generate .apsimx files made it  and I just zipped and send it.however please check these new ones. three sheets are different tries

**Comment by hol430** [comment]
Ok, observed data looks good. The problem now is that you've set all three fields to match on in the predicted/observed node. What these dropdowns do is tell apsim how to match the predicted rows up to the observed rows. E.g. if you set the first field to Clock.Today and leave the others blank, apsim will match a predicted row to an observed row if they have the same value for Clock.Today.

In your file, you've set field1 to biomass, field2 to Yield, and field3 to Clock.Today, so apsim will match a predicted row to an observed row if the two rows have the same value for biomass, Yield, and Clock.Today. There are no rows in either table for which this is true, which is why you don't get a predicted/observed table in your DB after the simulations are run.

So I'd suggest leaving field2 ("second field name to use...") and field3 ("third field name to use...") both empty, and setting field1 to Clock.Today, like so:

![image](https://user-images.githubusercontent.com/36427516/134827125-1138c682-a076-411d-a1be-cf8efb1c3e77.png)

I tried this and ended up with a p/o table with results after rerunning the file.

**Comment by masooandy** [comment]
thanks a lot https://github.com/hol430 .problem solved.god bless you.
