### ISSUE TITLE
Missing dependences in the deb package?

### ISSUE THREAD

**Issue by frank0434** [APSIMInitiative/ApsimX#6840]
Hi @hol430, 
We tried to rebuild a singularity container for the HPC system. 
The build was fine.  But we seem to have a dependence exception. 

**System.DllNotFoundException: Unable to load shared library 'sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsqlite3: cannot open shared object file: No such file or directory**

Wondering if the 'sqlite3' library is not in the deb package list? 

Full error message below. 
Thanks in advance for any feedback.

```
./apsimx-2021.10.8.6835.sif --verbose Base.apsimx
----------------------------------------------
System.Exception: Error in file:/powerplant/workspace/cflfcl/github/ShinyClimateChange/Projects/P009_LucerneNZ/LocalParameters/Base.apsimx
 ---> System.Exception: Error reading file /powerplant/workspace/cflfcl/github/ShinyClimateChange/Projects/P009_LucerneNZ/LocalParameters/Base.apsimx
 ---> System.DllNotFoundException: Unable to load shared library 'sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsqlite3: cannot open shared object file: No such file or directory
   at Models.Core.Run.SimulationGroup.<>c.<Initialise>b__28_0(Exception e) in /tmp/ApsimX/Models/Core/Run/SimulationGroup.cs:line 182
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, Action`1 errorHandler, Boolean initInBackground, String fileName) in /tmp/ApsimX/Models/Core/ApsimFile/FileFormat.cs:line 113
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in /tmp/ApsimX/Models/Core/ApsimFile/FileFormat.cs:line 66
   --- End of inner exception stack trace ---
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in /tmp/ApsimX/Models/Core/ApsimFile/FileFormat.cs:line 80
   at Models.Core.Run.SimulationGroup.Initialise() in /tmp/ApsimX/Models/Core/Run/SimulationGroup.cs:line 183
   --- End of inner exception stack trace ---
ERRORS FOUND!!
Elapsed time was 0.9 seconds

```

**Comment by hol430** [comment]
sqlite3 should be in the .deb file's dependencies, however some distributions may be giving the file a version ABI suffix (e.g. `libsqlite3.so.0`). APSIM will be looking for exactly `libsqlite3.so`. You can check if this already exists by doing something like `ldconfig -p | grep sqlite`.

I think on debian you may be better off installing the `libsqlite3-dev` package, as this will give you a `libsqlite3.so` out of the box, but I don't know if the other debian derivatives offer this package in addition to the regular sqlite3 package, which is why I haven't listed libsqlite3-dev as a dependency in the .deb file.

The other way to fix this is to just create a symlink called `libsqlite3.so` in a place that the loader will find it (ie apsim bin directory or `/usr/lib`). E.g. `ln -s /usr/lib/libsqlite3.so.0 /usr/lib/libsqlite3.so`.

Finally, in case it helps, you can see our "official" docker image for apsim [here](https://github.com/APSIMInitiative/APSIM.Docker/blob/master/NextGen/apsimng/Dockerfile). There's not really much in it, but it may be useful to you as a reference.

**Comment by hol430** [comment]
The .net runtime is indeed necessary to run apsim, however as far as I can see there's no package for this in the official repos (for current debian) so it needs to be installed from microsoft's repos...let me know if I'm missing something here. Also, aspnetcore-runtime may be a bit excessive, you should be able to get away with just dotnet-runtime-3.1 (unless of course you need the asp runtime for something else).

I'll add libsqlite3-dev to the deps when I get the chance - should be safe enough as you say.
