### ISSUE TITLE
Truncated column results in data display from Report

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6904]
I have a column named "Resource" generated by one of my reports. The column contains string entries containing a full stop (e.g. Finance.BankAccount and these values show up when I inspect the database in Browser DB. When this table displays in the PagedDataPresenter the leading characters before the full stop are removed. The columns do not fill the screen so it doesn't seem to be a column size issue.  I have looked through the code but cannot find where any truncation happens as when I inspect the column data at various places I can see the full string. This does not happen for the Category column in the same table

![image](https://user-images.githubusercontent.com/19215637/139651913-ccc5f63e-1043-481e-b0bb-414a3b323a04.png)

**Comment by hol430** [comment]
Looks like this is happening because we calculate the column width based on the width of the column header and the cells in the first row. So if you have a column which has cells further down with contents wider than that of the first row, you will get truncated cells.

The obvious solution is to calculate the width of every cell up front and use the max for each column as that column's width. This is extremely slow.

@hol353 any thoughts? If it helps, here is a file which reproduces the problem.

[report-repro.apsimx.txt](https://github.com/APSIMInitiative/ApsimX/files/7456893/report-repro.apsimx.txt)

**Comment by lie112** [comment]
Ok, that makes sense. The full stop must be considered a string break point in GTK. I really couldn't find any reason for the truncation and could see the full string in the database. This seems like an odd behaviour by GTK. Is there a way to resize the columns?
There must be a default width somewhere (or an autofill calculation) as "Date" is wider than the content and it looks like "Activity" has actually increased wider than the default size based on the content as there was no breakpoint such as a "." in the content of the Activity column.
Can we remove the string breakpoint character from this GTK so it resizes on full string? Maybe it's the wrap width that needs to be turned off

Gtk.CellRendererText:wrap-width
Specifies the minimum width at which the text is wrapped. The wrap-mode property can be used to influence at what character positions the line breaks can be placed. Setting wrap-width to -1 turns wrapping off.
https://gnome.pages.gitlab.gnome.org/gtk/gtk4/class.CellRendererText.html

**Comment by hol430** [comment]
It's not a gtk problem, as we're not using a stock gtk widget. The sheet widget is a custom widget which we've written to display tabular data, as the builtin GtkTreeView widget doesn't perform well with the large datasets which we need to display. The wrap-width property is not used because we're not using CellRenderers. The full stop is also unrelated - in my example .apsimx file I posted above I have a long string of 'x' characters which gets truncated. I think it's a coincidence that the strings in your screenshot above happen to be truncated right before the '.' character.

> There must be a default width somewhere (or an autofill calculation) as "Date" is wider than the content and it looks like "Activity" has actually increased wider than the default size based on the content as there was no breakpoint such as a "." in the content of the Activity column.

All columns have some internal padding - that's probably what you're seeing here. There's certainly no default width - it's all calculated from the first row of data (and the column headings). This all happens in [`CalculateColumnWidths()`](https://github.com/APSIMInitiative/ApsimX/blob/master/ApsimNG/Views/Sheet/Sheet.cs#L440) in Sheet.cs.

You might be on to something with manual resizing of columns. It wouldn't really be ideal but should be better than what we have now.

**Comment by lie112** [comment]
Thanks, that makes sense. The columns with a large string in the header or first row are correct.
The only way to fix it is probably to check all data on creating the table widget. You could quickly get the largest count of characters in entries from each column by SQL (select max(datalength(YourColumn)) from YourTable) and use this as a padded string of a given character to estimate the best width of each column. This saves running through each row doing cell size calculations

**Comment by par456** [comment]
Three cells are checked, top, middle and bottom. This may still occur with lots of different sized values, but would be too slow to check every row.

**Comment by lie112** [comment]
What about a quick sql query check for longest record in all character columns? This could even be added as a view for each table in the database for easy access during redraw based on Presenter without any great overhead. This would take advantage of the fastest calculations based on SQLite.
This issue has always been a problem when reporting enums by string (which was added over just the integer value)  in the output as the column is often truncated. The alternate here would be to allow functionality to report a table with id and name for enums and link this via the integer id back to the main table. This could reduce database file sizes significantly for large runs.
