### ISSUE TITLE
Data display clock.today bug?

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#6923]
Just noticed an odd behaviour of the datastore in my simulation. 
The clock ends up repeating itself in the display so I cannot interrogate the data via the gui. 
@hol430 not sure what's causing the bug though it should be related to the display since the simulation ran fine and the results can be imported into R/excel correctly. Thanks!

![1636070320(1)](https://user-images.githubusercontent.com/63323287/140436425-376052b2-1997-484d-b007-0ec5553bcf6f.png)

**Comment by hol430** [comment]
I think the data is displayed in the order in which it's written to the DB, rather than by Clock.Today. That said, I'm not sure how the data might be written out of order in the first place. Can you upload your .apsimx file?

**Comment by Chloe0317** [comment]
[nvol.zip](https://github.com/APSIMInitiative/ApsimX/files/7480675/nvol.zip)
Kindly see the attached @hol430 
Thanks!

**Comment by hol430** [comment]
I'm not seeing the problem on my computer. Which version of apsim are you using? And does the problem go away if you delete your .db file and re-run everything?

**Comment by Chloe0317** [comment]
Hi Drew,

I'm using the custom build version that was compiled last week. The problem
doesn't go away if I delete the .db file and re-run.
I cannot figure out why this is the case.
My date, time, and region setting are Australian standard settings
(d/mm/yyyy), I'm not sure if that has anything to do with it but cannot
think of anything else.

**Comment by lie112** [comment]
I have noticed an issue with the Writer waiting for 100 entries before it writes all to the database. If you have report entries being written by multiple Zones, the order can get mucked up and you lose the ability to ever sort to the exact order entries were created when there are multiple entries on a single day (in clem's case all entries are on the last day of the month).
Looking at the code it seems there's big performance advantages in writing blocks of entries rather than all the overhead for a single entry every time.
Have we had a good look at reporting to SQLite to look for performance improvements with transactions or is the bottleneck in APSIM retrieving the values to write each entry? Data management could be the next area of cpu saving.
I was thinking about a static instance to track the current record number that could be written to the output such that date isn't the finest level of reporting the occurrence of entries.

**Comment by par456** [comment]
Can't reproduce, if it's still a problem, reopen this issue.
