### ISSUE TITLE
netcoreapp3.1 in the batch mode

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#6955]
It seems we can only compile into netcoreapp3.1 now. Correct me if we still can compile net472.

I need to run models.exe in the batch mode with HTCondor. Could we compile netcoreapp3.1 into self-contained application? I have done a test in a VM withouth netcoreapp installed and get errors for missing library.

I also noticed the runtime of netcoreapp is very slow for the first time in the command line mode. It takes about 1 min in the first time instead of 3 s in the second time. I guess it is related with to search and load libraries.

**Comment by hol430** [comment]
Correct. You can no longer build or run on .net framework unless you checkout an older version of the code. If you want to build in self-contained mode, try `dotnet publish -c Release -f netcoreapp3.1 -r win-x64 Models.csproj` and then copy the contents of `bin/Release/netcoreapp3.1/win-x64/publish/` to your target machine. There should be a Models.exe in there which can be run without a system-wide .net core installation.

The output of the above build command can only be run on windows - if you need to run on another platform, you'll need to substitute a valid [.net runtime ID](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#windows-rids) (e.g. `-r linux-x64` instead of `-r win-x64`).

**Comment by byzheng** [comment]
Thanks @hol430 

I get an error to load "sqlite3" after moving to a new VM and also cannot find sqlite3.dll in the published folder.

System.Exception: Error in file:E:\tmp\test\375e780cabcc4bb7f00f5a9887faa9c8.apsimx
 ---> System.Exception: Error reading file E:\tmp\test\375e780cabcc4bb7f00f5a9887faa9c8.apsimx
 ---> System.DllNotFoundException: Unable to load DLL 'sqlite3' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Models.Core.Run.SimulationGroup.<>c.<Initialise>b__28_0(Exception e) in C:\GitHubRepos\ApsimX\models\Core\Run\SimulationGroup.cs:line 182
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, Action`1 errorHandler, Boolean initInBackground, String fileName) in C:\GitHubRepos\ApsimX\models\Core\ApsimFile\FileFormat.cs:line 113
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in C:\GitHubRepos\ApsimX\models\Core\ApsimFile\FileFormat.cs:line 66
   --- End of inner exception stack trace ---
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in C:\GitHubRepos\ApsimX\models\Core\ApsimFile\FileFormat.cs:line 80
   at Models.Core.Run.SimulationGroup.Initialise() in C:\GitHubRepos\ApsimX\models\Core\Run\SimulationGroup.cs:line 183
   --- End of inner exception stack trace ---
ERRORS FOUND!!

**Comment by byzheng** [comment]
I found sqlite3.dll in the bin\Release\netcoreapp3.1\win-x64. Seems publish command doesn't copy this file.

**Comment by hol430** [comment]
Well spotted - I just checked the windows installer scripts, and it seems that we manually copy in sqlite.dll. It would be better if this were automatic, but for now, if you copy this file into the publish directory, do things work as expected?

**Comment by byzheng** [comment]
Yes it works after I copy it. 

Is a way to reduce the file size of publish folder? Currently I have

**Comment by hol430** [comment]
The publish folder is large because you've built apsim in self-contained mode - that is, you've bundled the .net runtime with apsim, so that apsim doesn't depend on a system-wide .net installation. That's going to take up quite a bit of space by design.

Only thing I could suggest to reduce disk usage would be to not build in self-contained mode - but that of course has its own set of problems :).

**Comment by byzheng** [comment]
Thanks. I need to compile as self-contained mode as models.exe has to be run at a computer without netcoreapp. 

Is there anyway to find out the required libraries to run a simulation without observations?

I noticed System.Net.* are not required to run my simulations.

**Comment by hol430** [comment]
No idea sorry; trial and error would probably be your best bet. You might need to be careful with some libraries - even if they're not required now, that may change in the future. Some libraries may be required for some .apsimx files but not for others.

**Comment by byzheng** [comment]
Thanks for tips. I understand it your concern. Try to save some spaces for easily transferring files over network.
