### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7047]
Hi,

I have created a simulation with replacement of cultivar and soil module. However running leads to the following error: **Object reference not set to an instance of an object**. I am unable to identify the source of the error. 

I attach a screenshot of the details about the error and the simulation file. 

Thank you,
A

![image](https://user-images.githubusercontent.com/68366659/149044259-0b06486f-5bd7-4e31-9264-9992b5a4e4be.png)

[Test.zip](https://github.com/APSIMInitiative/ApsimX/files/7850781/Test.zip)

**Comment by hol430** [comment]
The error is coming from the "reset on sowing" script. The script is designed to work with nutrient, but there is no nutrient model in the soil - it has soil nitrogen instead. Soil nitrogen is the "older" version of nutrient -and it will probably be removed at some point in the future, so the easiest fix here is probably to remove soil nitrogen from your soil and add nutrient instead. You can add nutrient by copying an existing nutrient node from somewhere, or you can right click on your soil -> add model -> nutrient.

@hut104 - when a soil is imported from old apsim, would it be better to add nutrient instead of soilN?
