### ISSUE TITLE
CLEM shutdowns randomly

### ISSUE THREAD

**Issue by yacobbeletse** [APSIMInitiative/ApsimX#7088]
After upgrading APSIM2022.01.6992.0 to APSIM2022.2.7010.0, CLEM is randomly shutting down, notably when I scroll on a graphical display report “ReportActivitiesPerformed”.
I never had this problem in the previous version. Is this a bug?

**Comment by zur003** [comment]
Anything that causes APSIM to randomly shut down is a bug!

**Comment by zur003** [comment]
Possibly not related, but the "Activity" labels aren't aligning with the body of the table, apparently because the headers of the two "parallel" Treeviews have different heights.

![image](https://user-images.githubusercontent.com/11879340/153581775-220896aa-e7e9-4774-acb2-1fcd4d91f64c.png)

**Comment by lie112** [comment]
This is a known issue #6358 along with #6904 where the first row of data and the column name are used to define column width which is often not the true width needed for the column resulting in truncated data and inability to see all information.
I am awaiting the overall APSIM fixes rather than working it out myself.
