### ISSUE TITLE
CLEM: selling milk and tracking activities in multi harvest crops

### ISSUE THREAD

**Issue by yacobbeletse** [APSIMInitiative/ApsimX#7130]
I am encountering two issues with CLEM simulations:

1.	Selling milk with ResourceActivitySell :

I wanted to sell milk by reserving some for households in my CLEM simulations, i.e., sell all except the user-specified amount. I am using the ResourceActivitySell property and Reserve Amount selling style to perform this activity. However, the HumanFoodLedger report shows that surplus milk is sold only once in the first year. In the subsequent months/years, the model sold everything milked instead of selling by reserving the specified amount. Could this be a bug?

2. Tracking activities in multi harvest sequence

The online help crop rotation demonstrates specifying the "first" and "last" harvest in a multi-harvest sequence using a harvest tag column allows multiple harvests and a sequence of crops, and avoids duplication of land preparation and planting after the first harvest. The example clearly shows land preparation and planting performed before the first harvest, and then no activities performed after the first harvest except harvesting. Such an approach is great for cases where only harvesting activity is performed. 

In my case, I am attempting to run Sugarcane-Mustard rotation and I need to track activities such as irrigation, fertilisation etc., after the first harvest (see attached snapshot below after March 2002, in blue dots) until the last harvest (before rotation to the next crop in the sequence). I need this to get the monthly cash flow throughout the year for different activities. However, this does not allow me to track other activities after the first harvest.  Mango is grown in a separate plot/field and Sugarcane-Mustard rotation is grown in another plot/field. Is the rotation meant to track the harvest only? 
![CropRotation](https://user-images.githubusercontent.com/23515057/155273675-3e7059b2-f1d3-41da-8562-00c4a227207c.png)

**Comment by lie112** [comment]
In response to point #2
This is not how the simple rotation model works. Multiple harvests from a single crop is implemented to allow harvesting across a number of months from a single crop, not two full cycles of that crop. Remember these harvests are actually based on grain production form the underlying input files.  For example staggered planting or crop variation may provide grain for harvest across 2 months form a single crop, before we rotate to the next crop. Multiple harvest allows the model to wait for all crop production before switching to the next crop in sequence.

What you are wanting is actually a three crop rotation with Sugarcane/Sugarcane/MustardSeed to achieve this you need a second sugarcane crop in your input with a different name and have two sugarcane and a mustard crop product components in your manage crop activity. This will do what you want. Because they are all single harvest crops you can remove the HarvestTag column from your input datafile.  If you want to do two harvests of the same sugarcane crop you can implement what you currently have. I will need to look at ensuring the various crop tasks can be performed between harvests.

**Comment by lie112** [comment]
point number 2
After reading your message again you are correct in what you are trying to do. It seems the various crop tasks do not respect the second harvest date. I will look into fixing this issue

**Comment by lie112** [comment]
In response to point number 1
You have a timer set for your milking activity that starts in September and repeats every two months from then on. 
This means milking can only be performed in Sept, Nov, Jan, March etc
There's a bug in milking in that it is not currently obeying the timer and only happens when milk is present. I'd have to look deeper into your weaning schedule and lactation curves to see why you only get milk for one month.
The sell milk activity is nested as a child below the Milking activity and so obeys the same timer rules and you can see it is only being performed every second month.
This explains the output provided. 

I have fixed the milking activity timer issue and it will be available soon.

**Comment by yacobbeletse** [comment]
@lie112 thanks and looking forward to the upgrades.
