### ISSUE TITLE
Current .Net version of APSIM NG

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7139]
Does the new approach adopted to move to .Net Core through the upgrade of gtk# version allow APSIM Next Gen to keep up with .Net releases?
I've noticed we're still in C# 8.0 using core 3.1, and I keep trying to use features of C# 9.0 and above.
Is it still a large job to move to the next release with gtk being the hold up or does the new compatibility of Core allow this easier?
We could benefit from the performance improvements in .Net 5 including to system.json.text serialisation, garbage collection and container image size.

**Comment by hol430** [comment]
There is some work involved in changing framework versions, mainly related to the installers, and making sure that users have the required runtimes installed on their machines.

**Comment by hol430** [comment]
I'm going to reopen this. Ubuntu 22.04 was released recently and does not officially support .net core 3.1 (only .net 6+). If we want to support the latest Ubuntu, we'll need to target .net 6.

**Comment by zur003** [comment]
This may be a bit harder to do than would appear at first glance. With APSIM.Shared I tried a simple change of TargetFrameworks to net6.0, but compilation failed because use of BinaryFormatter to serialise/deserialise XML is now considered obsolete, as is some of the web access stuff like HttpWebRequest and FtpWebRequest. I tried changing BinaryFormatter to XMLSerializer, but that failed because it won't serialise Interfaces (like IModel). So there's going to be a bit of work in going to Net 6 beyond just worrying about the runtimes.

**Comment by hol430** [comment]
I guess we do it iteratively. GtkSharp does support .net 6 though, so at least we don't have that headache again.

Moving to .net 6 would probably also force some people to update their dev environments. I'm not sure which older versions of visual studio support .net 6 development.

Another problem is related to building all projects into the same bin directory. This causes problems when publishing in self-contained mode, and it can also cause inconsistent warnings (and, potentially, errors, though I've never seen that) about locked files when building the solution. I'm unable to publish the solution in self-contained mode at all with the .net 6 sdk (whereas with the .net core 3.1 sdk, I can publish but there are problems with the resultant files).

**Comment by zur003** [comment]
My earlier comment was perhaps a bit too negative. Building with .Net 6 generates warnings, not errors, detailing the obsolete features. The warnings can be disabled using suitable pragmas, yielding code that builds and runs. However, it would certainly be better to revise the code to avoid use of obsolete features, for reasons of both improved security and the ability to keep going if the features are completely deprecated and removed in the future. Disabling warnings would just be a way to kick the can a bit further down the road.

**Comment by zur003** [comment]
@hol430 - There is a FTPClient class in APSIM.Shared.Utilities which doesn't appear to be used anywhere in ApsimX. Is it used in some other application? Just asking, because it uses the now-deprecated System.Net.FtpWebRequest class.

**Comment by hol430** [comment]
Yep, FTPClient can be deleted. Nothing I know of uses the APSIM.Shared project in this repository.

**Comment by jal-frezie** [comment]
I had a look at what's involved getting .net runtime 3.1 installed on Ubuntu 22.04 and it is far from trivial! Any way I can avoid having to downgrade Ubuntu on my new laptop? I'm wondering if a virtual machine is the way to go

**Comment by hol430** [comment]
If you don't need the gui, then docker is an option.

Otherwise, the [dotnet-install](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) script should get you out of trouble.

```bash
curl -sSL https://dot.net/v1/dotnet-install.sh >dotnet-install.sh
chmod u+x dotnet-install.sh
./dotnet-install.sh --channel 3.1
~/.dotnet/dotnet --list-sdks
```

**Comment by jal-frezie** [comment]
I installed the runtime using snap, which seemed to work OK but Apsim appears to need the SDK as well:
jaspert@chopper:~/Downloads$ apsim
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
jaspert@chopper:\~/Downloads$ dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.28
  Commit:  ce3350c1cc

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.28 [/snap/dotnet-runtime-31/32/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jal-frezie** [comment]
OK I did as you suggest with the dotnet-install script, added ~/.dotnet to the PATH, used equivs to make a fake dotnet-runtime-3.1 package to satisfy apsim's dependency, and when I run Apsim I briefly see the display then it exits with:

No usable version of libssl was found
Aborted (core dumped)

I understand that the reason for dropping dotnet-runtime-3.1 from ubuntu 22.04 was because openssl 1.1 was lost, but I thought the script downloaded a version with all required libraries statically linked? (I also tried adding the SDK from snap, but then Apsim core dumped straight away)

**Comment by zur003** [comment]
Your other option for now is to do your own build of Apsim, targetting .Net 6.0. I did this today after upgrading to Ubuntu 22.04.1, and it works just fine. Basically all that's needed is to edit the various .csproj files and replace netcoreapp3.1 with net6.0 as the TargetFrameworks.

**Comment by hol430** [comment]
Yeah, I'm surprised that the dotnet-install script doesn't bundle the openssl libs, but I haven't actually put that to the test, as my distribution still provides openssl 1.1 out of the box (for now). I don't know of any real workaround for this problem, other than installing the older openssl in some fashion. You could always build it yourself and tell apsim about it (e.g. via `LD_LIBRARY_PATH`). Something like this might do the job:

```bash
curl https://www.openssl.org/source/openssl-1.1.1o.tar.gz >openssl-1.1.tgz
tar xzf openssl-1.1.tgz
cd openssl-1.1.1o
./config # (possibly with --prefix=someprefix if you want to make install later)
make #-j`nproc`
LD_LIBRARY_PATH=/path/to/openssl-1.1.1o ApsimNG
```

This all highlights the need to finish the migration to .net 6. While core 3.1 is still "supported" by microsoft until the end of this year, that doesn't mean much in the face of distributions jumping ship on the older openssl versions.

**Comment by jbrider** [comment]
https://ubuntu.com/blog/install-dotnet-on-ubuntu

**Comment by jbrider** [comment]
I thought it would inject the article...
Main news below:

# quickly install a bundle with both the SDK and the runtime
sudo apt update && sudo apt install dotnet6
# or cherry-pick only the dependencies you need to develop or run
sudo apt install dotnet-sdk-6.0
sudo apt install dotnet-runtime-6.O
sudo apt install aspnetcore-runtime-6.0

**Comment by jal-frezie** [comment]
zur003 I'd be happy to build my own Apsim targetting .net 6.0 but I'll need to exchange models with other users and that will make things hard with version numbers. Could we actually move the official Linux release to .net 6.0? It seems to be available on Ubuntu as far back as 16.04 according to the Microsoft site. Looks like you have fixed the problems from earlier in this thread.

**Comment by zur003** [comment]
Yes, the problems mentioned earlier have been fixed, although I just noticed that creation of documentation doesn't work unless the PdfSharpCore nuget package is updated to a newer version. There are a number of other nuget packages that could be updated. The transition to .Net 6 might be a good time to do that updating.

@hol430 - what is required to move everything to .Net 6? I think developers would need to move to VS 2022, and we would need to somehow ensure that users have the net 6 runtimes installed.

**Comment by hol430** [comment]
I guess the steps would be

0. Get things working/make sure things still work (e.g. updating nuget packages as you mentioned)
1. Ensure that the jenkins build agents have the .net 6 sdk available
2. Update the installer generation scripts

- The Debian installer just needs to have the runtime version updated in the dependencies of the control file (`ApsimX/Setup/netcoreapp3.1/debian/control`)
- MacOS installer shouldn't need any changes since we bundle the runtime with the apsim distributions, which is achieved via `dotnet publish`
- Windows installer generation script (`ApsimX/Setup/netcoreapp3.1/windows/apsimx.iss`) needs to have the URL to the .net runtime updated

3. Update the dockerfiles over in the APSIMInitiative/APSIM.Docker

There may be other stuff involved, my head is not really in this space at the moment. But that's the obvious stuff that immediately comes to mind.

**Comment by zur003** [comment]
I've started working on updating the nuget packages. For the most part, this has been straightforward, with a few minor API changes along the way. A couple of areas, however, are a bit more challenging:

1. The current `Microsoft.Azure.Storage.Blob` package is now deprecated, with Microsoft advising a switch to `Azure.Storage.Blobs`. That switch is a bit beyond my very limited knowledge of Azure, and I shall leave that conversion to someone else (most likely @hol430). There is a bit of advice on the transition available [here](https://elcamino.cloud/articles/2020-03-30-azure-storage-blobs-net-sdk-v12-upgrade-guide-and-tips.html). The older packages still work for now.
2. `System.Drawing.Common` "should" be upgraded from version 5 to version 6. However, Unix (and Mac?) support is disabled by default in version 6. Microsoft describes the situation [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). Microsoft's advice is to move to either `ImageSharp` or `SkiaSharp` (or to `Microsoft.Maui.Graphics`, but that appears to wrap `SkiaSharp` for its Unix support). We're already pulling `SkiaSharp` into `APSIM.Interop`, so that's probably the path to take for now.

**Comment by lie112** [comment]
.Net 6+ will also provide some additional performance benefits.
One example is specifying sealed keyword for classes and types to improve access speed
See
https://www.meziantou.net/performance-benefits-of-sealed-class.htm
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#peanut-butter

**Comment by zur003** [comment]
I just noticed that Microsoft [ended official support for Net 3.1](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) at the end of 2022. We really should be looking at moving to .Net 6.

**Comment by zur003** [comment]
We're now using .Net 6.0. This issue can (and will) be closed.
