### ISSUE TITLE
Data assimilation for read only parameters

### ISSUE THREAD

**Issue by VicB18** [APSIMInitiative/ApsimX#7177]
Hello,

We have data for the soil temperature and want to use it in a simulation. But SoilTemperature is a model with read only temperature value.
![kuva](https://user-images.githubusercontent.com/47314151/158122999-5890bc15-abaa-4320-80f0-b8a5bfc35331.png)
Is there a way to set the soil temperature value in the simulation?

Thank you

**Comment by hol430** [comment]
You could delete the soil temperature node from your simulation, and have your manager script implement the ISoilTemperature interface. Any model which uses soil temperature should then use your script instead.

The ISoilTemperature interface contains a single property - a double array called `Value`. Your script could look something like this:

```csharp
public class Script : Model, ISoilTemperature
{
    public double[] Value { get; private set; }

    [EventSubscribe("DoManagement")]
    DoDailyCalcs(object sender, EventArgs args)
    {
        Value[0] = 20;
        Value[1] = 30;
        ...
    }
}
```

**Comment by peter-devoil** [comment]
This is a good workaround, but it would be nice to have a set/reset method one day. It was sorely missed in classic as well.

**Comment by VicB18** [comment]
Thank you, Drew, for the explanation. Can you, please, just clarify how to do it?
I added a Manager script with the code you provided.
![kuva](https://user-images.githubusercontent.com/47314151/158362135-a35a60b7-3937-45b0-a92b-6b3e111fccaa.png)
How can I ensure that 

> Any model which uses soil temperature should then use your script instead.

In addition, how can I compare the measured and simulated temperatures?

Thank you

**Comment by hol430** [comment]
I would guess the "object not set" error is due to the Value array not being initialized, which means it will always have its default value of null. (Attempting to dereference the null array would certainly cause that error.) The solution would be to initialize the array before doing anything with it (probably once at start of simulation would be best, rather than doing it every day). The trick will be allocating the correct number of layers - you'll need to make sure this is the same as the number of layers in the soil. E.g.

```csharp
using Models.Soils; // (if not already present)

...

[Link] private IPhysical physical = null;

[EventSubscribe("StartOfSimulation")]
private void OnStart(object x, EventArgs e)
{
    Value = new double[physical.Thickness.Length];
}
```

As for comparing the simulated to measured values....one way to do that might be to use an experiment node. If you're not familiar with the experiment node, there's some documentation [here](https://apsimnextgeneration.netlify.app/usage/factorials/) and an example .apsimx file called Factorial.apsimx which will be included in your apsim installation. The ModelReplacement example in this file is similar to what you're trying to do.
