### ISSUE TITLE
Morris SA on a soil parameters 

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7193]
Hi there, 

I am interested in using Morris SA for sensitivity analysis, but I am facing some challenges which I think are related to how I defined the path to the parameters. 

1) I tested the soil initial water - but I get the following error, which is quite surprising because it is a child to Soil to my understanding. 
![image](https://user-images.githubusercontent.com/68366659/159427653-50f81bb2-7e3f-4570-a3fd-b066c8a60581.png)

2) I tested a parameter (FBiom) with multiple layers - and I got the following error. I tried using parenthesis rather than square brackets, but it will always return to square brackets when I save. I guess parenthesis is specific to APSIM classic. 
![image](https://user-images.githubusercontent.com/68366659/159426645-7aae88b7-4447-4551-878c-f295314d1334.png)

What is the best way to test a multi layer parameter using Morris SA in APSIM X? 

Any help about this please? 
Thank you

Below is a copy of the simulation file. 
[Morris_Sensitivity_Maize_tesvo4.zip](https://github.com/APSIMInitiative/ApsimX/files/8322045/Morris_Sensitivity_Maize_tesvo4.zip)

**Comment by hol430** [comment]
> I tested the soil initial water - but I get the following error, which is quite surprising because it is a child to Soil to my understanding.

The initial water node is removed when the simulation is run, so you won't be able to report anything coming from this component. If you want to report initial water content, you could report `[Soil].Initial.SW`, `[Soil].Initial.SWmm`, `[Soil].Initial.SWGravimetric`, or `[Soil].Initial.SWVolumetric`. If you want the daily (live) water content, you could report `[Soil].SoilWater.Water`.

> I tested a parameter (FBiom) with multiple layers - and I got the following error. I tried using parenthesis rather than square brackets, but it will always return to square brackets when I save. I guess parenthesis is specific to APSIM classic.

This is a bug in apsim, which seems to be caused by having an underscore in the reporting variable name. I've fixed the bug in #7196, but in the meantime, you should be able to run your file if you remove the underscore from the TotalSoil_fbiom variable alias in your report.

**Comment by andynen** [comment]
Thank you @hol430 - I will take note of that. 

I actually do not need to output those variables as I want to asses their effects on the model output. 

I also found a Morris Example Run from the Tutorial folder which helped understand Morris SA better. 

Thank you for your support. 
A
