### ISSUE TITLE
Morris SA: Report Analysis & Output of the Default Values

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7219]
Hello, 

I am trying to make sense of the report analysis of Morris SA (see image below). What would the report analysis represent given the multiple simulations from a range of parameters? 

I understand that it cannot be the average of all (I tested with an R algorithm and it does not match), 
Is it from a specific simulation ID? 
Or does it represent the output of the default value? - I tested this last option and it did not match. 

What should the barplots in the report analysis tell us? 
and How can we get the output of the default values alongside the Morris SA output? 

Thank you, 
A
 
![image](https://user-images.githubusercontent.com/68366659/161893955-0f253436-4782-4a1f-aeae-1d2be4249401.png)

**Comment by hut104** [comment]
I suggest you look at the example rather than the tutorial to learn about Morris SA.

Note that the approach uses the modern approach to performing Morris SA, and so uses the revolving staircase method for sampling the parameter space.  Therefore, you need to be careful in averaging the EE values to ensure you include the right rows for each parameter.  We use the Morris model in R to do this to ensure the averaging matching the sampling strategy.
________________________________
From: andynen ***@***.***>
Sent: Thursday, 7 April 2022 5:03 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Morris SA: Report Analysis & Output of the Default Values (Issue #7219)


Hello,

I am trying to make sense of the report analysis of Morris SA (see image below). What would the report analysis represent given the multiple simulations from a range of parameters?

I understand that it cannot be the average of all (I tested with an R algorithm and it does not match),
Is it from a specific simulation ID?
Or does it represent the output of the default value? - I tested this last option and it did not match.

What should the barplots in the report analysis tell us?
and How can we get the output of the default values alongside the Morris SA output?

Thank you,
A

[image]<https://user-images.githubusercontent.com/68366659/161893955-0f253436-4782-4a1f-aeae-1d2be4249401.png>

**Comment by andynen** [comment]
Thank you @hut104 this is well noted. I will investigate how to analyze the Morris SA output using the R's Morris package.
