### ISSUE TITLE
Unrealistic FInert values?

### ISSUE THREAD

**Issue by ElsaLagerquist** [APSIMInitiative/ApsimX#7223]
Hi,
I'm running simulations on two different soils using APSIM Next Generation, one is a heavy clay soil and the other one has 43.46 % silt and 15-30 % sand. I'm now trying to stabilise the different nutrient pools by running simulations over 20 years and using different initial values. I have a system without tillage but with annual cereals.
To get a stable Humic poll in the top 0-10 cm, for both C and N, I need to use a very low FInert, at 0.002 it get stable for the heavy clay soil and at the lighter soil it does not get stable over these 20 years but the lower I put FInert the smaller is the increase in Humic C and N over the simulated period. The other pools (FOM and Microbial) stabilise over this 20 year period and the mineralisation and crop yield and biomass looks realistic. The location is a northern Europe site, southern Sweden. I use 0.080 and 0.075 as the value for FBiom for the two different soils, which stabilised the Microbial pool. Changing other parameters did not affect the stabilisation of the pools and I have kept them to the default, taken from the oats example. 

The final use of the simulations will be to assess different cropping scenarios on crop performance and nutrient cycling, so looking at the relative effects between these scenarios. I wonder how concerned I could be about this deviation from the normally used FInert values and why this could be.

My questions are: 
1. can I affect the Humic pool in other ways than changing FInert, which is the only parameter that I have clearly seen affect this pool. Can it be a result of the combination of different parameters?
 2. Can this be an effect of the location that is not extensively used in APSIM simulations? That the effect of climate, coordinates, soil properties and management on the simulated humic pool has not been calibrated well enough? Or can it even be true for this system?
 3. Since the simulations of mineralisation, yield and biomass are realistic, can this very low FInert be used with trust after having a pre-simulation period before the simulations that will be assessed? Is there anything that could still be affected by this after pre-simulation and stabilisation of the nutrient pools that I should pay attention to when drawing conclusions from the assessment?
 
Best regards,
Elsa

**Comment by hut104** [comment]
Elsa
Thanks for your questions.

  *   The Biom and FOM pools will stabiise much more quickly as they are more labile.  The Hum pool will ordinarily take much longer as it has a much longer turnover time.  In Australia, virgin soils may take many decades to stabilise, with most fields likely still declining.  It may be that your simulations should not necessarily be stable, depending on your field history.
  *   Finert may be different depending on the C composition of the soil.  In Australia, for example, we have significant amounts of charcoal from long histories of traditional burning prior to clearing for agriculture.  This charcoal C forms part of our F inert.  At depth, most C is inert, not for chemical reasons, but for other reasons such as Oxygen availability.
  *   It may be worth considering local expertise and literature as to whether local fields are stable (ie in C balance) or whether they are net C emitters.

________________________________
From: ElsaLagerquist ***@***.***>
Sent: Monday, 11 April 2022 7:25 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Unrealistic FInert values? (Issue #7223)


Hi,
I'm running simulations on two different soils using APSIM Next Generation, one is a heavy clay soil and the other one has 43.46 % silt and 15-30 % sand. I'm now trying to stabilise the different nutrient pools by running simulations over 20 years and using different initial values. I have a system without tillage but with annual cereals.
To get a stable Humic poll in the top 0-10 cm, for both C and N, I need to use a very low FInert, at 0.002 it get stable for the heavy clay soil and at the lighter soil it does not get stable over these 20 years but the lower I put FInert the smaller is the increase in Humic C and N over the simulated period. The other pools (FOM and Microbial) stabilise over this 20 year period and the mineralisation and crop yield and biomass looks realistic. The location is a northern Europe site, southern Sweden. I use 0.080 and 0.075 as the value for FBiom for the two different soils, which stabilised the Microbial pool. Changing other parameters did not affect the stabilisation of the pools and I have kept them to the default, taken from the oats example.

The final use of the simulations will be to assess different cropping scenarios on crop performance and nutrient cycling, so looking at the relative effects between these scenarios. I wonder how concerned I could be about this deviation from the normally used FInert values and why this could be.

My questions are:

  1.  can I affect the Humic pool in other ways than changing FInert, which is the only parameter that I have clearly seen affect this pool. Can it be a result of the combination of different parameters?
  2.  Can this be an effect of the location that is not extensively used in APSIM simulations? That the effect of climate, coordinates, soil properties and management on the simulated humic pool has not been calibrated well enough? Or can it even be true for this system?
  3.  Since the simulations of mineralisation, yield and biomass are realistic, can this very low FInert be used with trust after having a pre-simulation period before the simulations that will be assessed? Is there anything that could still be affected by this after pre-simulation and stabilisation of the nutrient pools that I should pay attention to when drawing conclusions from the assessment?

Best regards,
Elsa

**Comment by ElsaLagerquist** [comment]
Hi Neil, thank you for the quick response and your inputs on my questions!

The soils we have here probably differ quite a bit from the Australian and New Zealand soils I have looked up in the soil database, according to your description. I will see what I find from the local expertise, it seems to be the best way to go for these variables.

Best,
Elsa
