### ISSUE TITLE
Want event with useful arguments

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#7262]
I want to publish an event with numerical arguments in one manager module, and subscribe to it retrieving those arguments in another. I see that I have to make a subclass of EventArgs which includes my arguments but I don't know where to declare this so it can be used by both publisher and subscriber.

**Comment by hol430** [comment]
Yes, it's possible to reference one manager script directly from another, although cyclic references are not possible. Here is a quick example which uses events, but you could easily just use direct method calls instead, by `[Link]`-ing to the script type in the other manager.

The main thing to remember is that the publisher manager below should be above the subscribing manager in the simulations tree (in terms of a depth-first search), to ensure that it gets compiled before the subscribing script so that the subscribing script is able to resolve the event arguments type defined in the publisher script.

Publisher:

```csharp
using System;
using Models.Core;

namespace Models
{
    [Serializable]
    public class Script0 : Model
    {
        [Link]
        private IClock clock = null;

        public event EventHandler<XArgs> CustomEvent;

        [EventSubscribe("DoManagement")]
        private void DoDailyCalculations(object sender, EventArgs e)
        {
            CustomEvent?.Invoke(this, new XArgs(clock.Today.DayOfYear));
        }
    }

    public class XArgs : EventArgs
    {
        public int X { get; private set; }

        public XArgs(int x)
        {
            X = x;
        }
    }
}
```

Subscriber:

```csharp
using System;
using Models.Core;

namespace Models
{
    [Serializable]
    public class Script1 : Model
    {
        [Link]
        private ISummary summary;

        [EventSubscribe("CustomEvent")]
        private void DoDailyCalculations(object sender, XArgs e)
        {
            summary.WriteMessage(this, $"Received event data: {e.X}", MessageType.Information);
        }
    }
}
```
