### ISSUE TITLE
Morris SA: System.ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7279]
Hello @here

I get the following error after running a Morris SA and the graphic results are empty. In fact, APSIMX runs successfully, but the datastore seems to no be able to write the output. It gives the following error after the run

![image](https://user-images.githubusercontent.com/68366659/167968940-171e3149-04fb-44c7-81b9-f94d23d8cee1.png)

and when I click on DataStore module it gives the following (see image below). 
![image](https://user-images.githubusercontent.com/68366659/167970266-6efea548-aea8-4a99-a8d2-812c8672df20.png)

Apparently, the issue is with some parameter being null.  that said, I tested the parameters whose Lower Bound were > 0, and it ran successfully and showed graphic results. Meanwhile those (see image below) with Lower Bound 0 did not and gave the same errors as mentioned earlier. Even after assigning non-zero values to the Lower Bound of these parameters, the same error persists. Are there any range limit to these parameters? If yes,  what are they or where can I find it ? 

When they are all 0. 
![image](https://user-images.githubusercontent.com/68366659/167969545-959a556d-0514-4dea-a89f-4cd2c279bbe7.png)

The non-zero values assigned: 
![image](https://user-images.githubusercontent.com/68366659/167969496-c973537d-0af4-40a2-9127-d05fc756513b.png)

Thank you, 
A

I attach here a copy of the sim file.  
[Morris_Sensitivity_Maize_vo4_test3.zip](https://github.com/APSIMInitiative/ApsimX/files/8674179/Morris_Sensitivity_Maize_vo4_test3.zip)

**Comment by hut104** [comment]
Hi,
I am not sure about the cause of your error.  But I did notice that some of the parameter ranges may be a bit wide.  The width of each range is very important for a sensitivity analysis.  I'd suggest that it is very unlikely that all soil OC would be inert, or microbial.  The ranges should represent that which would be reasonable for the given soil you are modelling.

The C:N ratio of zero is likely the cause as you may be getting a divide by zero.  It is unlikely that the soil OM would have no nitrogen in it.
Neil.
________________________________
From: andynen ***@***.***>
Sent: Thursday, 12 May 2022 10:49 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Morris SA: System.ArgumentNullException: Value cannot be null. (Parameter 'key') (Issue #7279)


Hello @here<https://github.com/here>

I get the following error after running a Morris SA and the graphic results are empty. In fact, APSIMX runs successfully, but the datastore seems to no be able to write the output. It gives the following error after the run

[image]<https://user-images.githubusercontent.com/68366659/167968940-171e3149-04fb-44c7-81b9-f94d23d8cee1.png>

and when I click on DataStore module it gives the following (see image below).
[image]<https://user-images.githubusercontent.com/68366659/167968940-171e3149-04fb-44c7-81b9-f94d23d8cee1.png>

Apparently, the issue is with some parameter being null. that said, I tested the parameters whose Lower Bound were > 0, and it ran successfully and showed graphic results. Meanwhile those (see image below) with Lower Bound 0 did not and gave the same errors as mentioned earlier. Even after assigning non-zero values to the Lower Bound of these parameters, the same error persists. Are there any range limit to these parameters? If yes, where can I find it ?

When they are all 0.
[image]<https://user-images.githubusercontent.com/68366659/167969545-959a556d-0514-4dea-a89f-4cd2c279bbe7.png>

The non-zero values assigned:
[image]<https://user-images.githubusercontent.com/68366659/167969496-c973537d-0af4-40a2-9127-d05fc756513b.png>

I attach here a copy of the sim file.
Morris_Sensitivity_Maize_vo4_test3.zip<https://github.com/APSIMInitiative/ApsimX/files/8674179/Morris_Sensitivity_Maize_vo4_test3.zip>

**Comment by andynen** [comment]
Thank you @hut104, I managed to reduce the width of some of the parameters and the simulation ran successfully. But it comes with an additional challenge in graphic display for the path analysis. I am not able to filter a specific year for the path analysis. the graphic display is empty when I specify a year, but when I removed the filtering, it gives the following messy graphs. 

![image](https://user-images.githubusercontent.com/68366659/167999582-ffc78914-f5a0-47a6-8f5d-cc24afa52b00.png)

It is challenging to understand where the source of the problem comes from. I tried a couple of things among other (i) I have removed some parameters from being tested, but yet the same issue. (ii) I put Morris parameter jump to be half of the number of intervals, but still the same.  (iii) I also tried Morris SA with nearly 25 soil parameters and yet the same persist, and the latter even add an additional challenge and does not display graphical results for statistics MuStar and Sigma. 

Any help will be greatly appreciated. 

Other questions: Can the number of parameters affect Morris SA in APSIMX? 
                          OR are there some parameters which should not be varied? 

Thank you, 
A

I attach here a sample of the simulation. 
[Morris_Sensitivity_test.zip](https://github.com/APSIMInitiative/ApsimX/files/8675262/Morris_Sensitivity_test.zip)

**Comment by andynen** [comment]
hello @here 

just adding the error given - **"Cannot find column [Clock.Today.Year]."**
![image](https://user-images.githubusercontent.com/68366659/168181599-bddd4472-c2f4-4359-acab-b807de48e0de.png)

and it gives only one point for "MuStar-Sigma analysis"
![image](https://user-images.githubusercontent.com/68366659/168181694-e3fe6e64-31ba-4796-b8ee-c4dd3f7ab08f.png)

Any help will be greatly appreciated.

Thanks!
A

**Comment by andynen** [comment]
hello @here, 

I managed to run the Morris SA and display the year.  I was using the wrong variable to aggregate the results under the MorrisMethodExampleModule. I was using “Ammonium” rather than “Clock.Today.Year”  and on the other side I was not selecting the right year.

Thank you, 
A
