### ISSUE TITLE
Report simulation file conversion and clear errors

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7304]
It would be useful if the status window reported that a simulation file had been converted to the latest version for full transparency that the file may have been modified.
Also if you get a json error deserialising the simulation file it would be good if this was deleted when opening another simulation to avoid confusion.
On file open, clear the status window. Is there any reason old messages would be wanted upon opening new simulation, even with multiple tabs open?

**Comment by hol353** [comment]
For @ric394 benefit: This defect fix is a bit of a stretch goal.

APSIM has a .apsimx converter class that converts the JSON in .apsimx files to a newer version when necessary. This happens automatically when the user opens a .apsimx file.

In the GUI there is a method called 
*OpenApsimXFileInTab*

This calls 
*FileFormat.ReadFromFile*

which calls 

*FileFormat.ReadFromString*

ReadFromString calls:

```c#
var converter = Converter.DoConvert(st, -1, fileName);
```

*converter* in the line above is of type *ConvertReturnType* which has a *DidConvert* boolean property that needs to be returned to the caller *ReadFromFile* along with the *newModel*. In turn *ReadFromFile* needs to return it back to its caller *OpenApsimXFileInTab*. 

The problem is that we need to return 2 things (*DidConvert* and *newModel*). The best way to do this is to change the return type to *ConvertReturnType* and add an extra property to *ConvertReturnType* called something like *NewModel*. Of course all calling methods will have to change as well.

Back in *OpenApsimXFileInTab* method, you can then use *DidConvert* to detect when a conversion happens and display an appropriate message to the status window by calling *ShowMessage*. You can also clear old messages (by calling *ShowMessage* with an empty string) as per @lie112 comment above.

I hope this convoluted description makes sense. Ask questions if not. Using a debugger to step through the code will help.
