### ISSUE TITLE
Email Issue

### ISSUE THREAD

**Issue by dewisoe** [APSIMInitiative/ApsimX#7310]
@hol430 

Hi Drew, this is Dewi. Not sure if you got my emails earlier or not as I kept getting messages saying that the emails were failed to be sent due to wrong email address... Thanks!

<img width="730" alt="Screen Shot 2022-05-26 at 2 47 03 PM" src="https://user-images.githubusercontent.com/106294934/170415647-a2ab5fc8-12ec-4719-b3cf-77237774a911.png">

**Comment by hut104** [comment]
Hi,
Drew has moved on to work with another modelling group.
If you raise the issue on github, some other user may be able to assist you.
We hope to be able to employ a replacement for Drew's role in the future.
________________________________
From: dewisoe ***@***.***>
Sent: Thursday, 26 May 2022 2:25 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Email Issue (Issue #7310)


@hol430<https://github.com/hol430>

Hi Drew, this is Dewi. Not sure if you got my emails earlier or not as I kept getting messages saying that the emails were failed to be sent due to wrong email address... Thanks!

[Screen Shot 2022-05-26 at 2 47 03 PM]<https://user-images.githubusercontent.com/106294934/170415647-a2ab5fc8-12ec-4719-b3cf-77237774a911.png>

**Comment by mpandreucci** [comment]
Hi Neil.
I didn't know Drew had left APSIM.
He assisted Dewi in running APSIM on her Mac but because she is running a custom build version, she is having trouble updating it and opening files that were done in more recent versions. 
We will put the issue here and see if anyone can help with that. 
I hope all is going well with you guys over there.

**Comment by hol430** [comment]
If you let me know what the problem is I'd be happy to make a somewhat-educated guess about a solution. Without a Mac to test on I won't make any promises though :).

**Comment by dewisoe** [comment]
Hi Drew, 

The APSIM that I have right now (custom built) is not able to be upgraded so I can’t open a file that Mariana created as she has a newer version.
 
Also, I’ve tried to download the newest APSIM version (APSIM2022.5.7042.0), but I got a couple of error messages:
- Exception has been thrown by the target of an invocation. --> Object reference not set to an instance of an object.
<img width="1293" alt="Screen Shot 2022-05-26 at 7 38 28 PM" src="https://user-images.githubusercontent.com/106294934/170441876-cf2c2b70-33d5-4ad5-b538-7454765a1538.png">

- Operation not permitted. 
<img width="1293" alt="Screen Shot 2022-05-26 at 7 38 49 PM" src="https://user-images.githubusercontent.com/106294934/170442207-dcb8703e-039d-4ece-abd6-e8b8f8f7ffdc.png">

**Comment by mpandreucci** [comment]
Hi Drew.
Yes, we have been having problems with the predicted/observed node. Even though everything is pointing to it, we can't load up graphs with the information that should be coming from that. Everything else works fine in the simulation.
Could you please post the instructions to work around the mac problem?
Thank you very much for helping with this!!

**Comment by dewisoe** [comment]
Hi @hol430,
Yes I'm on MacOS Monterey. Would you be able to post the instructions please?
Thank you!

**Comment by hol430** [comment]
Hi guys, sorry for the delay. You would just need to open a terminal and run the apsim launcher script from your shell. I don't have a mac to give you the exact location of this script, but I'm pretty sure it's something like `/Applications/APSIMxxxx.xx.xx.0.app/Contents/MacOS/ApsimNG` (substitute your version number there). If I've got that path right, you should be able to run that command from your terminal and it will launch apsim. If the path is not right, someone with access to a mac might need to chime in here.

**Comment by mpandreucci** [comment]
Hi Drew @hol430
I'll talk to Dewi to see if that works. Will let you know how that goes.
Thanks a lot for that.

**Comment by her123** [comment]
From your user Applications directory (mine is /Users/her123/Applications)
Use this command

./Applications/APSIM2022.5.7043.0.app/Contents/MacOS/ApsimNG

**Comment by mpandreucci** [comment]
Hi Neville.
Thanks a lot for that.

**Comment by dewisoe** [comment]
hi @hol430 @her123 

thank you so much for that! it's working now..
