### ISSUE TITLE
SimpleGrazing/AgPasture grazing outputs

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#7336]
Just a heads up - people may be aware of this and it may have been discussed in another issue but I could not find it. I found that the output from SimpleGrazing.GrazedDM did not match that from AgPasture harvested weight (e.g. for a ryegrass and white clover pasture ([AGPRyegrass].HarvestedWt + [AGPWhiteClover].HarvestedWt) as AGPHarvWt). Also the pre and post grazing weights did not make sense - too high. After a bit of sleuthing it turns out that the default settings in the Forages component  was grazing the SurfaceOrganicMatter.Residue in some way, shape or form. Not sure why SurfaceOrganicMatter.Residue is a forage but I do recall some discussion about why this is so? Anyway, the fix for this (which may be common knowledge) is make sure that the live and dead fraction consumable for SurfaceOrganicMatter.Residue is set to zero (not one - which seems to be the default) - so it is not grazed. Should/can the default be changed?

![image](https://user-images.githubusercontent.com/32279744/173464031-a752c6aa-2939-445b-83df-e28962c985e9.png)

@sno036 @rcichota @hol353 @andomariot

**Comment by rcichota** [comment]
Yeah, I noticed this oddity too. Although it seems the default has been reset to zero, but maybe the change is not retroactive (?).
I think I see where this (the Forage thingy) is trying to do, but some of these inputs (like digestibility) are described by some models (AgPasture) and it changes over time, not sure how these are reconciled... 
The SimpleGrazing model also has some oddities, I notice a few while working on fixes for AgPasture, unfortunately I did not have time to log the issues properly (will do eventually), but these include using different 'pools' to compute some of the biomass values; e.g. I think it uses total biomass for pre and post harvested, not only the above-ground... which is why the values are too high...

**Comment by MarkLieffering** [comment]
Thanks @rcichota for your comments

> Although it seems the default has been reset to zero, but maybe the change is not retroactive (?).

I did a fresh pull this morning so am using the LAG (latest and greatest) version. However, the AgPasture example has the default Residue consumable fraction set to 1. Do these examples get updated?

>e.g. I think it uses total biomass for pre and post harvested, not only the above-ground

I don't think this is the case (at least in my simulations) - see here a day before, during and after a grazing event. AGPHarvestWt is the reported aboveground harvested, AGPAbove is the aboveground on the day. AGPHarvestWt = previous day's AGPAbove - the set residual (2000 in this case) + whatever is grown on the graze day. AGPHarvestWt  = SimplGrazedWt - (reported by SimpleGrazing) = the PreGrazeDM- the set residual (2000). So I don't think in this example belowground bits are being harvested. Note the SimpleGrazing.PreGrazeDM = the previous day's AGPAbove

![image](https://user-images.githubusercontent.com/32279744/173475191-d521d5e4-4034-4056-a0b6-f149ac61f17b.png)

@rcichota
