### ISSUE TITLE
APSIM NextGen Freezing

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#7405]
APSIM NextGen is freezing at the drop of a hat.

**Comment by zur003** [comment]
Are you running under Fedora Linux?

Seriously, though, a bit more detail is needed. For example, what were you trying to do at the time of the freeze?

**Comment by hrpasl** [comment]
lol. I am running APSIM NextGen and it is taking up about 80% of my CPUs to operate. I am not running much else so APSIM will run, but then if I go to open my datastore, the computer will freeze. If I then close APSIM to delete the .db files and restart it, APSIM is continuing to run as a background file.

**Comment by peter-devoil** [comment]
It certainly has trouble under Ubuntu Linux :) 

The data store seems to be at the center of the problem, the tables here aren't large

**Comment by zur003** [comment]
I think rather than the data store per se, the problem is with the "PagedDataProvider", which appears to be reading the 814533 rows in the table in block of 50 at a time, and with the Sheet, which seems to be trying to fetch data for all the rows, including those not visible. But I'm still trying to make sense of it....

**Comment by zur003** [comment]
@hol353 - The problem seems to be in Sheet.cs, with the block starting at line 314, commented with "Optionally add in blank rows at bottom of grid". If I understand correctly, it's fetching data for all the rows, even when those rows aren't displayed. I'm not quite sure what the intent was here. Can you clarify?
