### ISSUE TITLE
Weather downloader can't be closed while it is downloading

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#7431]
If SILO is down the user can't cancel or close the dialog box.

**Comment by zur003** [comment]
I think that HttpClient will time out after 100 seconds by default, but we probably ought to allow the user to cancel. 

Also I just noticed that the message box displayed on a download error isn't very useful:
![image](https://user-images.githubusercontent.com/11879340/183425426-bc496a4e-c788-40ae-969e-636f650f885b.png)

I think the problem is that it's trying to display the full URL in the message box, but it's very long with nowhere to break it to wrap.
