### ISSUE TITLE
Automatic refreshing of DataStore when running all simulations

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#7451]
When removing variables from the output(reporting) list and rerunning the simulations (from the top - rerunning all), the datastore still keeps the old variables (as empty columns) and does not auto-refresh the list of parameters. Similarly, when adding a variable in the middle of the list, these new variables will show up at the end of the list in the datastore.

APSIM version	Version 2022.8.7074.0, built 2022-08-18
Run on	2022-08-19 10:26:29

**Comment by lie112** [comment]
This is due to the order the columns are added to the underlying SQLite database. When a simulation is run, the database is only emptied of data relating to the current simulation. If the database was destroyed and recreated with each simulation run the problem would be solved but APSIM would not work across multiple runs or experiments. There is no way to know whether the data in one of the columns to remove is still correct and needed for another simulation. 
Therefore, the solution is to delete the .db file from your working directory (it will have the same name as your simulation apsimx file). This will delete the table structure and all data. When you next run your simulation the database will be recreated with obsolete columns removed and the correct column order.
It might be useful to have a "delete datastore" or "full clean datastore" option in the popup menu of datastore model to simplify this process as it's a common requirement.

**Comment by peter-devoil** [comment]
There is a right click menu entry on the datastore that allows just that:
![image](https://user-images.githubusercontent.com/1924386/185815601-504c02a0-8dff-40a6-9af1-0a02ea4025c8.png)

It would be a nice user feature/shortcut when running a simulation from any node (ie right clicking on the tree) to wipe any datastores underneath that node before running.

**Comment by lie112** [comment]
Great. It's hard to keep up with things that get fixed and improved. Empty datastore never cleaned old columns or reordered.

**Comment by hol353** [comment]
> It would be a nice user feature/shortcut when running a simulation from any node (ie right clicking on the tree) to wipe any datastores underneath that node before running.

This isn't possible with the current design of the .db files. Each report has its own table in the db file. This means that multiple simulations outputs go into the same table (if those simulations have a report of the same name). If you run a subset of simulations then it can't just wipe the table in the .db file because the user will lose outputs from other simulations. It will go and wipe data for the subset of simulations being run though but this doesn't alter the structure of the table (i.e. columns). The result is that columns can get out of order if the user is adding  / removing columns from their report. 

Perhaps we need a different design for our .db files but I can't think of a better way.

**Comment by lie112** [comment]
I suggest that the user is somewhat responsible for for cleaning up database during periods of managing reporting outputs. The updated version of "Empty the datastore" seems to do this well.
The functionality provided is perfect for getting the required output from multiple models and experiments.
