### ISSUE TITLE
Insert emoji option does not work when renaming something

### ISSUE THREAD

**Issue by Keith-Pembleton** [APSIMInitiative/ApsimX#7507]
When right clicking on something I am in the process of renaming the option appears to insert emoji.  When i saw this I got very excited because i have a manager script that i am particularly proud of.  However when I select that option nothing happens.  So now I am :(. 

Was there ever the intent to have emoji's enabled in the interface? and if so why?

**Comment by zur003** [comment]
Emojis were never enabled deliberately, but come in automatically with the Gtk SourceView widget used for script editing. You cannot currently insert emojis into component names, as only alphanumeric characters are accepted. You can insert them into strings in scripts 🌱️, if you really want to, and even use them in parameter descriptions, as in:

![image](https://user-images.githubusercontent.com/11879340/190303946-a2f740c6-630d-45d2-9c68-5e77491d49b3.png)

However, this is more by accident than by design. Personally, I give them 👎️.

**Comment by Keith-Pembleton** [comment]
Thanks for explaining @zur003
