### ISSUE TITLE
SWIM Wishlist - after release - provide more information to users on nodes and layering

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#7540]
From Kirsten: (this could sit in the documentation or in the tutorial)

-	One practical (user) question on layering (that you may want to clarify in the document (unless I didn’t read properly and missed the answer): You explain the background and difference between layers and nodes and also show how they align. This is a big improvement from APSIM Classic where I’d been playing in excel to optimise my provided layer structure to get the nodes to be approximately half-way these layers. But one question: when I output for example SW – do I get these for the nodes or for the layers? Asking because when we simulate an experiment with measurements at particular depths, we would like to align those. In Figure 1 node i+1 is in layer i, except for first and last. So was just wondering if the output (sw(1), sw(2), ….) is for the nodes or has been back calculated to represent the layers.

**Comment by hol353** [comment]
> when I output for example SW – do I get these for the nodes or for the layers? Asking because when we simulate an experiment with measurements at particular depths, we would like to align those. In Figure 1 node i+1 is in layer i, except for first and last. So was just wondering if the output (sw(1), sw(2), ….) is for the nodes or has been back calculated to represent the layers.

SWIM works on nodes. When you output sw(1) you get soil water in node 1 (the surface). Likewise, when you specify initial water in the GUI you are setting water contents for the nodes as per Figure 1.
Internally, sw = th. There is no back calculations to convert from nodes to layers.

Having said that, your assertion that node i+1 is in layer i is incorrect. If you look at figure 1:

![image](https://user-images.githubusercontent.com/1943827/218355221-f78defea-fe60-42dc-bcd4-e6af8d0ca494.png)

node i = layer i. It's just that node 1 is at the surface rather than the middle of the layer and node 7 in the figure is the bottom of the profile rather than the middle of layer 7.

I will add this to the documentation.
