### ISSUE TITLE
Hard crash of apsim

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#7566]
Output variable "no3()" causes a hard crash of apsim.
[RizwanCalibration.zip](https://github.com/APSIMInitiative/ApsimX/files/9859728/RizwanCalibration.zip)

**Comment by zur003** [comment]
I started looking into this, and found that any variable with a name like "xxx()" will cause this crash, due to a stack overflow. I have a fix, but don't want to commit it until I have a better understanding of what is going on. I noticed that Models\Core has both a "Locator" and a "Locater"class. The XML summary description of both classes is identical. Why are there two similar classes with confusingly similar names and how do they differ?

**Comment by her123** [comment]
Pick a winner on the classes. Find the one with the most functionality and keep it. You have Deans permission to submit the fix.
