### ISSUE TITLE
Cultivar selection menu needs a scroll bar

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7647]
It would make it easier to go through the list. Currently, it takes 30 seconds to move from the bottom of the list to the top.

BTW, if you keep scrolling up, you will end up in a blank area:

![image](https://user-images.githubusercontent.com/39573622/202324841-bc207667-8f38-4fe0-be41-3afd1a07dec7.png)

**Comment by ric394** [comment]
Hi @hol430 @zur003 I'm attempting to add a vertical scrollbar to the DropDownView.
I've had trouble locating good documentation on how to do this. Would you be able to point me in the right direction?
I've tried doing the below, is this on the right track?
![image](https://user-images.githubusercontent.com/123442863/218607420-760ac189-d0c3-406a-8d6d-82a909d5e13b.png)

**Comment by zur003** [comment]
@ric394 - Welcome to the challenges of Gtk#. It may be possible to accomplish your goal by modifying the ComboBox style. There is apparently an "appears-as-list" style for comboboxes that adds scrolling, or so I gather from some Google searching. But I'm not sure how you can set that style. I'll look into it a bit more...

**Comment by zur003** [comment]
OK. I have a lead here. If you edit global.css and add a section like this:
`combobox {
	-GtkComboBox-appears-as-list: true;
}`
comboboxes will appear with scrollbars. However, I don't know that global.css is necessarily the best place to make this change. @hol430 might have some advice here, and would know better than I how to modify styles on the fly under Gtk#.

Also note that this is a somewhat problematic feature in Gtk, and it may not be supported in Gtk 4.

**Comment by hol430** [comment]
As far as documentation goes, there is no official documentation for GtkSharp, likely due to the LGPL licence on the gtk/gobject documentation and code comments. As a result you'll need to consult the C api documentation. This is not as problematic as it may sound, the type names and method names tend to translate pretty much directly into C# if you substitute snake_case for PascalCase. The Gtk3 documentation is [here](https://docs.gtk.org/gtk3/) and the documentation for the other related libs (e.g. gdk, pango, cairo, etc) is [here](https://docs.gtk.org/).

I think global.css should be the right place for this to change, as it contains changes to be applied in both light and dark themes.

I notice `appears-as-list` only exists in the gtk2 documentation. It may be deprecated in gtk3, but if it works then it may be worth committing anyway, as an alternate solution may be difficult to find. Maybe there is a height or max-height property you could experiment with. If you're running Linux, a good way to experiment is to use the [gnome inspector](https://wiki.gnome.org/Projects/GTK/Inspector) which lets you modify gtk widgets and style while the application is running without recompiling (similarly to devtools in a web browser).

**Comment by ric394** [comment]
@zur003 That worked like a charm on Windows:

![image](https://user-images.githubusercontent.com/123442863/218645180-7c157bdb-fc0d-4abc-b6ac-c1cee2737630.png)

@hol430 That is very useful information to have. Thank you.

**Comment by zur003** [comment]
Thanks for the comments, @hol430. From what I can determine, appears-as-list is not itself deprecated, but the combo box widget will be replaced with a new equivalent in Gtk4. For more on this, see [https://mail.gnome.org/archives/gtk-list/2016-December/msg00036.html](https://mail.gnome.org/archives/gtk-list/2016-December/msg00036.html). That can and will be dealt with at a (much?) later date.

The combobox's scrollable list works, but there are a few quirks with the initial scroll position and selection. I think these could be tinkered with fairly easily: the list is actually a Treeview that can be accessed via the "PopupAccessible.Widget" property of the combobox.
