### ISSUE TITLE
Model pasted into simulation is empty

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#7658]
1) Open and run the canola simulation - the simulation completes without error.
2) Copy a wheat model from the wheat example into the paddock within the canola example.
3) When you run this simulation there is an error stating that the wheat model cannot find a property.
4) Close the canola example
5) open the canola example again and run without error.

@zur003 this may be related to recent similar errors.

**Comment by zur003** [comment]
@hut104 - This appears to be a serious bug in the GUI, but I don't think I can take credit for it this time. It seems that a copy-paste operation copies only a node (in this case, Wheat), but not its children (which in this case is most of the model). How can this have been around but not be noticed? It also affects adding a model from the Toolbox, or using "Add Model", and looks to have been around since July or so (I think...).

**Comment by zur003** [comment]
@hut104 - Ah, now I understand. The children aren't copied because the Wheat model is a resource. If you save the simulation after adding Wheat, then close and re-open it, the full model is present. I think we need to add a bit of logic to detect when a resource model is added to a simulation, and pull in the resource at that point.
