### ISSUE TITLE
Learning APSIMx - help required

### ISSUE THREAD

**Issue by yashvirchauhan** [APSIMInitiative/ApsimX#7689]
Hi there, 
I am still trying to get learn APSIMx
In the factorial example included in APSIMx, when I want to create a new factor, e.g. time of sowing, IntelliSense seems to work fine after I type [SowingRule]. But in the example on chickpea (chickpea. apsimx) the same thing does not seem to work. Further, I have multiple experiments with dates of sowing spread over a couple of years, how to put year. When I put 8-may-2018 as 2018-5-8, as given in the example, it can not run the simulation and throws the error 'Invalid path: [SowingRule].Script.SowingDate.' Can someone point out my mistake? I have scores of sowing dates, months and years that I want to cover in one run. Cheers, Yash

**Comment by lie112** [comment]
The property defining your sowing date in the sowing manager script [Sowing] is of string type and expects the format dd-mmm and does not include a year component. In order to include the Year you need to change the SowDate property to a DateTime type in the manager script (click sowing, then select the Script tab). Once this is a DateTime the WithinDates method will include the supplied year. Use dd/mm/yyyy as the format for entering the date.

`        public DateTime SowDate { get; set; }`

**Comment by yashvirchauhan** [comment]
Thanks for your help, Adam, it worked the way I wanted it to work.
