### ISSUE TITLE
Maize model - Nitrogen stress factor

### ISSUE THREAD

**Issue by santos-cl** [APSIMInitiative/ApsimX#7839]
We have been working with the Maize model in APSIM Next Gen to simulate the crop response to nitrogen. However, we have encountered a couple challanges. If we set up simulations in NextGen and Classic that are as similar as possible, we can see a couple differences.

Looking at the nitrogen stress factor in NextGen and Classic, we can see that they are quite different. In NextGen, the factor never changes from1 while there is a crop in the field.

- In Classic, the nitrogen stress factor we looked into is: n_stress_photo

- In NextGen, the nitrogen stress factor that we looked into is: \[Maize\].Leaf.Photosynthesis.FN

![image](https://user-images.githubusercontent.com/70726437/223227621-8d3e77e8-2894-45eb-a1dd-b738615ee618.png)

Similarly, if we look at the relationship between the nitrogen stress factor and the nitrogen concentration, NextGen seems non-responsive.
![image](https://user-images.githubusercontent.com/70726437/223227647-70fe2642-69c6-4034-bdd4-fc62f8eaabd9.png)

However, internally, the model seems to be responding to nitrogen. Even if the response is somewhat different from Classic.

![image](https://user-images.githubusercontent.com/70726437/223227670-70d2decf-a115-40e0-bbe0-b2e3025994d9.png)

Are we looking at the wrong variable? Or is there a glitch in the Maize
response to nitrogen? I would appreaciate any insights! Thanks!

**Comment by ilhuber** [comment]
For FN being reported as 1, looks like this might be because leaf live biomass MetabolicNConc and FunctionalNConc are always equal while MetabolicWt is nonzero, which means that Leaf.Fn is always 1 while the crop is in the field, and consequently so is Leaf.Photosynthesis.FN.

In LeafCohort, MetabolicWt and MetabolicN are computed by the following code, where Live is a Biomass object:
https://github.com/APSIMInitiative/ApsimX/blob/4e27991462682007438356b740165c73da023d9a/Models/PMF/Organs/LeafCohort.cs#L790-L798

Inside Biomass, MetabolicNConc is calculated as the following:
https://github.com/APSIMInitiative/ApsimX/blob/4e27991462682007438356b740165c73da023d9a/Models/PMF/Biomass/Biomass.cs#L180-L189

So FunctionalNConc.

In Leaf, Fn is computed as MetabolicNConc / functionalNConc:
https://github.com/APSIMInitiative/ApsimX/blob/4e27991462682007438356b740165c73da023d9a/Models/PMF/Organs/Leaf.cs#L1171-L1177
Which should evaluate to 1, barring some weird floating point error stuff.

I am not sure if this variable is what we should be looking at for N stress, though.

**Comment by hol353** [comment]
As @ilhuber  points out FN in maize in Next Gen will always be 1. This is a limitation caused by the Maize model using the 'Leaf' model. It is on our task list to remove the 'Leaf' model from Maize (and other crop models) and replace it with 'SimpleLeaf'. This is a complex task. No timeline on when this will be completed.

**Comment by hol353** [comment]
Same as #5708. Closing...
