### ISSUE TITLE
Spikes in predicted soil water potential with SoilWat

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#7859]
Simulation where we simulate soil water potential. On two occasions where the conditions get wet, we get a wild negative spike in water potential. See 6 cm water potential and also the water retention curve figure.
[Temora.zip](https://github.com/APSIMInitiative/ApsimX/files/11012532/Temora.zip)

**Comment by par456** [comment]
Leaving some notes here for Neil on what I figured out when digging into this. Attached is the stripped down version of the file that has just the 6cm water potential, I was using this to test with and the spike within that time is one of the worst.

[Temora.zip](https://github.com/APSIMInitiative/ApsimX/files/11394081/Temora.zip)

In the HyProps.cs file, in the Suction Function, it is possible for the est and est2 variables to end up as the same value, which gives a slope (m) of 0 and therefore a divide by 0 error.

![image](https://user-images.githubusercontent.com/130029141/236123091-157ab0a5-2218-48dd-a9ec-a44df42d45f7.png)

They can both end up with the same value on when psiValue is a number between 0 and -1, as then psiValue2 will also end up between 0 and -1 (since a small number to the power of 10 will only get smaller). 

![image](https://user-images.githubusercontent.com/130029141/236123428-941e43fe-4646-4360-a72f-e919cc9ded32.png)

When this happens, and both psi values are between 0 and -1, then in SimpleTheta, they both end up in the first if statement, t is set to 0, and the calulation at the bottom is the same for both psi values, which leads to est and est2 equalling the same.

I tried some solutions to try and stop this from happening when the pFnew value got to small (instead just adding or subtracting dpF instead when the value was too small), and while this stops a divide by 0 error on the next iteration, it does not stop the extreme spikes.
