### ISSUE TITLE
"The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower"

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7886]
On VS2019 with up-to-date code. 

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	APSIM.Shared	C:\Program Files\dotnet\sdk\5.0.416\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141	
`

**Comment by zur003** [comment]
That is correct. The Windows version of Visual Studio 2019 does not support targeting .Net6.0. You will need to update to Visual Studio 2022. 

If, for whatever reason, updating VS is not possible and you still want to build Apsim yourself, you will have to manually edit each of the .csproj files and remove "net6.0" from the "TargetFrameworks" tag. 

We are doing this in part because Microsoft stopped supporting .Net 3.1 in December 2022. You can look forward to a similar transition 3 years from now, based on Microsoft's support schedule.
