### ISSUE TITLE
Best practice for parallelizing ApsimX simulations on HPC

### ISSUE THREAD

**Issue by ugrewer** [APSIMInitiative/ApsimX#7999]
### What is your question?

**Issue**: I am running a large number of ApsimX simulations on an HPC. What is the best practice to achieve parallelization?<br/><br/>

**Approach 1: Rely on ApsimX to conduct parallelization**
In my understanding, ApsimX is able to internally parallelize working on multiple APSIM simulations. In that case: On an HPC, I run top-level control-flow to subdivide my overall list of APSIM simulations into sub-lists of suitable size to be run on a single node. I then request as many array-jobs, as there are sub-lists. Within each array-job, I request all resources available on a single HPC-node (e.g. 64 CPUs, 128GB Ram). 
In a single call to ApsimX we inform it about a list of APSIM simulations to be executed by one of the following:

- .../Models sim_1.apsimx sim_2.apsimx ... sim_n.apsimx
- .../Models allSims.apsimx

_Side-question_: is it still possible to run all apsimX-files that are specified within a text-file, as under ApsimClassic: #1932. I fail to do so. <br/><br/>

**Approach 2: Manual parallelization via pyhton, bash, or similar**
On an HPC, I run top-level control-flow to subdivide my overall list of APSIM simulations into sub-lists of suitable size to be run on a single node. I then request as many array-jobs, as there are sub-lists. Within each array-job, I request all resources available on a single HPC-node (e.g. 64 CPUs, 128GB Ram). 
The array-job uses python to start 60 parallel processes. Each process consecutively executes single Apsim-simulations consecutively until all simulations on the sub-list have been run.<br/><br/>

**Approach 3: Define resource-tiny array-jobs**
On an HPC, I request as many array-jobs as there are APSIM simulations (e.g. 10 million). Within each array-job, I request resources needed for a single APSIM simulation (maybe: 3 CPUs, 6GB Ram ?). Within each array job, I run a single APSIM simulation while preventing ApsimX to utilize more resources than allocated to the array, by:

- .../Models --cpu-count=2 sim_1.apsimx

_Side-question_: In my understanding of #7687, it is sufficient to specify “--cpu-count”. Instead, it is in addition not necessary: 
•	to specify the environmental variable "NUMBER_OF_PROCESSORS" 
•	to limit the number of processes to which the apptainer-container has access via “--cpus” (weblink: [limiting container resources](https://apptainer.org/docs/user/latest/cgroups.html))<br/><br/>

**_Overall question_**: What are the pros and cons of the mentioned approaches? Is ApsimX generally or under certain conditions (i.e. fixed location and metfile) more efficient to parallelize? Is there one best and preferred option that I should use or are they rather equivalent? Currently, I parallelize using python. 

Thank you very much for your advice!

**Comment by JRichetti** [comment]
Let me attempt to answer this. I think what I do is your Approach 3

The way I managed to run many APSIMx on HPC was by using SLURM_ARRAY and a loop. I batched it in loops of 1k. 1k simulations because it takes less than 2h to run them sequentially, so I get in the 2h priority instead of long wait in the slurm scheduling thing. Essentially, I have a scrip (my case in R) with a loop that runs 1k .apsimx simulations.
I use SLURM_ARRAY_TASK_ID to send as many jobs as simulations/1,000. Each job will save the output in a .csv 

sbatch -a 1-?? parallel_APSIM.sh

where ?? is the number of jobs = total number of apsim simulation divided by 1,000. So if I'm doing 12,657 simulations ?? will be 13. That means 13 jobs will be sent with SLURM_ARRAY_TASK_ID varying from 1 to 13. This number is used to 'align' the simulations. So SLURM_ARRAY_TASK_ID = 1 will run sim_1.apsimx to sim_1000.apsimx, SLURM_ARRAY_TASK_ID = 2 will run sim_1001.apsimx to sim_2000.apsimx, and so on. the last one will run from sim_12001.apsimx to sim_12657.apsimx


This .sh asks for 1 CPU with 8GB for 1h59min and calls the .R script that has the loop that runs 1k simulations. The script saves each .db file and I use a tryCatch() (this is R, dunno equivalent in Python) to make sure errors are saved but the loop doesn't stop. It saves all 1k outputs I'm interested in a .csv that once everything is done I join them in one big .csv (but that is just row binding data frames). Thus far, my biggest need was about 24k simulations and all the jobs started right away and everything was done in less than 2h. I'm not in the millions of simulations to say if this approach is bad or not. So far so good. :P

Hope this helps!
