### ISSUE TITLE
CLI interface/option for building `.apsimx` simulation files

### ISSUE THREAD

**Issue by asherbender** [APSIMInitiative/ApsimX#8045]
### Describe the new feature

Currently the `--edit` option provides an interface for modifying parameters. It is not clear this option can be used to add/remove components from the simulation. 

It would be useful to provide a CLI interface that is conceptually similar to 'right-clicking' on nodes of the simulation tree in the GUI. That is; the ability to:

- add models to nodes
- delete nodes
- rename modes
- toggle enabled
- toggle readonly.

For example, remove a node might look like:

`Model.exe <PathToApsimXFile> --remove simulations.simulation.zone.report`

Whereas adding a node might look like:

`Model.exe <PathToApsimXFile> --add simulations.simulation.zone report`

Like 'right-clicking' on nodes of the simulation tree, additions could be pre-populated with default values. They could be modified in a subsequent step using `Model --edit`

In the limit, it would be useful to have a CLI interface that allowed creating a simulation from scratch. Minimally, allowing model nodes to be added/removed would provide functionality that is not available through `Model --edit`.

Related issues 
- #8038
- #6339

**Comment by hol353** [comment]
Rather than lots of calls to Models.exe to build a simulation or make lots of modifications to a simulation I propose turning the config file into a set of 'instructions'.

## Current config file functionality
Documented here: https://apsimnextgeneration.netlify.app/usage/editfile/

[Field].Soil = soils.apsimx;[soil1]      # replaces a soil from another file (soil called 'soil1' in file 'soils.apsimx').
[Field].Soil = [AllSoils].Soil1      # replaces a soil from a soil called 'Soil1' in a folder named 'AllSoils'
[Simulation].Name = asdf             # rename simulation to 'asdf'
[Weather].FileName = met1.met        # set FileName property of Weather model to met1.met
[Clock].StartDate = 2021-01-01       # set StartDate property of Clock model to 2021-01-01
[Simulation1].Enabled = False        # disable 'Simulation1'

# New functionality
Keep the exiting functionality and add additional 'instructions':

add [Field] soils.apsimx;[soil1]     # adds a soil to 'Field' from another file (soil called 'soil1' in file 'soils.apsimx').
add [Field] Report                   # add a new instance of Report class to field - same as AddModel from GUI
delete [Field].Irrigation            # delete Irrigation from Field
copy [Simulation1] [Simulation2]     # copy a simulation with name 'Simulation1' to a new sibling node with a name of 'Simulation2'
save 'c:\test.apsimx'                # save to file 'test.apsimx'
load 'c:\test.apsimx'                # load from file 'test.apsimx'
run                                  # run all simulations in file.

## Current CLI

/path/to/Models.exe <PathToApsimXFile> --edit <PathToConfigFile> 
Uses the config file to modify the apsimx file and then runs it.

## Proposed CLI

We keep the --edit switch for backwards compatibility.

/path/to/Models.exe *PathToApsimXFile* --script *PathToScriptFile*
Applies the 'instructions' in the script file

Feel free to comment / make suggestions.

**Comment by ric394** [comment]
as suggested by @par456 ```--apply``` could be used instead of ```-script```.
