### ISSUE TITLE
How to set Factorial Experiments with varying SurfaceOrganicMatter amount?

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#8050]
### What is your question?

Dear all, 

I'm testing if wheat yields are sensitive to SurfaceOrganicMatter amount. Could you please check my APSIMX file why the scripts not work properly? Thanks.
![image](https://github.com/APSIMInitiative/ApsimX/assets/72141690/4116a478-2f59-402d-95f5-7d0a480bebf7)

[Factorial_test.zip](https://github.com/APSIMInitiative/ApsimX/files/11661232/Factorial_test.zip)

**Comment by KeLiu7** [comment]
@par456 Dear Andrew, could you please have a look when you are free? many thanks.

**Comment by par456** [comment]
The StandingWt variable is a calculated value, so it can't be adjusted like that. It's sum of the standing weight from all the standing surface organic matter stored in that model.

If I'm understanding what you are doing, I think you want to change the InitialResidueMass instead, so that there is a different starting SOM for each simulation? That would look like:

`[SurfaceOrganicMatter].InitialResidueMass = 400 to 800 step 100`

**Comment by KeLiu7** [comment]
Yes, this is what I want Andrew. Many thanks
