### ISSUE TITLE
Pasting soils to new zone or factor duplicates some of its children functions

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8090]
### What happened?

I have struck this a couple of times recently when copying a soil and pasting it into another zone or into a factor....  The UI seems to duplicate some children (NO3, NH4 and Urea in the most recent experience) and then throws an error tell you the soil has duplicate children.  The gotcha with this one is that the copied soil is added to the JSON but does not show up in the UI.  It is easy enough to fix by deleting the duplicate models from the JSON but many users would not know to go looking there so better if this didn't happen.

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
I think it may have been the solute models that were duplicated the other time I struck this too

**Comment by par456** [comment]
I'm having a bit of trouble reproducing this, this might require a specific set of actions. 

1. When you copy from one zone to another, are the zones under different simulations?
2. When you copy them, are you using the right-click menu (copy and paste), the keyboard shortcuts (ctrl-C, ctrl-V) or dragging the soil from one zone to the other

If you have a file that always causes this to happen with a set of specific inputs, that might be helpful as well.

**Comment by rcichota** [comment]
I have come across this issue too, as Hamish said it is easy to fix by manually deleting (in text editor), but a pain nonetheless. I noted that this issue (only?) occurs when the soil being copied has ```SoilNitrogen```, it seems to work fine with ```Nutrient```. This must have come about when ```Solute``` was made explicit in the soil node, but as ```SoilNitrogen``` is not used much, the error went unnoticed for a while... 
This issue seems to have been create because ```SoilNitrogen``` uses specific versions of ```Solute``` (SoilNitrogenNO3, etc.) while the 'official' solutes are called simply NO3, etc. As far as can see, APSIM now tries to always add the 'official' solutes, so when copying a soil with ```SoilNitrogen```, it copies the existing ones and adds the 'official' solutes too. Once one of the copies is deleted the simulation runs.
A warning, deleting the versions for ```SoilNitrogen``` (SoilNitrogenNO3, etc.) enables the simulation to run, but the calculations go wacky and definitely wrong. But no error message or warning is raised! I only noticed this some couple of weeks ago and did not investigate further as I did not have time, it is something we need to look at. Perhaps it is easier from APSIM infrastructure to check which nutrient model is being used and copy/add the appropriate solutes, but it would be good to also have a check so that ```SoilNitrogen``` does not run if its required solutes are not present. Or better still, find a way to get away with having two versions of solutes...
