### ISSUE TITLE
Cultivar description

### ISSUE THREAD

**Issue by AnnaBlanke** [APSIMInitiative/ApsimX#8182]
### What is your question?

Dear APSIMX users, 

I am trying to calibrate a new peanut cultivar. And I am wondering if there is detailed description of the cultivars available in the model ? Ideally, the datasets used for calibrating these cultivars would be available somewhere and a description where these cultivars are used and how they are typically managed. The only description I found is in the the crop module documentation: 
"Early bunch, Virginia bunch, Streeton, McCubbin, Chico, NC7, VB97, Florunner, Conder. Cultivars differ in terms of biomass partitioning to grain and phenology." 
Thanks for your help!

**Comment by hut104** [comment]
The cultivar descriptions are captured in the Peanut model resource (https://github.com/APSIMInitiative/ApsimX/blob/master/Models/Resources/Peanut.json)
If you search for "cultivar" you will find the list of parameter overrides to explain differences between each cultivar and the base model.
The data used to create these is in the validation test set
https://github.com/APSIMInitiative/ApsimX/tree/master/Tests/Validation/Peanut
If you are looking for a description of the growth habit of each cultivar (e.g. runner vs bunch) we may need to find a table in one of the publications used to create the model.  Otherwise, start by inferring this from their names (e.g. virginia bunch vs FloRunner)

**Comment by AnnaBlanke** [comment]
Thanks a lot! That´s helpful.
