### ISSUE TITLE
Graphs in NextGen outputting multiple points per day

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#8207]
### What happened?

[Incubation.zip](https://github.com/APSIMInitiative/ApsimX/files/12245270/Incubation.zip)

Each factorial has a different number of points on the x axes even though their clock is the same.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
The problem seems to be in your soils, where FOM in your organic matter is missing for all but the first layer. This is causing an error somewhere, with the everything except the 75cm variation. Putting a 0 into the other layers instead of leaving it blank will let the sim run all the way through and report the values you are expecting.

However, apsim should have responded with some sort of error message, so I'll have to look into it further as to why it doesn't stop the sim and warn you.
