### ISSUE TITLE
uploading soil profile data 

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#8269]
Dear ApsimX community

It is very strange that I cannot identify a proper soil profile for a specific location in ApsimX (for example, Lockhart 2 No 1085). The available soil profiles through the download button in ApsimX GUI are two synthetic soils even I specified the distance within 200km. I tried several locations the results are the same (only synthetic soils popped up). 

To fix the issue, I tried the alternative approach by using the APSIM classic and imported it to ApsimX but the is no simulated results shown. There is no field to choose associated with "Table" in Report and Datastore.     
![image](https://github.com/APSIMInitiative/ApsimX/assets/68523509/53e15850-d1b4-4760-88d7-ace109ba7617)

It would be very appreciated if you could help in solving these two issues! 

Warm regards!

Qunying Luo

**Comment by zur003** [comment]
This is certainly broken. ApsimX is calling the web service with `http://apsimdev.apsim.info/ApsoilWebService/Service.asmx/SearchSoilsReturnInfo?latitude={latitude}&longitude={longitude}&radius={radius}&SoilType="`. Note that no value is being provided for SoilType. Calling the service with a SoilType of "Clay", along with appropriate values for latitude, longitude and radius, returns the Lockhart soil as expected. 
Has there been some change in the ApsoilWebService, e.g., something that made providing SoilType mandatory rather than optional?

**Comment by hol353** [comment]
The server went down last week for 2 days. Back up now. I wouldn't have thought that behaviour changed though.

**Comment by zur003** [comment]
That's weird. The WebService code doesn't appear to have been changed for some time, and the SearchSoilsReturnInfo method clearly should be returning values if SoilType is null or empty. So why has behaviour changed? All I can think of is that the HTTP server may be acting differently and providing something other than an empty string (like maybe a space character?) for the SoilType parameter. But that seems unlikely....

**Comment by par456** [comment]
We just went and checked the server and it seems there was more than one version of the APSoil service on it. We've linked up what we think is the newer one and it now seems to be working.

**Comment by qluo02** [comment]
Thanks for inspecting and fixing this issue!

Cheers

Qunying
