### ISSUE TITLE
Memo not displaying it's contents

### ISSUE THREAD

**Issue by aldoherty** [APSIMInitiative/ApsimX#827]
When clicking or adding you get this error message:

Object reference not set to an instance of an object.
                         at UserInterface.Presenters.MemoPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter) in c:\ApsX2\UserInterface\Presenters\MemoPresenter.cs:line 50

**Comment by jbrider** [comment]
MemoPresenter currently fails when accessing the MemoView as a HTMLView - returning null.
Models\Memo.cs was changed on 22/4/16.
[ViewName("UserInterface.Views.HTMLView")] was changed to  [ViewName("UserInterface.Views.MemoView")]

**Comment by zur003** [comment]
My fault. Trying to make things a bit friendlier for the Gtk# version of the user interface. MemoView uses a RichEdit control, which is dreadful on non-Windows platforms.

**Comment by zur003** [comment]
My comment from yesterday wasn't entirely accurate. The problem I encountered with the Gtk# GUI was that an "HTMLView" was being used for memo display, but the WIndows.Forms version displays stuff using a RichEdit viewer rather than an HTML browser. In this case, use of rich-edit like control is appropriate, and a suitable Gtk counterpart exists (although it doesn't speak RTF), but the logical thing is to provide access to this control via a "MemoView" rather than an "HTMLView". After all, we're trying to display (and allow editng of) a memo, not a web page.

**Comment by jbrider** [comment]
HTMLView is using a newer version of the RichTextEdit (RICHEDIT50W) that MemoView appears to use.
It looks like it is only used in Windows and not in Mono.
Mono should be using the standard RichTextEdit... so on mono it should be the same as a MemoView anyway.... or am I not following how that works.
As far as being able to use Markdown - that seems to be in line with how the code base is being documented - Memo seems to be the best way to document the science used in the crop model.

**Comment by zur003** [comment]
HTMLView really should be displaying HTML in a browser, not trying to convert it to RTF. The RichEdit control is OK on Windows, but is a disaster on Macs, and pretty lousy on Linux. It's actually one of the main reasons for considering going away from Windows.Forms and using Gtk# instead.

I hadn't considered the Markdown aspect. I suppose the questions around it are:

1) Is Markdown the way we want to go for text markup? The alternatives would include RTF (please, NO!), HTML, or Pango markup. Any other likely candidates?

2) Whatever markup mechanism is used, we need to make it convenient for the user to use it. Specifically, a WYSIWYG editor would be preferable to hand-embedded markup.
