### ISSUE TITLE
Option to supply eo for evaporation

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#8290]
### Describe the new feature

Assists with simulation of lab experiments and testing of alternative calculations of eo ahead of implementing actual changes.

**Comment by KirstenVer** [comment]
Controlled environment node does have pan evaporation and various entries that could be used in eo calculations, but not sure if used? And pan evap is not equal to eo anyway.

**Comment by hut104** [comment]
Wow, we added in a switch.... flags used to be no no.

**Comment by hol353** [comment]
No, the final implementation won't be a switch. It was my initial attempt yesterday afternoon to let me do some testing. My PR will try and extract the ```AtmosphericPotentialEvaporationRate``` method from MicroClimateZone.cs into a new class that can be replaced, by the user, with a different implementation. The problem is that there can be lots of MicroClimateZone instances (one for each Zone) so it becomes a bit tricky. I'll work it out.
