### ISSUE TITLE
No water and N uptakes supplied to root

### ISSUE THREAD

**Issue by CinziaCremonini** [APSIMInitiative/ApsimX#8330]
### What happened?

Hello, I'm a new user of the APSIM model. I am trying to simulate a crop rotation with multiple treatments. For this, I am using the "operation model". However, I am encountering the following error:  
"No water and N uptakes supplied to root. Is Soil Arbitrator included in the simulation?". Soil Arbitrator is included in the simulation. I have attached the files. 
Any helps would be appreciated.

[simulation.zip](https://github.com/APSIMInitiative/ApsimX/files/12793908/simulation.zip)

### What Operating System are you on?

MacOS

**Comment by par456** [comment]
Hi,

 I just had a look and in your bienn_0_lq_mais simulation, in the operations on line 14, you have the EndCrop date set before the harvest date (line 13 above it). This is what is causing the error, since it's trying to harvest the crop after its already been ended.

Switching those two dates around fixes the problem.

**Comment by par456** [comment]
Closing this as the problem seems to be solved. Please leave a comment or reopen if it is not.
