### ISSUE TITLE
Replacements folder doesn't preserve changes

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#8331]
### What happened?

It seems like Replacements folders no longer preserve most changes made to Plant models between opening and closing a simulation. The only changes preserved are new direct children. Deeper-nested new children and field changes are not preserved. When re-opening the simulation after closing it the Plant under Replacements no longer has a visible model structure, and on showing model structure all children are read-only. This seems to have been introduced by #8164 as it does not happen on version 2023.07.7277.

Another probably related issue is that adding a Plant to Replacements by dragging and dropping it does not reveal model structure anymore, and similar to above the children are read-only when model structure is manually revealed. This is easy enough to work around by adding the model to Replacements through the "Add model..." interface.

Related: #8258 

### What Operating System are you on?

Windows

**Comment by ilhuber** [comment]
The following change gets around the issue, but is fairly hack-y.
```diff
diff --git a/ApsimNG/Presenters/AddModelPresenter.cs b/ApsimNG/Presenters/AddModelPresenter.cs
index 5dd746d26..dd58a110c 100644
--- a/ApsimNG/Presenters/AddModelPresenter.cs
+++ b/ApsimNG/Presenters/AddModelPresenter.cs
@@ -185,8 +185,8 @@ private void OnAddButtonClicked(object sender, EventArgs e)
                         }
                         else
                         {
-                            child.ResourceName = selectedModelType.ResourceString;
                             bool isUnderReplacements = model.Name == "Replacements";
+                            child.ResourceName = isUnderReplacements ? "" : selectedModelType.ResourceString;
                             // Make all children that area about to be added from resource hidden and readonly.
                             bool isHidden = !isUnderReplacements;
                             foreach (Model descendant in child.FindAllDescendants())
```

**Comment by peter-devoil** [comment]
There's a similarity between this problem - comparing a compiled in resource with a potentially modified component - and the lack of ability to diff components, on a wishlist here: https://github.com/APSIMInitiative/ApsimX/issues/8139

**Comment by hol353** [comment]
This change was a deliberate decision to make it more difficult to casually change models that have a structure (e.g. Plant). As you've discovered, you can't copy a plant from a simulation to replacements and change it. Instead, you should copy the JSON from Models/Resources (https://github.com/APSIMInitiative/ApsimX/tree/master/Models/Resources) and paste it onto Replacements.

Closing this issue. Feel free to comment further though.

**Comment by femiguez** [comment]
We used to add a 'Replacements' folder and add a model as a way of changing deeper parameters in APSIM, but since this is not an option any more it has broken a lot of code that relied on being able to edit the replacement. I haven't tried the workaround you suggested, but the decision seems a bit drastic to me.

**Comment by peter-devoil** [comment]
There's inconsistent behaviour when copying/dragging an object to a replacements folder from a simulation (it stays "readonly"), and "adding model" (it's editable).

**Comment by ilhuber** [comment]
> Instead, you should copy the JSON from Models/Resources (https://github.com/APSIMInitiative/ApsimX/tree/master/Models/Resources) and paste it onto Replacements

I feel like a possible limitation of this approach emerges if there are significant changes between the release version of APSIM you are using and what is currently in the repository, since the Model resources aren't installed as distinct files when APSIM is installed. To avoid this, maybe the files should be packaged with the installer so you don't need to mess with git to get the model version your installation uses. This would become essentially the same workflow as adding a configuration file to APSIM Classic.

**Comment by femiguez** [comment]
@ilhuber we were just talking about this in my group yesterday. The incompatibility between what is in 'Resources' and previous APSIM versions is not a simple issue. Because if you are using an older version of APSIM you can't go back and add model resources. Maybe it is possible to restore editable replacements and address the issue in a different way?

**Comment by hol353** [comment]
Hmm this is tricky. One solution is to add a new item to the right click menu of Replacements to add a model from the resources that are packaged in the version you are using. No need to have the resources as files in the installation directory. They can be extracted from the Models.dll file at runtime.

We were trying to make it a bit more difficult to change a model. Too many users want to change things they shouldn't for _routine application work_. Once they make a change to a model then it is no longer validated and shouldn't be called APSIM Soybean or APSIM Maize in publications.

Two use cases that are valid for changing a model.
1. Adding a new cultivar. This can be done by adding a cultivar under a model in the field. No need to use Replacements.
2. Making improvements to a model or creating a new model. In both cases the developer should be using the latest release so the above mentioned problem by @ilhuber  and @femiguez goes away doesn't it?

**Comment by peter-devoil** [comment]
I think this should be discussed more widely - there's some disagreement here about what constitutes apsim's "typical user".

Some users - typically those associated with investigative, not "routine" activities are tasked with exploring how the internals of models behave, which isnt possible without an understanding of its a) structure, and b) internal relationships. Those relationships are often made evident by breaking components to see the associated damage: eg - what happens if grain number is reduced by substantial amounts? Where does the excess biomass go? What happens if it's zero? Can I add an insect response factor to the GN calculation and test it across lots of environments?

These scenarios are intended for publication; they're bumps on the road to discovery. This roadblock to changing a model simply serves to discourage investigative users. Yes, users can get into trouble modifying "non-routine" parameters - that's why we've got reviewers that would look out for such things. 

Editing JSON with a text editor is very '90s.

**Comment by femiguez** [comment]
@peter-devoil @hol353 @HamishBrownPFR Will there be time to discuss this in our next meeting? I would like to address it at some point. Thanks!
