### ISSUE TITLE
Nutrient variables not being output

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#8336]
### What happened?

[Composite].Nutrient.FOM.C   All zeros
[Composite].Nutrient.FOMCarbohydrate.C Does reports values
[Composite].Nutrient.FOMCellulose.C Does reports values
[Composite].Nutrient.FOMLignin.C Does reports values
[Soil].Nutrient.FOM.C All zeros

[SIm.zip](https://github.com/APSIMInitiative/ApsimX/files/12811968/SIm.zip)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
In your grapevine_test_drama_markos_upd_apsimX_still_same_error.apsimx file I could not find a Nutrient node, which was causing me linking errors when running the simulation. I don't have enough experience with grapevine to know how Nutrient should be included though.

I can reproduce your error with the ExperimentBased_ContinuousforInitialisationV2_Merridin2023.apsimx file. As a test I also output those variables on the Wheat example and it did the same thing, 0s on [Soil].Nutrient.FOM.C and values on the other lines.

I'm not sure if this is expected behaviour or not, will need someone else to come and check this.

**Comment by sno036** [comment]
This is not expected behaviour. The output Nutrient.FOM.C (and N) should accumulate the C and N in the sub components. Can this be addressed?
