### ISSUE TITLE
Wheat model uses the branching rate in previous day

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#845]
Not sure this is a desired feature or bug. 

See the figure below. The branching rate is 3 at day 43. However, the branching number is increased from 4 to 6 (only 2 increase). Seems the branching rate in previous day (day 42) is used in day 43.

![image](https://cloud.githubusercontent.com/assets/1657381/15306641/b8d2427e-1c0f-11e6-8e6f-ceb6f75738f9.png)

**Comment by HamishBrownPFR** [comment]
@byzheng Good work spotting this Bangyou.

The problem comes from this section of code in Structure.cs.  A new cohort of leaves is initiated by the DoLeafTipAppearance() method and its population is set at current TotalStemPopn, then stem population is incremented for todays branching.  

I suspect the order of these events should be reversed otherwise potential tillering is offset by one haun stage.  However, this will effect other models so will need some checking of its impacts.  I will get onto that before there are any more models there that it will impact  

![image](https://cloud.githubusercontent.com/assets/7295858/17242180/daa572ce-55c9-11e6-829b-ada31607c461.png)
