### ISSUE TITLE
Ability to report after initialisation on the first day of the simulation

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8484]
### Describe the new feature

Particularly useful for getting changes in pools. There is currently a "FinalInitialise" - unsure what this really is but soil arrays are reported with zeros when it is used.

**Comment by peter-devoil** [comment]
also https://github.com/APSIMInitiative/ApsimX/issues/8477

**Comment by hol353** [comment]
I have added a 'StartOfFirstDay' event for reporting at the beginning of a simulation after all models have properly initialised themselves. Don't use 'StartOfSimulation' because not all models will be correctly initialised. 

To get a row of output at the end of the simulation you can use 'EndOfSimulation'. I was wondering about a 'EndOfLastDay' event to match 'StartOfFirstDay' but it isn't really needed.
