### ISSUE TITLE
Putting y-axis on the right distorts graph

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8522]
### What happened?

Please note the position of the black and green lines. Green lines should never be on the top.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/3cb3c5ff-5db5-46ab-9949-eb3eba15c9b5)

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/fcb3ce3c-07ff-452b-b8a9-1c45d9a2d23b)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Just looking at your graph @BrianCollinss, are you setting your Total series as the one with the axis on the right? I note that it's using a different scale (0-50 on the left, 0-70 on the right) in your graph, which would explain the change in the lines.

Your Live series has a maximum of 50, so it's highest point is at the top of the graph on the left axis, and your Total series has a maximum of 70, which is the highest point on the right axis. If you want to have the same units on both sides of the graph, I would suggest manually setting the maximum of the left and right axis so they are on the same scale. That should solve the problem.

**Comment by par456** [comment]
@LenLon 

I'm not seeing behaviour like that on my end, though there is something strange going on with that graph. I can count 8 LL15 points on your graph, however your table only contains 6 pairs of values. The LL15 line also seems to start at a different depth.

Does your apsim file happen to either contain multiple soils in a simulation, or just multiple simulations in that file? I have a feeling that the wrong soil is being referenced in that graph. 

Would be able to upload a copy of your apsim file here so I can take a look at it?

**Comment by BrianCollinss** [comment]
Thanks @par456 . Should it not be done by the code automatically?

**Comment by par456** [comment]
The graphing system doesn't really understand if two variables have the same units attached to them, so it just scales every axis automatically for whatever content is connected to it. 

It would have to be an optional flag to match the axis, otherwise it would ruin graphs with different units on either side (which it's often used for as well). In my opinion it's better to just manually set the axis at that point so you have better control over how it displays.

**Comment by BrianCollinss** [comment]
Cheers @par456 . Noted.

**Comment by LenLon** [comment]
@par456 Thanks for having a look!

I setup the soil profile using the apsimx R package by @femiguez using the `get_isric_soil_profile()` function, which currently does not play nice with ApsimX due to the renaming of the nodes where NH4, NO3 and Urea conc. are given. For some reason I also cannot change the display there between kg_ha and ppm anymore (the GUI changes, the values do not). 

[APSIMX_sims.zip](https://github.com/APSIMInitiative/ApsimX/files/13919731/APSIMX_sims.zip)

We've encountered the issue before that ISRIC soils seem to have LL15 values lower than the AirDry values, which can be fixed by the `get_isric_soil_profile()` function, fixing LL15 at AirDry values. I do observe now that I have different numbers of layers in the Soil.Water and Soil.Chemical nodes, for example. :(
