### ISSUE TITLE
DataStore keeps the old column names

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8528]
### What happened?

When a column is renamed and simulations are re-run, DataStore still shows an empty column with the old name. Only removes it when refreshed.
![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/5922dc46-e612-4ff0-8d91-919a615c7234)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
This one was investigated when working on #6807. This requires large changes to be corrected. Best to correct this when making larger scale changes to DataStore.

**Comment by lie112** [comment]
This can be manually addressed by deleting the .db database file and running the simulation again.
One solution would be for empty datastore menu option to delete the db file rather than just empty all tables, thus maintaining column names and order. Maybe the empty datastore functionality is needed elsewhere other than just a user UI option. Adding a ResetDataStore menu option that does the hard delete might be useful, but it's often locked by the UI so that needs to be addressed.

**Comment by BrianCollinss** [comment]
How about automatically refreshing the DataStore whenever one of the Reports are changed and saved? I am not sure if it is plausible to implement.

**Comment by par456** [comment]
Not really with the way reports currently work. The system doesn't know what columns it needs to fill until the simulations are running, as there isn't a way to pre-empt based on what is written into reports (and that only makes sense to implement if you always run all simulations in the file).

If you use the "Empty the Datastore" menu option it will clear all the columns out, and that how I get rid of columns I don't need when working on a file, but that obviously gets rid of everything else as well.

The reason the datastore doesn't full clear (like the menu option) when running a simulation, is so that you can run a couple of simulations separately one after another without the DB resetting between runs.
