### ISSUE TITLE
Humic Nitisols Missing

### ISSUE THREAD

**Issue by Malitoz** [APSIMInitiative/ApsimX#8592]
### What is your question?

I wish to use Humic Nitisols for my work. I searched in Download Soil but I got soil for a different location. I'm using the following coordinates; -0.517, 37.459.

**Comment by BrianCollinss** [comment]
What do you mean by "a different location"?

**Comment by Malitoz** [comment]
Does APSIM include Tropical Humic Nitisols? If so, how can I incorporate it into my simulation? Please provide the coordinates (latitude and longitude) if available.  Here's a video link to further clarify: https://1drv.ms/v/s!ArK9rrVUdFuKgop_KPv5r35rC2Pt5Q?e=cW5KDq

**Comment by BrianCollinss** [comment]
APSIM NextGen interface allows downloading soil data from two sources: APSoil, ISRIC. the first can be downloaded in full from APSoil web page. ISRIC is a gridded database and you can only extract data based on coordinated. I suggest you download APSoil and see if your soil (or something similar) is included.

**Comment by zur003** [comment]
And actually the "ISRIC" data isn't downloaded directly from ISRIC; it's using gridded data set up for the CSIRO "World Modellers" project, which was extracted ,, ifrom the ISRIC data. In any case, if you enter a location it provides soil data for the nearest grid point rather than your exact location.

It this case, as the site appears to be located at University of Embu, it would probably be best to see whether anyone at the university has suitable data and, if they do, enter it manually.

I would also note that ISRIC does have a more detailed soil data set for Kenya (see [https://www.isric.org/projects/soter-based-soil-property-estimates-kenya](https://www.isric.org/projects/soter-based-soil-property-estimates-kenya). However, transforming the ISRIC data into a form suitable for APSIM usage is not a trivial exercise.

**Comment by Malitoz** [comment]
Thank you for your feedback @BrianCollinss & @zur003 this is helpful.

**Comment by BrianCollinss** [comment]
No worries. If your question has been answered, you can close this issue.
