### ISSUE TITLE
Cannot ignore the missing values in the excel file on graph

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#8599]
### What happened?

In the master branch of APSIMX. Generate a graph with error

```
LAI (Observed): NaN Values found in points. These may be empty cells in the datastore.
LAI (Observed): 1 points where Y is NaN, but X is valid.
```

The example node is `.Simulations.Validation.Growth Experiments.Wagga.Wagga2008.Graphs.Garnet.LAI` on Canola.apsimx (validation test).

For example, the excel file is located `Tests\Validation\Canola\Wagga2008.xlsx`.

The cell `N57` is an empty without space, tab, or other special character. But source codes is red as NaN value. 

<img width="370" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/1657381/a890b7e1-20b6-472d-bb6f-06bd4986b4e3">

 

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@byzheng this is expected behaviour. These messages are warnings and not errors and are intended to let users know that data is potential missing or has another issue.

**Comment by hol353** [comment]
The problem is that observed data is by nature sparse so predicted/observed graphs often have lots of these warnings that 'become normal' for the user and get ignored.

**Comment by ric394** [comment]
> The problem is that observed data is by nature sparse so predicted/observed graphs often have lots of these warnings that 'become normal' for the user and get ignored.

@hol353 Would it be beneficial to provide a checkbox to turn off/turn on the messages so a user can decide when they can see the messages?

**Comment by hol353** [comment]
I don't think we want a checkbox. Everyone will just turn the messages off. 

I would argue that observed data is sparse and is not an error and shouldn't be written to the status window.

**Comment by par456** [comment]
This message was added as part of a bunch of messages to inform users when values weren't appearing on graphs, since it was hard to tell why a point wasn't appearing. (such as, is no data present because you have the column wrong, or because it's NaN, or because it's outside the axis).

The messages are useful for debugging when a graph is wrong, so I wouldn't want to remove them completely, but is there somewhere else they can go so we can bring them up if we do need them?
