### ISSUE TITLE
CriticalNConc in leaf cohort model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#86]
In the leaf cohort model (L799 of LeafCohort.cs and L803 of Leaf.cs), the functional N concentration (`FunctionalNConc`) is calculated according `CriticalNConc` and `MinimumNConc`. From my understanding, all critical N belong to structural N. Is this correct ( @HamishBrownPFR )? If so, it could make sense to assume critical N also include structural and metabolic N.

L799 of LeafCohort.cs

    FunctionalNConc = (LeafCohortParameters.CriticalNConc.Value - 
          (LeafCohortParameters.MinimumNConc.Value * StructuralFraction)) *
          (1 / (1 - StructuralFraction));

L803 of Leaf.cs

     double FunctionalNConc = (LeafCohortParameters.CriticalNConc.Value - 
            (LeafCohortParameters.MinimumNConc.Value * 
             LeafCohortParameters.StructuralFraction.Value)) * 
             (1 / (1 - LeafCohortParameters.StructuralFraction.Value));
                
BTW: function `MinNconc` should return `MinimumNConc`, not `CriticalNConc`

    public override double MinNconc
    {
        get
        {
            return LeafCohortParameters.CriticalNConc.Value;
        }
    }

**Comment by HamishBrownPFR** [comment]
If we think of the N in the leaf in 3 layers.  
- The first is structural N which does not contribute to photosynthesis so if the leaf were at MinimumNConc concentration all the N would be structural and it would not be able to conduct photosynthesis.
- The second layer is metabolic which is the photosynthetic machinery.  As N increases from MinimumNConc to CriticalNConc photosynthesis will increase also.  
- The third layer is non-strucutural which is photosynthetic machinery excess to the needs for maximum photosynthesis and nitrates.  As leaf N exceeds CriticalNConc it is accumulating non-structural N and this has not additional benefit to photosynthesis.

So for calculating the effect of leaf N on photosynthesis (RUE) it is changes between MininumNConc and CriticalNConc that are important.  FunctionalNConc represents the upper limit for MetabolicNConc to which actual MetabolicNConc is related to determine FN.  The RUE model then relates RUE to FN.

I think the problem here is you are mixing critical and functional N.  You are correct that criticalN includes structural N.  That is why I created the functionalN variable to remove structural because it has no effect on photosynthesis.

MinNconc SHOULD!!!! return CriticalNconc.

The MinNconc property is not used in internal leaf calculations.  It is passed to the arbitrator as the minimumN concentration that is required for leaf growth.  The arbitrator partitions N to organs to meet their MinNconc in the first pass and then to meet their maxNconc in the 2nd pass.  It is a priority for a plant to partition sufficient N to leaves to be functional and not just enough to grow so functional N needs to be included in the first priority for leaf.

**Comment by HamishBrownPFR** [comment]
Hi Bangyou.

I have posted a response to this.  I am pleased to see another set of critical eyes looking through the PMF code.  I am planning to document the N partitioning stuff in more detail soon.  But please keep asking questions via the post if you see stuff that doesn’t appear to make sense as a lot of this is my logic that has not really been tested and there are bound to still be errors.

I seem to recall an email coming through from you in March while I was on holiday (not answering emails) and I haven’t got that far back in my inbox (and probably won’t now).  Please re-send the email if your questions are still outstanding.

Hamish

**Comment by hol353** [comment]
I can't see a defect or enhancement request here so closing.
