### ISSUE TITLE
Replacing BinaryFormatter 

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8680]
As highlighted in #8446 BinaryFormatter that we use for serialization, [is going to be deprecated this year](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md)  along with .net 6.0, so when we move .net frameworks next, this key part of APSIM will no longer work.

From what I've see looking at the uses of serialization, we use it for server socket communication and for deep cloning APSIM objects. For the server socket communication, we could probably get away with using JSON serialization as I don't think it needs to be hyper performant (correct me if I'm wrong).

For deep cloning APSIM objects however, JSON serialization will be way too slow, since it's even slower than BinaryFormatter and we clone the apsim objects a fair bit.

So I'm opening up this issue to try and gather some notes and opinions on how we tackle this. I've looked at some serializers to see if we could do a like-for-like swap, but most will require at minimum, retagging our classes throughout the project and often they can't handle circular references like we frequently have.

Serializers I've looked at:
[Protobuf-net](https://github.com/protobuf-net/protobuf-net) - Fast serialization, requires full retagging
[Memorypack](https://github.com/Cysharp/MemoryPack) - Fast serialization, struggles to handle models, poor feedback
[MessagePack-CSharp](https://github.com/MessagePack-CSharp/MessagePack-CSharp) - Fast serialization, requires full retagging, has typeless mode but can't handle models like that

Retagging the project would be a crazy amount of work however, and most likely cause a lot of conflicts since it'll touch everything in models and will take some time to do. I would really prefer to avoid that if possible.

Having a specific deep copy function might be a better solution for that, however the same problem exists, the ones I've tried either are too old of date to be any use, or simply can't handle our model structure for a file.

DeepCopy Libraries I've looked at:
[DeepCloner](https://github.com/force-net/DeepCloner) - Doesn't work on .net 5 or later
[FastDeepCloner](https://github.com/AlenToma/FastDeepCloner) - Can't handle models, poor feedback

The last option we have for deep clone would be to try and create our own so we can actually deep copy models in a sensible way, but again, would be a pretty big project to make that happen.

**Comment by zur003** [comment]
I totally agree with your analysis. JSON should be OK for the socket stuff, and I think I've worked through a solution for cloning, though I'm not sure how best to package it. What I've done is re-build [DeepCloner](https://github.com/force-net/DeepCloner) from source, adding net6.0 to the target frameworks. This revealed a different problem. Most of the time we don't actually **want** do a full deep copy. Our current approach of serializing and deserializing means that fields tagged with the "NonSerialized" attribute are not copied, and that's actually the way we want things to be. A true deep copy creates all sorts of problems with things like Locators and their caches, particularly within Manager scripts. I've been able to get around that issue by modifying DeepCloner so that it doesn't copy fields tagged as "NonSerialized". This seems to do what is required, and is a bit faster than our current approach (it appears to reduce overall run time for the Wheat validation by around 10%).

My main question now is how to "package" the changes. [DeepCloner](https://github.com/force-net/DeepCloner) uses the MIT license, so we can largely do whatever we want with the code, which hasn't been very actively maintained (the last code change was 2 years or so ago). Should we fork DeepCloner, keeping it as a separate package while bringing it up-to-date and adding the option of not cloning suitably tagged fields, or should we just take the source, extract the bits that we need, and embed that into Apsim somewhere (e.g, within APSIM.Shared)?

**Comment by hol353** [comment]
Wow, well done Eric (again). The open-source way is to fork the repo, make the changes we want and keep it as a separate package. We can change the readme file, if it has one, to say what we changed. Others may find it useful.

**Comment by par456** [comment]
Sounds like you've done some good work there Eric, and I agree with Dean, we should probably fork DeepCloner because we aren't going to be the only project that is running into this problem. If you've adapted it to work with the BinaryFormatter serialization tags, that'll make moving away from BinaryFormatter much easier.

**Comment by bj-far** [comment]
@par456 I just discovered this issue - I upgraded a utility app that used .net 6.0 to .net 8.0 and ran into it right away with opening .apsimx files. There is a workaround! It will allow you to get around the immediate issues whilst tackling each part of the problem (and upgrading to .net 8.0) if so desired. Works for opening .apsimx files, anyway:
[https://github.com/nuke-build/nuke/issues/1282](https://github.com/nuke-build/nuke/issues/1282)

**Comment by zur003** [comment]
Time for an update here. As of early February 2024, there is a [fork of DeepCloner](https://github.com/adimosh/DeepCloner) which was reconfigured to support recent versions of .NET; this is available on nuget as DeepCloner.Core. However, we cannot easily use this "out of the box" as it deep-clones everything, including fields tagged with "NonSerialized", which causes a bit of grief in the ApsimX context. I've therefore forked the new fork, and added a couple of lines to suppress the cloning of "NonSerialized" fields, and this works smoothly. The modified project is available from my [Github repository](https://github.com/zur003/DeepCloner).

I'm not quite sure where to take things from here. It would be simple to just add the new .csproj to ApsimX. However, it would probably be better if the suppression of cloning of NonSerialized fields could somehow be made an option, with that change then being merged into the DeepCloner.Core nuget package. Adding an optional argument is a bit trickier than it sounds, given the series of calls made to get to the point where the suppression actually occurs. And there is the question of whether the maintainer of DeepCloner.Core would be willing to merge such changes....

**Comment by hol353** [comment]
Well done Eric. It would be cleaner for us if we could get the DeepCloner.Core nuget package changed to optionally suppress the cloning of 'NonSerialized' fields. It would also be useful for others as well. It is at least worth trying. Do you want to contact them or raise a PR with them?

**Comment by zur003** [comment]
I raised a PR for DeepCloner.Core, but there was no response, so we may need to build our own version rather than using a Nuget package. 
Although the cloning works well enough, we still need to serialize/deserialize for APSIM.Server communication. Following the suggest of @par456 above, I've played around with using JSON for the task. It looked like it should be simple, but it's not. The main snag I've run into inn the APSIM.Server context is the deserialization of DataTable structures.  Basically what happens is that they serialize into nested arrays, but the deserialization process doesn't know that these arrays need to be converted back into a DataTable unless you tell it to do so explicitly. It the DataTable is a member of a class, it can be tagged with a `[JsonConverter(typeof(DataTableConverter))]` attribute to handle this, but a DataTable on its own is tricky. I have a workaround, though I'm not entirely happy with it. 
Someday soon, I'll tidy up what I've done and submit a PR for it, so others can have a look and see what they think.
