### ISSUE TITLE
Report filters result in some years being repeated and some years being removed

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8721]
### What happened?

[APSIM (Custom Build) 2024-02-29 14-06-50.zip](https://github.com/APSIMInitiative/ApsimX/files/14442682/APSIM.Custom.Build.2024-02-29.14-06-50.zip)

I ran simulations for 2010-2023. When I filter the daily report, the 2010-2011 data are repeated, and the rest of the data are not shown. Or, something is wrong with Clock-Today when it is filtered! These are the filters I tried:

`"SowDate" = "01-Jul" and "Cultivar" = "Test1" and "Population" = 50 and "AutoIrrigate" = "false"
`

`[SowDate] = "01-Jul" and [Cultivar] = "Test1" and [Population] = 50 and [AutoIrrigate] = "false"`

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I've been having trouble reproducing this bug. I made a small experiment to do the same multiple filters you have, but it was working on my end.

Do you have a file on hand that causes this to happen?

**Comment by BrianCollinss** [comment]
I had attached the file to the previous comment

**Comment by par456** [comment]
That zip only contained a video of the problem and not an apsim file that I could use to reproduce it.

**Comment by BrianCollinss** [comment]
[SRAT-14-Feb.zip](https://github.com/APSIMInitiative/ApsimX/files/14645170/SRAT-14-Feb.zip)

When I use the following filter, I only see data for 1980.
`"Cultivar" = "Fast" and "Population" = 50 and "AutoIrrigate" = "false"`

But the other method works now:
`"Cultivar" = "Fast" && "Population" = 50 && "AutoIrrigate" = "false"`

**Comment by par456** [comment]
It looks like this problem is related to #8519

The DataStore uses the PagedDataProvider to search up rows to be displayed. But from what I can tell, it'll get 50 rows in the order they were read into the DB and then sort them by simulation name and clock today, leading the whole table to be out of order and basically not sorted. 

Then when you go scrolling though, you can easily miss entire years worth of data because the year 2000s data is mixed in with 1984 60% down the scrollbar.

In this case there is also an error that eventually ends all the permutations (just in different years) so I saw data from 1980 up to 2000 when I copied it out to excel and sorted it there, but if you just scroll through you'll be lucky to find any dates past 1990.

To test I ran the datastore reader with both the rowid filter and without it and got the same data, just with the rowid filter, it's completely unsorted. Will need to further investigate this problem, might need some help from @hol353 to understand what the pageddataprovider is needed for.
