### ISSUE TITLE
When two booleans are used as Report Events, records may repeat

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8896]
### What happened?

I am using two booleans as daily report events. When both are true, records are repeated. Shouldn't they be treated as one 'true' condition when both are true?

```
[Maize].IsAlive == true
(bool)AutoIrrigate.GetProperty("IrrigNeeded") == true && (bool)AutoIrrigate.GetProperty("IrrigAllowed") == false
```

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/7b53aed4-a66a-454d-866d-938a540a5773)

If I make another copy of the same boolean in report events panel, I will get another copy of those records:
![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/7559eb18-60f0-4330-ac27-a46106311cb7)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I think this is working as intended, as each line in the event will trigger a row to be written. For example, if I was to put:
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/3aa68ad5-b66c-4dfb-bdce-03d6259007e4)


I then get it repeating the row 4 times per day, since the events are 4 copies of the end of day event:
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/850f63a7-f8ea-4353-b4c2-936efe4346d4)

In this case, if you want all 3 of those conditions to be satisfied, you'd write it as:
`[Maize].IsAlive == true && (bool)AutoIrrigate.GetProperty("IrrigNeeded") == true && (bool)AutoIrrigate.GetProperty("IrrigAllowed") == false`
