### ISSUE TITLE
Physical grid needs warning note to say red values are estimated values

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#8906]
### Describe the new feature

In order to make sure users are aware that clay, silt, etc values coloured red are estimated, a note should be added to make users aware.

**Comment by femiguez** [comment]
I would say that all soil properties are estimated. The difference with auto-generated clay, silt and sand is that they could be quite different from the soil being used and often unrealistic. This was raised with the new soil temperature model, which requires clay and silt. I think that having them as red is already an indication that they are 'different' from the rest. Rather than a 'warning' maybe a message could be displayed when adding the new soil temperature model indicating users that they should change the auto-generated clay, silt and soil to better match their soils.

**Comment by sno036** [comment]
I suggest that the text be modified to "Note: Values in red are estimates only and needed for the simulation of soil temperature. Overwrite with local values wherever possible." and that the text be coloured red.
