### ISSUE TITLE
Mismatch between observed and predicted data

### ISSUE THREAD

**Issue by ekhaembah** [APSIMInitiative/ApsimX#8994]
### What happened?

Predicted and observed dates not matching on the time series graphs. E.g. below
![image](https://github.com/APSIMInitiative/ApsimX/assets/12144731/1f446350-0428-4eb8-bec8-ae503c23efed)

[Oats.zip](https://github.com/APSIMInitiative/ApsimX/files/15492774/Oats.zip)

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
An update: We have found the problem. The graphing code in APSIM doesn't like empty cells in the Clock.Today column of the spreadsheet. Interestingly, this bug in the graphing code has been there since the very first version of APSIM NG. I'm amazed noone has spotted this. Well done. Perhaps you should get a prize.

I would like to know how you can have measurements in the spreadsheet that don't have a date. The workaround is to add dates for these measurements or to delete the rows.

We'll think about how we fix the bug.

**Comment by hol353** [comment]
More information about what I found in the code:

Line 1528 of GraphView.cs has these lines:
```c#
// Create a new data point for each x.
double[] xValues = GetDataPointValues(x.GetEnumerator(), xAxisType);
double[] yValues = GetDataPointValues(y.GetEnumerator(), yAxisType);
```

The method GetDataPointValues strips invalid values from the array passed in. The problem is that it does this for x and y values independently so a value will be removed from x and not y. When this happens the x and y values no longer match each other. We need to process x and y together.

**Comment by ekhaembah** [comment]
> An update: We have found the problem. The graphing code in APSIM doesn't like empty cells in the Clock.Today column of the spreadsheet. Interestingly, this bug in the graphing code has been there since the very first version of APSIM NG. I'm amazed noone has spotted this. Well done. Perhaps you should get a prize.
> 
>**I would like to know how you can have measurements in the spreadsheet that don't have a date**. The workaround is to add dates for these measurements or to delete the rows.
> 
> We'll think about how we fix the bug.

Maybe too late but measurements without dates relate to graphing maximum size of the leaf against leaf position (data below)<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CFLEZK/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CFLEZK/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


SimulationName | MaxLeafSize.Script.LeafPosition | MaxLeafSize.Script.MaxLeafSize
-- | -- | --
RS_Oats_9899_IrrigFull | 1 | 347.9
RS_Oats_9899_IrrigFull | 2 | 470.1
RS_Oats_9899_IrrigFull | 3 | 752.8
RS_Oats_9899_IrrigFull | 4 | 1727.4
RS_Oats_9899_IrrigFull | 5 | 4210.6
RS_Oats_9899_IrrigFull | 6 | 3681
RS_Oats_9899_IrrigFull | 7 | 4710
RS_Oats_9899_IrrigFull | 8 | 5040.5
RS_Oats_9899_IrrigFull | 9 | 4201
RS_Oats_9899_IrrigNill | 1 | 400.4
RS_Oats_9899_IrrigNill | 2 | 561
RS_Oats_9899_IrrigNill | 3 | 894.3
RS_Oats_9899_IrrigNill | 4 | 1776
RS_Oats_9899_IrrigNill | 5 | 2285.7
RS_Oats_9899_IrrigNill | 6 | 2598.9
RS_Oats_9899_IrrigNill | 7 | 2829
RS_Oats_9899_IrrigNill | 8 | 2837
RS_Oats_9899_IrrigNill | 9 | 1659
RS_Oats_9899_IrrigED1 | 1 | 444.6
RS_Oats_9899_IrrigED1 | 2 | 695.2
RS_Oats_9899_IrrigED1 | 3 | 1045.6
RS_Oats_9899_IrrigED1 | 4 | 1658
RS_Oats_9899_IrrigED1 | 5 | 2400



</body>

</html>
