### ISSUE TITLE
Once you go dark, you cant go back

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#9112]
### What happened?

In the global settings, unselecting "dark mode" doesnt unselect dark mode

### What Operating System are you on?

Linux

**Comment by lie112** [comment]
In the running for Best Issue Title of 2024!

**Comment by par456** [comment]
So I spent a couple of hours looking into this and I think it's a restriction within Gtk3 whcih we use for the GUI. To actually get the dark mode to activate, we have to set an environment variable called GTK_THEME right at the start of launching the GUI (UserInterface.cs).

I had a play around with this, and there is no way to change this setting once it is set. I tried completely closing the GUI and restarting Gtk and it didn't change from dark mode to light mode. I think it would actually require restarting the program completely. There are other stylings in the GUI too that aren't linked to the Gtk variable, so when you change it, you end up in a weird half theme, where some theming is dark mode, but some is not.

So I'm going to suggest we just address this with a popup when you change the darkmode setting saying it won't take effect until you restart the GUI, and also stop the other theme changes from going to dark mode when the main part of the GUI isn't yet.

**Comment by peter-devoil** [comment]
On linux, I'm seeing it stay dark even after a restart. It's an oldish installation, so I'll check what happens when I wipe the settings file (after I find it)..

Many other progs wont actually change colour without a restart, so I wouldnt be upset about that..

**Comment by hol353** [comment]
I wouldn't be surprised that when the GUI is run on Linux it uses the Linux desktop theme. I suspect @hol430 set that up as he was on Linux.

**Comment by peter-devoil** [comment]
I'm frankly amazed that linux has even a concept of desktop themes, let alone frameworks that actually use them!

**Comment by par456** [comment]
I'm just going to reopen this as there is a little of work here to do. 

At the moment if you change that setting on windows some of the dark/light theming changes, but not all, so you end up with invisible graph axis and other oddities until you restart apsim. See my comment from above about what is needed.

**Comment by ric394** [comment]
@par456 do you mind if I give this one a crack?

**Comment by hol430** [comment]
Yeah, my memory of this is a little hazy, but I'm pretty sure apsim is simply respecting the system-wide settings when run on Linux. On Windows, I think we assumed that not many people would (intentionally) have a correctly-configured gtk installation, and so therefore we decided that it was safe to ignore the system-wide settings.

Specifically, the gtk setting you want to look at is `gtk-application-prefer-dark-theme` (`Gtk.Settings.Default.ApplicationPreferDarkTheme` in .net lingo). If this is true, gtk will try to use a "dark" theme. If false, gtk will use the system-wide theme. The default value of this parameter is based on your gtk config files in `/etc/gtk-3.0`, `$XDG_CONFIG_DIRS/gtk-3.0`, and `$XDG_CONFIG_HOME/gtk-3.0`. If you change your gnome system to light mode and apsim (and/or other gtk apps) are still dark, you should look in these directories because you've probably set this to true somewhere.

So if you really want apsim to run in light mode, and don't want to change the system-wide settings, and also don't mind blinding yourself when switching between dark and light applications, then setting this property to false after calling `gtk_application_init()` should get the job done.
