### ISSUE TITLE
GTK warnings and errors

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#9219]
### Describe the new feature

When using VS Code these warnings and errors appear.

![image](https://github.com/user-attachments/assets/7826f336-4f3a-49c4-afa6-159152b64f1b)

The `GTK-CRITICAL` outputs usually happen when moving the mouse over various view components and don't seem to be critical.

Is there any way to clean these outputs up or resolve them?

**Comment by zur003** [comment]
PR #9224 eliminates most of the problems I encountered. A couple of rough spots remain:

1. On my Ubuntu system, I see "Unable to load sizing from the cursor theme" messages whenever I go to a view that holds a GraphView, This is because OxyPlot's PlotView attempts to load a cursor of type Gdk.CursorType.Sizing. This cursor type is not available by default under Wayland.
2. The font warnings seem by @ric394 also come from GraphView, which tries to explicitly load the Calabri Light font for use with plot annotation. However, Calabri is a Windows font, and may not be present on other platforms.

There may be other errors lurking somewhere that I haven't seen, but these Gtk-CRITICAL messages shouldn't be ignored. They usually indicate a problem of some sort which may lead to memory leaks or worse.

**Comment by hol353** [comment]
Moving the mouse over the Experiment view gives lots of these GTK-CRITICAL errors:
```
(ApsimNG:32384): Gtk-CRITICAL **: 13:58:34.539: gtk_tree_model_get_iter: assertion 'path != NULL' failed

(ApsimNG:32384): Gtk-CRITICAL **: 13:58:34.542: gtk_tree_model_get_iter: assertion 'path != NULL' failed

(ApsimNG:32384): Gtk-CRITICAL **: 13:58:34.543: gtk_tree_model_get_iter: assertion 'path != NULL' failed
```
