### ISSUE TITLE
CroptimizR parameter table cannot be edited

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9293]
### What happened?

When I remove a row, it returns when I save. Also I have this in the APSIM file now:

```
        {
          "$type": "Models.Sensitivity.Parameter, Models",
          "Name": "",
          "Path": "",
          "LowerBound": "NaN",
          "UpperBound": "NaN"
        }
```

https://github.com/user-attachments/assets/5f7fd4ad-b2cf-4609-9bf6-8322039cb2a5

### What Operating System are you on?

Windows

**Comment by par456** [comment]
@hol353 This is actually a bug in all models that use the ClassWithOneListProperty DataProvider. The rows are deleted from the dataprovider, but not from the model reference that is put into the ReplaceModelCommand, therefore the changes aren't saved.

Individual cell edits do work though.

Might need to show me how the model gets updated change events, because I couldn't figure out where the link between the grid and model actually was.
