### ISSUE TITLE
Renaming manager scripts does not update name in report module unless ApsimX is restarted

### ISSUE THREAD

**Issue by LenLon** [APSIMInitiative/ApsimX#9332]
### What happened?

This might be intended or an edge case not worth fixing, but I thought I'd bring it up for posterity:

If you rename a manager script in your simulation that generates custom output variables of the report format `[ManagerScript].ScriptSimulationsSimulationFieldManagerScript.Variable`, e.g. to "ManagerScriptTWO", the report variable has to be `[ManagerScriptTWO].ScriptSimulationsSimulationFieldManagerScript.Variable` to keep working.

Only after a restart it's `[ManagerScriptTWO].ScriptSimulationsSimulationFieldManagerScriptTWO.Variable`, which seems a little inconsistent.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Can I get a copy of your apsimx file plus the weather file (if needed) please @LenLon ?

**Comment by LenLon** [comment]
Apsim and weather file are here [weather.zip](https://github.com/user-attachments/files/17093000/weather.zip)

**Comment by ric394** [comment]
This looks to be exposing and reporting variables as intended. 
If you change the name of the manager script you will have to change the report variable's model name as well.

Using a report variable like `[Cumul_report_vars].Script.PublicPropertyName` seems to be working, even if I change the name and update the report variable's model name to reflect the name change. 

I believe having to use the full apsim path of script is no longer required, however if you're using an older version of APSIM, you may still have to use it.

**Comment by par456** [comment]
Yep, Julian is right on this. The full name of a script class shouldn't be required when referencing variables anymore. Scripts are now given a generated class name based on the node path (which changed when you named the node), but you should always be able to refer to a script using just [ManagerName].Script.MyVariable 

Script is actually a property of manager that gives you a reference to the script object so that you don't need to know it's name.

You can also use GetProperty("VariableName") function in manager to get the value of a variable.

At this point there should never be a situation where you need to work out the dynamic name given to a script to reference it, those long script names are there to avoid namespace clashes, so we want helper methods to avoid needing to you them.
