### ISSUE TITLE
Regression Not Working

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#9373]
### What happened?

Regression for OvP graphs is not working consistently in the attached simulation. It works for the top graph (OvPsph), but not for the next one (OvPVolub. The data are bing graphsed, but there must be a problem wiht the Volub observed data that I can't find, or the Regression node is not functioning properly. Can you please check that for me. 
[RegressionNotWorking.zip](https://github.com/user-attachments/files/17285183/RegressionNotWorking.zip)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
One of the cells in the Eucalyptus.Stem.Volub column of your observed data has a space or other hidden character in it, because of that, excel thinks the column is of type string instead of numbers.

To fix this, in excel I used the column filter to show only the 'Blank' cells, selected all those and hit delete, then in apsim, cleared the datastore and reran the simulation. The regression line worked then.

**Comment by sme016** [comment]
I'll test that. Much appreciated.

**Comment by BrianCollinss** [comment]
I have had this issue when I used Excel formula which inserted "" for empty cells.

**Comment by sme016** [comment]
Yes - that is what I had done too.

**Comment by BrianCollinss** [comment]
It's hard to fix if Excel sheet is messy (i.e., empty cells randomly distributed!).

**Comment by sme016** [comment]
Yes - my Excel file is messy like that, but Andrew's advice worke perfectly. Thanks
