### ISSUE TITLE
Merge duplicate plant mortality parameterisations

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#953]
@rcichota 

There are two ways to parameterise plant mortality in PMF.  The Structure object has a PlantMortality function and Plant has a MortalityRate function that both do the same job.  

The plant class is the right place to put this function as structure can pick it up easily and I am happy to make this merge. 

Two questions for you @rcichota 
1. There is a MortalityRateModifier parameter that is declaired as 1 and never changed.  Is it OK to remove this?
2.  Is all your chicory stuff in the master at the moment and if not are you doing anything in the plant class that will get mucked up if I make changes here?

**Comment by rcichota** [comment]
It is perfectly ok to merge both. I was meant to talk to you about that last month, but run out of time. I am not intending to do any changes in the code right now, unless something extraordinary occur. All changes made are merged to Master. I am working only on the parameterization of the chicory model now. So you may go ahead with the merging.
The idea of adding the MortalityModifier was to have some way to change the mortality rate on the go. I guess I was thinking about a grazing event, for example, where the mortality rate might increase momentarily due to pugging (could be a disease, etc). I am not so sure that the modifier was a good enough idea, in fact I cannot see it working as such all the time. So you may remove it and if you have a good idea of how a external, and probably temporary, modifier could work, that would be great. In any case we are not needing it now, we may get back to this when we actually need...
