### ISSUE TITLE
Cultivar parameters reported at Harvesting vs PlantEnding

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9544]
### What happened?

This might be intentional. When I report a plant parameter at [Wheat].Harvesting, it is equal to the number specified by the Cultivar. However, when I do the same at [Wheat].PlantEnding, the reported value is equal to the parameter's default value in the model. I understand that when PlantEnding is called there is no plant on the ground. So, what is the best approach here? Could this be misleading in some situation, like mine? Should APSIM NOT report the value of plant parameters whatsoever when there is no plant on the ground?

![image](https://github.com/user-attachments/assets/c9cf8562-3ee1-43cc-9418-091c1d98f80f)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
PlantEnding is an event that tells the plant to do all it's resetting to default values, you should never try and get values from the plant at that point, as the value you get will be inconsistent as it will depend on the order of events. 

Basically, you should never be reporting values at plant ending, as you can't control at what point during resetting that the values are reported.

**Comment by BrianCollinss** [comment]
What do you think of this comment:

> Should APSIM NOT report the value of plant parameters whatsoever when there is no plant on the ground?

The reason I am using PlantEnding is to make sure I have one line of report for each crop even if it is dead before Harvesting. Is there a better option here?

**Comment by par456** [comment]
> Should APSIM NOT report the value of plant parameters whatsoever when there is no plant on the ground?

It doesn't make a lot of sense once the plant is no longer in the ground to report, but I'm guessing you're trying to capture the point just before it dies to do a report (so that if it dies or harvests, each plant has exactly one row).

> The reason I am using PlantEnding is to make sure I have one line of report for each crop even if it is dead before Harvesting. Is there a better option here?

What crop is this needing to be done with? Sorghum and SCRUM have direct calls to EndCrop that make this a little difficult, but the rest of the crops you'd have a manager script calling EndCrop to kill it under certain circumstances. If that's the case, you could invoke an event from that manager script for your report to listen for alongside the harvesting event.

I've had to do this with multi-year wheat rotations in the past, where I had a set date that if it passed, it meant the crop was dead and I should kill it so that I could sow something else the next year. I then reported an event for the report to listen for and print out the status of the dead crop:

```C#
using APSIM.Shared.Utilities;
using Models.Utilities;
using Models.Soils;
using Models.PMF;
using Models.Core;
using System;
using System.Linq;

namespace Models
{
    [Serializable] 
    public class Script : Model
    {
        [Description("Crop")]
        public IPlant Crop { get; set; }
        
        [Link] Clock clock;
        private bool wasAlive { get; set; } = false;
        public event EventHandler PlantDead;
        
        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
            if (Crop.IsReadyForHarvesting)
            {
                Crop.Harvest();
                Crop.EndCrop();
                wasAlive = false;
            }
            
            if (Crop.IsAlive && DateUtilities.DatesAreEqual("31-Dec", clock.Today)) 
            {
                PlantDead.Invoke(this, new EventArgs());
                Crop.EndCrop();
                wasAlive = false;
            }
        }
    }
}
```

and in report it was just this for the events:
```
[Wheat].Harvesting
[Harvest].Script.PlantDead
```

**Comment by BrianCollinss** [comment]
Cheers @par456. I put (this)[https://github.com/APSIMInitiative/ApsimX/discussions/9452#discussioncomment-11538156] here for future references as a good manager script to kill a crop if needed.
