### ISSUE TITLE
The long title in the APSIM UserInterface

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#998]
I understand the full path in the title is useful to find the location in the simulations. However, it uses lots of space in the title bar and can only show one simulation  if simulation in a deep of folder structure (e.g. more than 100 characters).

I suggest to show a shorten title and show full path when mouse hover on it.

**Comment by fai04d** [comment]
Related: On creating a new simulation the name does not show in the tab at all. It will only show if the file is closed and opened again. I'll look at both of these.

**Comment by fai04d** [comment]
Upon further investigation, this will not be possible at this time. The collection of tabs is identified by the name of the tab so must be unique. While it is possible to shorten the name and use tool tips to display the full path, the identifier key is the tab name. This would mean that duplicate tab names would be possible if files with the same name but different locations were opened.

As the tab does not contain information about the simulation it is showing, there is nothing except for the name to link the tab to the simulation. As such, the tab name cannot be changed. 

We can limit the width of the tab and show the rest of the path with a tool tip, but this just shows the first part of the path which is not useful.

We could change how we display the path; e.g. split it up and reverse it so c:\ApsimX\Prototypes\WheatValidation.apsimx becomes something like WheatValidation > Prototypes > ApsimX > C. That way we could limit the tab width and still have a unique identifier.

Similarly the empty tab for a new simulation can't really be fixed since there's no identifying file name until after the sim is saved. 

You can get around this by assuming the newest tab is the one being saved, but since it's possible the user could have multiple new files open or has moved the tabs, this is an invalid assumption. You can't use the selected tab either since both tab controls may have a selected tab.

Leaving this open for further comment.

**Comment by zur003** [comment]
@fai04d In the Gtk# version of the GUI, I decided I didn't like the idea of identifying tabs by name, and refactored to use a different approach. I'm not sure whether I can use the same logic in the Windows.Forms version (it involves looking at the "parentage" of controls), but I'm willing to give it a try.

**Comment by fai04d** [comment]
It's probably not worth trying since it's primarily a cosmetic change. Once you roll the GTK# version out we can implement it then.
